### ISSUE TITLE
202207: Scrum: Active and Deferred functionality

### ISSUE THREAD

**Issue by fmichaelobrien** [GoogleCloudPlatform/pbmm-on-gcp-onboarding#124]
The current landing zone is a partial implementation of a full production deployment.  The following are our plans for enhancing the example landing zone as of mid 2022.

# Todo
- add github issues
- Detail branching/PR/release/tagging strategy doc/procedures
- Detail CD clean deployment on remote org as PR on demand (+1) regression testing (full LZ install with infrastructure - not just actual LZ solution)  
- Provide doc/tooling to add secure zone deployment bastion VM  in addition to default cloud shell and local developer SDK
- Detail admin super-admin role of org admin not required for LZ deploy - role add/delete are automated
- Dev workflow assistance: Fully delete/recreate LZ (reuse procedure for CD redeploys) - up to fully clean organization
- Prepare workaround for 25 limit on VPC Peering connections - after forest of division/team/workload projects passes 25
- Detail Canary CD and ATO traffic generation app with UAT/Firewall config to both exercise the LZ and demo serverless/IaaS/PaaS workload example
- Unclassified/Classified separation of Profile 3/5/6 workloads via VPC separation
- SC2G GC-TIP Dev test version of IPSEC VPN (leave out interconnect for cost) - for cloud to ground workload testing (IE: DB on prem, app on CSP)
- SC2G prepare DNS flows in prep for 30d prior WIF (workload intake form) per workload - have example shared PaaS and custom IaaS/SaaS flows
- CCCS project and zoning for logging agent placement and traffic flows
- Expand zoning on existing shared workload PaaS ready Shared VPC host/service projects with 1:1 service project subnets
- Detail zoning for per-team workload separate VPC with its own perimeter peering and VPC endpoints
- Onboarding: Dev only: Full/Paid Accounts: detail procedure on adding day 1 Full/Paid accounts before LZ deployment - 90d free stays (all others use shared billing)
- Onboarding: Quota: Do GCP projects/billing association quota increase from 5 to 20 before LZ deployment
- Onboarding: Quota: expand projects limit from 20 to 50 in prep for running out of project quota on dev recycling of parameterized project IDs
- RFC-6598 perimeter VPC
- RFC-1918 dev/staging
   SC2G GC-CAP ingress/egress traffic must be decrypted (except finance/health by ip rule exclusion)
   GoC root cert on all endpoints - https://www.gcpedia.gc.ca/wiki/Non-Person_Entity_Public_Key_Infrastructure#Root_Certificate_Authorities
 - detail option to create cluster during root readme or as part of the lz solution
 - Dev workaround for timed out cluster creation (we are usually 5 min from a 30 min timeout on 25 min duration)
 - https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit/issues/33#issuecomment-1239695788

Notes
CE = customer edge
high level diagram at cxp with active/passive router deployments
pre-shared key (psk)
internal /30 bgp peering through tunnel
ipsec phase 1/2 params
fortinet vip
ipsec + bgp configs
bgp through tunnel peering / route table
tunnel failover and app testing 

SC2G
MacSEC protocol through CE routers - for pbmm flows encrypted across gcbb
MacSEC tunnels ground ce to tip ce (mon/tor)
cxp = cloud exchange provider (2 parts vpn(iis/eps, gc-cap
eps = enterprise perimeter security system
pbmm traffix must traverse macsec and ipsec tunnels
non-pbmm traffic via l3 gcbb mpls service
casb (cloud access security broker) for saas (2023)
iaas perimeter firewall, tls, ips, sandboxing, l3 l7 inbound controls, logging
cse/cccs via sc2g

flows from cloud tenancy to cap: 100.96 rfc6598 (snat address)

no snat for tip
cloud interconnect bandwidth shared between cap/tip
manditory rfc6598 (perimeter vpc) and 1918 (dev/stg/prod zones)
100.96 for ext facing fw - distinct between csps
no cloud/ground ip address overlaps

paz:
public zone zip
ean
ean/dmz boundary
dmz
ian
internal zone zip
all flows documented in wif
uat for cloud tenancy
edc rz
cap traversal latency 20-30 ms
2 CxP at each region
approved fw for sc2g not including waf

# Pending/Current - for next release Q4 2022
- ITSG-22 and ITSG-38 Network Zoning compliance (ZIP, DMZ, PAZ, HRZ, MZ...) - https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/issues/161
- Cloud Build us bucket disallowing NA region location restriction has a fix by specifying the bucket as of 20220818 - https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/issues/26
- Upgrade to Organization Policy V2 API - thanks Mike C. https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/issues/26
- Appspot bucket still in us - https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/issues/52
- Remaining _Default and _Required buckets are still in global https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/issues/167
- Branching strategy for CD - https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/issues/154
- Enumerate Network Traffic Flows - https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/issues/149
- Security Appliance: Perimeter based endpoint security (fortigate, palo-alto, IDS) - https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/issues/45
- VPC peering https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/issues/146
- Min/Full deployment types https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/issues/155
- ACM - Access Context Manager - Access Levels - https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/issues/123
- flip ingress FW rule to allow for testing - https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/issues/158
- Artifact Registry Vulnerability Scanning - https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/issues/86
- IAP - https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/issues/51
- serverless VPC access (via existing shared VPC) for traffic generation https://cloud.google.com/vpc/docs/serverless-vpc-access https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/issues/50
- TDD consolidation: add issue on TDD as operations links - where the TDD is kept up to date with the arch and operation of the LZ - in leu of the TDD - use the doc folder as primary reference (from within the TDD) - to avoid continuous TDD pdf generation out-of-band of this repo.  https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/issues/68
- verify audit sinks - getting no log content
- ADFS Identity federation - https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/issues/99
- Workload automation for dev/uat/prd - https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/issues/153
- Naming standards doc (static/dynamic) - best practices - https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/issues/132
- CICD https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/issues/82
 - private catalog in place for always on marketplace (currently restricted by post-deploy non-super-admin user) https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/issues/69
 - Log levels https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/issues/125
- Align with security foundations blueprints for push/pull sync of fixes/enhancements https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/issues/127
- Add Policy Controller rego constraints for validation automation - via blueprints in CFT https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/issues/128
- vpn or dedicated interconnect (partner interconnect and router appliance = future)
- routers for one of above (BGP dynamic routing) https://cloud.google.com/network-connectivity/docs/router
- IGW VPC beyond default (0.0.0.0/0) specific routes + firewall rules for public access (currently all open egress and ssh specific)
- perimeter bridges (prod to common) - IGW defaults off
- https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/issues/169
- SRF (Security Resilience Framework - https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/issues/150

# deferred - customer specific
 - partner interconnect or router appliance - for now simulate with VPN
# deferred
 - bilingual docs/wiki
 
 # reference issues
- prior to continuous deployment - follow the install procedure https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/issues/97

# Discussion
- VPC Peering
AWS = 50 (modifiable)
https://docs.aws.amazon.com/vpc/latest/tgw/transit-gateway-quotas.html
https://us-east-1.console.aws.amazon.com/servicequotas/home/requests
GCP = 25 (modifiable)
ttps://cloud.google.com/vpc/docs/quota?hl=en_US&_ga=2.238983808.-1098396564.1647194753#vpc-peering

**Comment by obriensystems** [comment]
20240406: Closing issue during retrofit/rebase of this TEF V1 based/modified repo to TEF V4 standards
This issue may participate in the LZ refactor after rebase
Query on all issues related to the older V1 version via the tag
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/labels/2024-pre-tef-v4
