### ISSUE TITLE
Minor: naming standard - missing root 2 char prefix on private perimeter VPC name - other 3 ok

### ISSUE THREAD

**Issue by obriensystems** [GoogleCloudPlatform/pbmm-on-gcp-onboarding#135]
cnpecnr-privpervpc-vpc should be cnpecnr-cnprivpervpc-vpc in this case

![Screenshot 2022-08-01 183024](https://user-images.githubusercontent.com/24765473/182256528-037103a4-5285-4f60-a27b-bb1149f746f1.png)

**Comment by fmichaelobrien** [comment]
20240406: Closing issue during retrofit/rebase of this TEF V1 based/modified repo to TEF V4 standards
This issue may participate in the LZ refactor after rebase
Query on all issues related to the older V1 version via the tag
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/labels/2024-pre-tef-v4
