### ISSUE TITLE
Adjust architecture diagrams/evidence from example (202205) to main branch - 1 subnet in prod vpc from 3

### ISSUE THREAD

**Issue by fmichaelobrien** [GoogleCloudPlatform/pbmm-on-gcp-onboarding#136]
Evidence capture was using older example branch - recalculate for main branch
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/blob/main/environments/prod/prod-network.auto.tfvars
obrien.systems = 3 (example branch used for evidence)
cloudnuage.dev = 1 (main branch)

**Comment by obriensystems** [comment]
<img width="1826" alt="Screen Shot 2022-08-02 at 11 14 15" src="https://user-images.githubusercontent.com/24765473/182409764-2294ad5a-0072-43d7-a90b-103162df3442.png">
