### ISSUE TITLE
Flip perimeter prod firewall deny rule for ssh:22 to allow - during dev - or flip name to deny to block

### ISSUE THREAD

**Issue by obriensystems** [GoogleCloudPlatform/pbmm-on-gcp-onboarding#158]
Once we get a range or single tunnel proxy or bastion/IAP access going we can flip back to deny

- https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit/blob/main/solutions/landing-zone/environments/common/firewall/public-perimeter-firewall.yaml#L53
- https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/blob/main/environments/common/prod-public-perimeter-firewall.auto.tfvars#L49
```
    allow-ssh-ingressp = {
      description          = "Allow SSH Connections from the internet"
      direction            = "INGRESS"
      action               = "deny"
      ranges               = ["0.0.0.0/0"]
```

**Comment by fmichaelobrien** [comment]
20240406: Closing issue during retrofit/rebase of this TEF V1 based/modified repo to TEF V4 standards
This issue may participate in the LZ refactor after rebase
Query on all issues related to the older V1 version via the tag
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/labels/2024-pre-tef-v4
