### ISSUE TITLE
As a developer i need to install/modify/update/delete the landing zone - modify/update readme and formal doc

### ISSUE THREAD

**Issue by fmichaelobrien** [GoogleCloudPlatform/pbmm-on-gcp-onboarding#163]
see also
onboarding workloads
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/issues/164
doc
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/issues/163
hub/spoke VPC peering
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/issues/146
example TF install
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/issues/97

20220826: draft in progress
- A full clean install of the LZ (refer to the readme and an example full clean deploy for a recent PR in https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/issues/97 )

- Gather a GCP billing ID for association later
- Involve the (BAA) Billing Account Administrator for the to-be-shared billing ID so that the SA account below can be added as a BAA
- Gather a subdomain for use by organization onboarding
- Involve the IT owner of the domain zone - to be able to add a TXT record to the zone just for organization onboarding
- Create new Cloud Identity account - as super admin (SA) - reference https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/blob/main/docs/google-cloud-onboarding.md#onboarding-category-3b1-3rd-party-email-account---3rd-party-aws-route53-domain-validation---reuse-existing-billing-account 
- Onboard the organization as step 2 of creating the super admin account
- Add the following roles to the SA account before cloning/running the repo
- Clone repo (several options)
- Configure variables
- Check in only bootstrap and common
- Run script - invoking 1 of 4 runs (bootstrap, common, nonprod, prod) - all 4 will run we expect bootstrap only to pass
- Fix any issues with config blocking common builds
- Commit common
- If common passes, commit nonprod config
- If nonprod passes, commit prod config
- Modifications: 
- Do a small FW change on prod - commit, observe changes in VPC Networks view and Asset Inventory change summary
- Upstream updates: pending
- Full LZ retrofit: pending
- Full LZ delete: pending

**Comment by obriensystems** [comment]
20240406: Closing issue during retrofit/rebase of this TEF V1 based/modified repo to TEF V4 standards
This issue may participate in the LZ refactor after rebase
Query on all issues related to the older V1 version via the tag
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/labels/2024-pre-tef-v4
