### ISSUE TITLE
Quota mitigation: Add terraform destroy option wrapper to bootstrap.sh to enable restarts/deletion of services for long lived deployments - without using project delete

### ISSUE THREAD

**Issue by fmichaelobrien** [GoogleCloudPlatform/pbmm-on-gcp-onboarding#18]
Several of our deployments are used for dev purposes.  The option to programmatically clean the project is an option that will work around both the billing/project association quota (lower for Identity vs workspace configured accounts) and the 30 day limit where deleted project consume project quota

**Comment by obriensystems** [comment]
20240406: Closing issue during retrofit/rebase of this TEF V1 based/modified repo to TEF V4 standards
This issue may participate in the LZ refactor after rebase
Query on all issues related to the older V1 version via the tag
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/labels/2024-pre-tef-v4
