### ISSUE TITLE
Adjust writeids.sh to handle organization/folder without 3 tfvars comment/uncomments - use the script to flip the install location

### ISSUE THREAD

**Issue by fmichaelobrien** [GoogleCloudPlatform/pbmm-on-gcp-onboarding#181]
The following needs additional work to fully handle organization or folder instalation
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/blob/main/writeids.sh#L74

Checking the sh, I wrote that to help out with git merges (do/undo changes) - I usually deploy directly a folder off the org (but 1 lz per org during testing) - you can put the org id there - but the code is defaulting to folder - 3 changes required in the tfvars - 
switch the 2 lines at
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/blob/main/environments/common/common.auto.tfvars#L33
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/blob/main/environments/bootstrap/bootstrap.auto.tfvars#L32
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/blob/main/environments/bootstrap/organization-config.auto.tfvars#L29

I'll put a jira in to switch these via the script

**Comment by obriensystems** [comment]
20240406: Closing issue during retrofit/rebase of this TEF V1 based/modified repo to TEF V4 standards
This issue may participate in the LZ refactor after rebase
Query on all issues related to the older V1 version via the tag
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/labels/2024-pre-tef-v4
