### ISSUE TITLE
Find original naming/tagging standard doc referenced in gcp TF modules - relate to DI 132

### ISSUE THREAD

**Issue by fmichaelobrien** [GoogleCloudPlatform/pbmm-on-gcp-onboarding#182]
see "Provides naming convention defined by the SSC Naming and Tagging Standard for GCP document."

https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/tree/main/modules/naming-standard/modules/gcp/cloud_function#outputs

- get access the original naming standard defined in the readme (original source/fork?)
- relate to in-progress naming standard design issue
- expand naming standard with tagging standard
- https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/issues/132

**Comment by svershin** [comment]
It lives here: https://gccollab.ca/file/view/3634499/ennaming-and-tagging-standardsfr

However, I am not an employee of the Government of Canada, and don't have access.

I believe this document should be available to the public, since future work on GCP will need to adhere to the guidance therein.

**Comment by fmichaelobrien** [comment]
Sounds good, I have a gcollab account (contractors are welcome),. I'll check access and PB level when I get back

**Comment by fmichaelobrien** [comment]
This one is under my G account
<img width="1561" alt="Screen Shot 2022-09-30 at 10 13 01 AM" src="https://user-images.githubusercontent.com/94715080/193289051-7e14d870-d003-4773-b2b3-320d08f25468.png">
downloading internally
https://gccollab.ca/file/download/3634499

**Comment by fmichaelobrien** [comment]
20240406: Closing issue during retrofit/rebase of this TEF V1 based/modified repo to TEF V4 standards
This issue may participate in the LZ refactor after rebase
Query on all issues related to the older V1 version via the tag
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/labels/2024-pre-tef-v4
