### ISSUE TITLE
Regular watch/sync with repo fork from terraform-google-modules/terraform-google-bootstrap

### ISSUE THREAD

**Issue by fmichaelobrien** [GoogleCloudPlatform/pbmm-on-gcp-onboarding#19]
shadow
https://github.com/terraform-google-modules/terraform-google-bootstrap

**Comment by obriensystems** [comment]
part of #360

**Comment by obriensystems** [comment]
20240406: Closing issue during retrofit/rebase of this TEF V1 based/modified repo to TEF V4 standards
This issue may participate in the LZ refactor after rebase
Query on all issues related to the older V1 version via the tag
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/labels/2024-pre-tef-v4
