### ISSUE TITLE
Traffic Generation: Add stub https/L7 Load  external Balancer with attached Cloud Armor in perimeter to serve up static or cloud run site

### ISSUE THREAD

**Issue by obriensystems** [GoogleCloudPlatform/pbmm-on-gcp-onboarding#190]
for lb, vpc-flow, firewall logs and armor attachment until we get the security appliance added

Collab:  https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit/issues/163

**Comment by fmichaelobrien** [comment]
20240406: Closing issue during retrofit/rebase of this TEF V1 based/modified repo to TEF V4 standards
This issue may participate in the LZ refactor after rebase
Query on all issues related to the older V1 version via the tag
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/labels/2024-pre-tef-v4
