### ISSUE TITLE
Control code to ITSG-33 mapping and labels - add code comments and GCP labelling

### ISSUE THREAD

**Issue by fmichaelobrien** [GoogleCloudPlatform/pbmm-on-gcp-onboarding#2]
see https://github.com/canada-ca/accelerators_accelerateurs-gcp/issues/18

We need a way to visually and programmatically link code to controls (in addition to control to code) - for human and IAC validation/reporting

For example which terraform module covers SC-8 TRANSMISSION CONFIDENTIALITY AND INTEGRITY

Doc only example:
https://github.com/canada-ca/cloud-guardrails/blob/master/EN/07_Protect-Data-in-Transit.md

link/label to (I need to verify)
SC-8 TRANSMISSION CONFIDENTIALITY AND INTEGRITY
https://cyber.gc.ca/en/guidance/annex-3a-security-control-catalogue-itsg-33#a316sc8
ITSG_33_SC_8
and
SC-12 CRYPTOGRAPHIC KEY ESTABLISHMENT AND MANAGEMENT
https://cyber.gc.ca/en/guidance/annex-3a-security-control-catalogue-itsg-33#a316sc12
ITSG_33_SC_12

Code example:
https://github.com/canada-ca/cloud-guardrails/blob/master/EN/05_Data-Location.md

and
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/blob/main/environments/common/main.tf#L84
link/label to ?
SC-7 BOUNDARY PROTECTION
ITSG_33_SC_7
https://cyber.gc.ca/en/guidance/annex-3a-security-control-catalogue-itsg-33#a316sc7
or
PE-18 LOCATION OF INFORMATION SYSTEM COMPONENTS
ITSG_33_PE_18
https://cyber.gc.ca/en/guidance/annex-3a-security-control-catalogue-itsg-33#a311pe18

Additions to PBMM doc
firewall, AC-12, IAM, functions
AU-3(2)
AU-4
AU-5
AU-6(4)
SC-28(1)
SI-3(1)

**Comment by fmichaelobrien** [comment]
[security_controls_services_automation_mappings.csv](https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/files/8312089/security_controls_services_automation_mappings.csv)

**Comment by fmichaelobrien** [comment]
Ongoing: terraform code to itsg-33 control to gcp service mapping
<img width="1214" alt="modules-controls-service-mapping-overview" src="https://user-images.githubusercontent.com/94715080/162195042-03220ced-35bd-43a0-ae41-0a93adada892.png">

**Comment by fmichaelobrien** [comment]
<img width="1246" alt="modules-controls-service-mapping-overview" src="https://user-images.githubusercontent.com/94715080/162511794-8dfd5429-c6aa-426f-8bdc-f2ed15ebe8e2.png">

**Comment by fmichaelobrien** [comment]
<img width="1220" alt="modules-controls-service-mapping-overview" src="https://user-images.githubusercontent.com/94715080/165201499-1bf67cb7-c4f2-4d71-9e22-290569c15a6c.png">

**Comment by fmichaelobrien** [comment]
Answer question on GR 8 network segmentation

https://github.com/canada-ca/cloud-guardrails/issues/96

**Comment by obriensystems** [comment]
See exercise 
https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit/issues/560

at compliance dashboard and automated security control mapping extract - so we don't have to manually create one of these

<img width="1236" alt="Screenshot 2023-11-12 at 19 22 33" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/5495d07c-df87-41b6-9c51-7a3f44795485">

or the wiki based editing of

<img width="2270" alt="Screenshot 2023-11-12 at 19 24 11" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/fda73446-94a7-4b47-b338-34c67b5f9f5c">

**Comment by obriensystems** [comment]
20240406: Closing issue during retrofit/rebase of this TEF V1 based/modified repo to TEF V4 standards
This issue may participate in the LZ refactor after rebase
Query on all issues related to the older V1 version via the tag
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/labels/2024-pre-tef-v4
