### ISSUE TITLE
GR12 - add disable public marketplace resource policy constraints/commerceorggovernance.disablePublicMarketplace for compliance

### ISSUE THREAD

**Issue by fmichaelobrien** [GoogleCloudPlatform/pbmm-on-gcp-onboarding#205]
Set the following to enforced to implement Guardrail 12
constraints/commerceorggovernance.disablePublicMarketplace

Chris, you are Excellent!!! - right there on page 1 - didnt see that - but time for an exhaustive run through the 87
This should fix GR 12 - will test installing elastisearch.
will go in both LZ's
thanks for that

see
https://github.com/canada-ca/accelerators_accelerateurs-gcp/issues/52

<img width="949" alt="Screen Shot 2022-11-14 at 10 34 06 PM" src="https://user-images.githubusercontent.com/94715080/201820253-90ffad48-c5bb-4a8d-9d38-c9fd2a095864.png">

**Comment by obriensystems** [comment]
<img width="1542" alt="Screen Shot 2022-11-22 at 22 23 43" src="https://user-images.githubusercontent.com/24765473/203463478-a9fd1406-ecbf-4ad7-bf1a-267767f4323a.png">

**Comment by obriensystems** [comment]
Found out all boolean org policies - existing 2 and new one are having no effect - all 3 are still the default false
PR on hold while fixing this in main

**Comment by obriensystems** [comment]
set defaults to true and removed commas

<img width="1099" alt="Screen Shot 2022-11-22 at 23 13 05" src="https://user-images.githubusercontent.com/24765473/203468027-4e1432a5-49a4-44df-b04a-4b97041eae64.png">

```
  local_policy_boolean = {
    "constraints/commerceorggovernance.disablePublicMarketplace" = true


Step #2 - "tf plan": Terraform will perform the following actions:
Step #2 - "tf plan": 
Step #2 - "tf plan":   # module.core-org-policy.google_organization_policy.boolean["constraints/commerceorggovernance.disablePublicMarketplace"] will be created
Step #2 - "tf plan":   + resource "google_organization_policy" "boolean" {
Step #2 - "tf plan":       + constraint  = "constraints/commerceorggovernance.disablePublicMarketplace"
Step #2 - "tf plan":       + etag        = (known after apply)
Step #2 - "tf plan":       + id          = (known after apply)
Step #2 - "tf plan":       + org_id      = "959133349631"
Step #2 - "tf plan":       + update_time = (known after apply)
Step #2 - "tf plan":       + version     = (known after apply)
Step #2 - "tf plan": 
Step #2 - "tf plan":       + boolean_policy {
Step #2 - "tf plan":           + enforced = true
Step #2 - "tf plan":         }
Step #2 - "tf plan":     }
```

**Comment by fmichaelobrien** [comment]
20240406: Closing issue during retrofit/rebase of this TEF V1 based/modified repo to TEF V4 standards
This issue may participate in the LZ refactor after rebase
Query on all issues related to the older V1 version via the tag
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/labels/2024-pre-tef-v4
