### ISSUE TITLE
Add perimeter stub prior to NGFW cluster onboarding with peering to the shared VPC

### ISSUE THREAD

**Issue by fmichaelobrien** [GoogleCloudPlatform/pbmm-on-gcp-onboarding#220]
See
- CCCS Baseline Security Requirements for Network Security Zones V2.0 https://cyber.gc.ca/sites/default/files/cyber/publications/itsp80022-e.pdf
Start with rebasing the existing environment

https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/issues/97

**Comment by obriensystems** [comment]
Get 2 new environments/orgs up
org1 = development of PR changes for peering
org2 = client simulated org with pre-PR main state - that we will apply this 220 PR changes to after prototyping in org1

**Comment by obriensystems** [comment]
Fix https://github.com/hashicorp/terraform/issues/31692 first

**Comment by obriensystems** [comment]
working 
<img width="1179" alt="Screen Shot 2023-01-28 at 13 19 04" src="https://user-images.githubusercontent.com/24765473/215284119-71e78826-80dd-4553-b5ff-91235ee11a1c.png">


<img width="1719" alt="Screen Shot 2023-01-28 at 13 18 35" src="https://user-images.githubusercontent.com/24765473/215284101-b790717b-339f-4719-8824-b9cca88862ea.png">

**Comment by obriensystems** [comment]
Triage older system for tf version
- add to the push cloud build yaml
```
root_@cloudshell:~/cloudshell_open/pbmm-on-gcp-onboarding (cnpe-cnd-cndev-sbx)$ git diff
diff --git a/modules/cloudbuild/templates/cloudbuild-push-request.yaml b/modules/cloudbuild/templates/cloudbuild-push-request.yaml
index 3495bbe..acc0fbf 100644
--- a/modules/cloudbuild/templates/cloudbuild-push-request.yaml
+++ b/modules/cloudbuild/templates/cloudbuild-push-request.yaml
@@ -14,6 +14,19 @@ steps:
               echo "*************************************************"
               terraform init || exit 1

+- id: 'tf version'
+  name: ${_DEFAULT_REGION}-docker.pkg.dev/${_SEED_PROJECT_ID}/${_GAR_REPOSITORY}/terraform
+  dir: "${_WORKSTREAM_PATH}"
+  entrypoint: 'sh'
+  args:
+  - '-c'
+  - |
+              echo ""
+              echo "*************** TERRAFORM VERSION ******************"
+              echo "******* At environment: ${_WORKSTREAM_PATH} *************"
+              echo "*************************************************"
+              terraform --version || exit 1
```
results
https://console.cloud.google.com/cloud-build/builds;region=global/1ec94347-7cae-41f6-8d22-0d57878f2a08;step=1?project=cnpe-cnd-cndev-sbx&supportedpurview=project
```
Terraform v1.0.10
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v3.90.1
+ provider registry.terraform.io/hashicorp/google-beta v4.50.0
+ provider registry.terraform.io/hashicorp/null v3.2.1
+ provider registry.terraform.io/hashicorp/random v3.4.3

Your version of Terraform is out of date! The latest version
is 1.3.7. You can update by downloading from https://www.terraform.io/downloads.html
```

**Comment by obriensystems** [comment]
Fix is only required for bootstrap (which runs outside the CB container directly on the gcloud shell (which runs 1.3.7), for all other common/non-prod/prod we can continue to use terraform 1.0.10 and experimental optional attributes

**Comment by fmichaelobrien** [comment]
20240406: Closing issue during retrofit/rebase of this TEF V1 based/modified repo to TEF V4 standards
This issue may participate in the LZ refactor after rebase
Query on all issues related to the older V1 version via the tag
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/labels/2024-pre-tef-v4
