### ISSUE TITLE
automate billing id and organization query for parameter writing

### ISSUE THREAD

**Issue by fmichaelobrien** [GoogleCloudPlatform/pbmm-on-gcp-onboarding#23]
nuage issue reference
export BILLING_ACCOUNT=$(gcloud alpha billing projects describe $PROJECT_ID '--format=value(billingAccountName)' | sed 's/.*\///')
export ORG_ID=$(gcloud projects get-ancestors ${PROJECT_ID} --format='get(id)' | tail -1)

https://github.com/canada-ca/accelerators_accelerateurs-gcp/issues/14

**Comment by obriensystems** [comment]
20240406: Closing issue during retrofit/rebase of this TEF V1 based/modified repo to TEF V4 standards
This issue may participate in the LZ refactor after rebase
Query on all issues related to the older V1 version via the tag
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/labels/2024-pre-tef-v4
