### ISSUE TITLE
do not use shared billing for guardrails and audit projects - ok for prod/non-prod projects - due to remote org permissions

### ISSUE THREAD

**Issue by obriensystems** [GoogleCloudPlatform/pbmm-on-gcp-onboarding#230]
the guardrails and audit projects will experience IAM permissions issues like creating log sinks due to lack of remote org IAM permissions.  We are ok with the existing billing account user set on the remote org

see #229 

https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/blob/main/environments/common/common.auto.tfvars#L66

**Comment by obriensystems** [comment]
working
<img width="1729" alt="Screen Shot 2023-01-30 at 23 31 06" src="https://user-images.githubusercontent.com/24765473/215665816-633c7c5c-4c28-48db-9afc-8298b2f47b49.png">

**Comment by fmichaelobrien** [comment]
20240406: Closing issue during retrofit/rebase of this TEF V1 based/modified repo to TEF V4 standards
This issue may participate in the LZ refactor after rebase
Query on all issues related to the older V1 version via the tag
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/labels/2024-pre-tef-v4
