### ISSUE TITLE
Switching the billing account on projects will update in place without switching billing/project association - manually switch billing and re-trigger the cloud build

### ISSUE THREAD

**Issue by obriensystems** [GoogleCloudPlatform/pbmm-on-gcp-onboarding#236]
If the billing account changes - the project will get updated in place without re-associating the billing id.
terraform will not pick up the change - the project will need to be manually deleted

<img width="1724" alt="Screen Shot 2023-01-31 at 08 57 55" src="https://user-images.githubusercontent.com/24765473/215780176-94281e4d-9741-47b8-846a-db7c0876b60e.png">

<img width="1723" alt="Screen Shot 2023-01-31 at 08 56 48" src="https://user-images.githubusercontent.com/24765473/215779873-201fd951-d9c3-4dfb-8376-c7cf6d21e5d5.png">

switch billing manually
<img width="1057" alt="Screen Shot 2023-01-31 at 08 58 58" src="https://user-images.githubusercontent.com/24765473/215780536-ca05cfdc-fbc9-4b1a-bf28-c58ebb7b6b25.png">

<img width="1058" alt="Screen Shot 2023-01-31 at 09 05 45" src="https://user-images.githubusercontent.com/24765473/215782177-fcf4c48e-bd3b-4958-ab78-a3d803156c9b.png">

**Comment by fmichaelobrien** [comment]
20240406: Closing issue during retrofit/rebase of this TEF V1 based/modified repo to TEF V4 standards
This issue may participate in the LZ refactor after rebase
Query on all issues related to the older V1 version via the tag
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/labels/2024-pre-tef-v4
