### ISSUE TITLE
shadow: Prototype/yaml SCED/SC2G HA partner interconnect - cloud to ground for profile 5 and 6

### ISSUE THREAD

**Issue by fmichaelobrien** [GoogleCloudPlatform/pbmm-on-gcp-onboarding#249]
See private DNS work in #286 - as a result of transitive peering - add a 2nd interconnect set in non-prod in #289
Configure IaC in TF for partner interconnect overlay 

https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/pull/258
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/pull/259
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/pull/260
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/pull/261

shadow already prototyped cologix partner interconnect running in KCC LZ V2 https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit/issues/298
Create Terraform version of Kubernetes Config Controller based work in 298
- adjust TEF V3 backport https://github.com/terraform-google-modules/terraform-example-foundation/issues/940

TODO
- Traffic Engineering across multiple interconnects through cloud router + BGP sessions - https://cloud.google.com/network-connectivity/docs/router/how-to/updating-priority
- Investigate hub spoke Network Connectivity Center - as part of partner interconnect enabled transitive peering solution (Around the 25 limit) 
#78  
- https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit/blob/dev/solutions/landing-zone/architecture.md#di-05-complete-network-design
- Need to spin up/verify an alternative to regular peering (due to the 25 limit/project) for the hub-spoke pattern - https://cloud.google.com/network-connectivity/docs/network-connectivity-center/concepts/overview over the normal https://cloud.google.com/architecture/deploy-hub-spoke-vpc-network-topology

R1: 
Implement SCED/SC2G for GCP 

R2:
Use MacSEC over IPSec

R3:
partner interconnect over direct connect

R4:
ASNs
Google: 16550

R5: Interconnect redundancy
- https://cloud.google.com/network-connectivity/docs/interconnect/concepts/best-practices#use_activeactive_vlan_attachments
- https://cloud.google.com/network-connectivity/docs/interconnect/how-to/partner/creating-vlan-attachments#gcloud

R6: VPC Global Dynamic Routing and traffic shaping
- https://docs.equinix.com/en-us/Content/Interconnection/Fabric/connections/Fabric-connect-google.htm
- https://cloud.google.com/network-connectivity/docs/interconnect/support/faq#ilb-backends
- https://registry.terraform.io/providers/hashicorp/google/3.22.0/docs/resources/compute_interconnect_attachment

Phase 1: brute force minimal connection test 
Phase 2: Architecture final review 

Initial work item is to start an interconnect and get the SDN UID to tag traffic.  Testing out https://cloud.google.com/network-connectivity/docs/interconnect/concepts/partner-overview#provisioning

## Links
Slide 19, 18 were used a lot in presentations at IRCC and ISED (from 2019 but still valid) - for profile 5/6
https://wiki.gccollab.ca/images/7/75/GC_Cloud_Connection_Patterns.pdf
review:  https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/tree/master/blueprints/networking/private-cloud-function-from-onprem
review https://cloud.google.com/network-connectivity/docs/interconnect/concepts/ha-vpn-interconnect

slide 65 in progress in 
https://docs.google.com/presentation/d/13sjT2tJ4yLIYGRREE3wBrylB1OvcEMpKdquVuJB_nX4/edit?resourcekey=0-N3DruQaiutFvZ98HTT7-vQ#slide=id.g2223ba5ee2b_0_665

20230717
<img width="1163" alt="Screenshot 2023-07-17 at 11 55 32" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/e10b2eb4-51fa-4333-9b6a-e75550a67a12">

20230413
![Screen Shot 2023-04-13 at 3 12 05 PM](https://user-images.githubusercontent.com/94715080/231859878-e70f7c40-4d01-481f-b6d6-f69b8eb11d63.png)

20230321
<img width="1463" alt="Screen Shot 2023-03-21 at 11 51 51 PM" src="https://user-images.githubusercontent.com/94715080/226797702-e3c2f9c9-6928-4bf0-ab6c-d22e8f5acc2f.png">

https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/tree/master/blueprints/networking/psc-hybrid
## Organization Policies
- subset of https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit/tree/main/solutions/org-policies/organization
- add org policy admin role
- constraints/compute.disableGlobalSerialPortAccess
- constraints/compute.vmExternalIpAccess

# Architecture Notes
- Multiple Shared VPCs per Host Project - sharing interconnect/VPN https://cloud.google.com/architecture/best-practices-vpc-design#connecting_multiple_networks

**Comment by obriensystems** [comment]
20230710: update for partner interconnect
- clean org with minimal terraform LZ - use the TOC version from https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/issues/251#issuecomment-1629103711
- add services project to host project
<img width="652" alt="Screenshot 2023-07-10 at 14 30 53" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/1bf28698-9674-4377-b819-30657ed215a2">

**Comment by fmichaelobrien** [comment]
- bgp route changes - some way to view/manage bgp routing on top of the discovered/static routes
- in AWS one CSR logical instance via direct connect - multi regional router
A: look at NCC for transit gateway like behaviour
- Equinix is the standby, cologix is the active - create 4 vlans 2 to each by key 
- adjust router logic to send traffic to cologix first.- check link
- put test VM right into non-prod host
- no peering between perimeter and host projects - waiting for NGFW?
- switch hardcoded region to 1 in main.tf
- LZ V1b - fix cap project name but lc project id
- instructions fix: for non-CSR apply - switch to project owning VPC
- finish network diagram subset

**Comment by obriensystems** [comment]
Update:
To switch billing accounts from the original 10% script run bootstrap - where the original terraform service account is created
- add the TF SA to both billing Billing Account Administrator and IAM BAA on both the original and target BIDs
- for example - switching back to the original BID from the target gets an error because although originally BAA was not required - it is now
```
Step #4 - "tf apply": │ Error: Error setting billing account "01BFA...3B" for project "projects/tzpe-....z-de": googleapi: Error 403: The caller does not have permission, forbidden

```
<img width="1821" alt="Screenshot 2023-07-24 at 08 41 00" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/64e84c04-cb4e-4a9f-be8d-ee1ae8823157">

<img width="124" alt="Screenshot 2023-07-24 at 08 41 39" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/76d08205-6e81-4370-a601-c9f8c0ea4f08">

<img width="140" alt="Screenshot 2023-07-24 at 08 46 36" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/7a5dc6cd-34ca-4c45-ac41-eb4ae502c8a5">

<img width="497" alt="Screenshot 2023-07-24 at 08 45 57" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/9323b93c-00bd-48e4-96bc-10053e0c34cc">

also replaced iam owner on tfsa
<img width="731" alt="Screenshot 2023-07-24 at 08 52 44" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/9f171952-bcf6-4d01-abe1-48f9f6badf79">

**Comment by obriensystems** [comment]
PR:
```
        new file:   modules/20-partner-interconnect/main.tf
        new file:   modules/20-partner-interconnect/outputs.tf
        new file:   modules/20-partner-interconnect/variables.tf
```

```
Step #3 - "tf plan": Terraform will perform the following actions:
Step #3 - "tf plan": 
Step #3 - "tf plan":   # module.partner-interconnect-primary.google_compute_router.router1 will be created
Step #3 - "tf plan":   + resource "google_compute_router" "router1" {
Step #3 - "tf plan":       + creation_timestamp = (known after apply)
Step #3 - "tf plan":       + id                 = (known after apply)
Step #3 - "tf plan":       + name               = "router-1"
Step #3 - "tf plan":       + network            = "tzpecnr-nonprod-svpc-vpc"
Step #3 - "tf plan":       + project            = "tzpe-tlz-tlz-np2"
Step #3 - "tf plan":       + region             = "northamerica-northeast1"
Step #3 - "tf plan":       + self_link          = (known after apply)
Step #3 - "tf plan": 
Step #3 - "tf plan":       + bgp {
Step #3 - "tf plan":           + advertise_mode = "DEFAULT"
Step #3 - "tf plan":           + asn            = 16550
Step #3 - "tf plan":         }
Step #3 - "tf plan":     }
```

**Comment by obriensystems** [comment]
interconnect part of the phased PR
```
        modified:   environments/nonprod/main.tf
        modified:   modules/20-partner-interconnect/main.tf
        modified:   modules/20-partner-interconnect/outputs.tf
```

**Comment by obriensystems** [comment]
Finish naming conventions and parameterization

```
        modified:   environments/nonprod/main.tf
        modified:   environments/nonprod/nonp-interconnect.auto.tfvars
        modified:   modules/20-partner-interconnect/main.tf
        modified:   modules/20-partner-interconnect/variables.tf
        modified:   environments/nonprod/variables.tf
```

**Comment by obriensystems** [comment]
Add prod
```
root_@cloudshell:~/lz-tls/_lz2/pbmm-on-gcp-onboarding (lz-tls)$ git status
On branch main
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        new file:   environments/prod/prod-interconnect.auto.tfvars

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   environments/prod/main.tf
        modified:   environments/prod/variables.tf





Step #3 - "tf plan": Plan: 5 to add, 2 to change, 0 to destroy.

Step #4 - "tf apply": *************** TERRAFORM APPLY ******************
Step #4 - "tf apply": ******* At environment: environments/prod ***********
Step #4 - "tf apply": *************************************************
tep #4 - "tf apply": module.net-host-prj.module.network["tlzprod-svpc"].module.subnets["prsubnet02"].google_compute_subnetwork.subnetwork: Modifying... [id=projects/tzpe-tlz-tlzprod-host4/regions/northamerica-northeast1/subnetworks/tzpecnr-prsubnet02-host4-snet]
Step #4 - "tf apply": module.net-host-prj.module.network["tlzprod-svpc"].module.subnets["prsubnet02"].google_compute_subnetwork.subnetwork: Modifications complete after 1s [id=projects/tzpe-tlz-tlzprod-host4/regions/northamerica-northeast1/subnetworks/tzpecnr-prsubnet02-host4-snet]
Step #4 - "tf apply": module.partner-interconnect-primary.google_compute_router.router1: Creating...
Step #4 - "tf apply": module.partner-interconnect-primary.google_compute_router.router1: Still creating... [10s elapsed]
Step #4 - "tf apply": module.partner-interconnect-primary.google_compute_router.router1: Still creating... [20s elapsed]
Step #4 - "tf apply": module.partner-interconnect-primary.google_compute_router.router1: Creation complete after 21s [id=projects/tzpe-tlz-tlzprod-host4/regions/northamerica-northeast1/routers/interconnect-prod-router]
Step #4 - "tf apply": module.partner-interconnect-primary.google_compute_interconnect_attachment.on_prem1: Creating...
Step #4 - "tf apply": module.partner-interconnect-primary.google_compute_interconnect_attachment.on_prem2: Creating...
Step #4 - "tf apply": module.partner-interconnect-primary.google_compute_interconnect_attachment.on_prem4: Creating...
Step #4 - "tf apply": module.partner-interconnect-primary.google_compute_interconnect_attachment.on_prem3: Creating...
Step #4 - "tf apply": module.partner-interconnect-primary.google_compute_interconnect_attachment.on_prem1: Still creating... [10s elapsed]
Step #4 - "tf apply": module.partner-interconnect-primary.google_compute_interconnect_attachment.on_prem4: Still creating... [10s elapsed]
Step #4 - "tf apply": module.partner-interconnect-primary.google_compute_interconnect_attachment.on_prem2: Still creating... [10s elapsed]
Step #4 - "tf apply": module.partner-interconnect-primary.google_compute_interconnect_attachment.on_prem3: Still creating... [10s elapsed]
Step #4 - "tf apply": module.partner-interconnect-primary.google_compute_interconnect_attachment.on_prem4: Creation complete after 12s [id=projects/tzpe-tlz-tlzprod-host4/regions/northamerica-northeast1/interconnectAttachments/vlan-attach-equinix-4]
Step #4 - "tf apply": module.partner-interconnect-primary.google_compute_interconnect_attachment.on_prem2: Creation complete after 12s [id=projects/tzpe-tlz-tlzprod-host4/regions/northamerica-northeast1/interconnectAttachments/vlan-attach-cologix-2]
Step #4 - "tf apply": module.partner-interconnect-primary.google_compute_interconnect_attachment.on_prem1: Still creating... [20s elapsed]
Step #4 - "tf apply": module.partner-interconnect-primary.google_compute_interconnect_attachment.on_prem3: Still creating... [20s elapsed]
Step #4 - "tf apply": module.partner-interconnect-primary.google_compute_interconnect_attachment.on_prem1: Creation complete after 22s [id=projects/tzpe-tlz-tlzprod-host4/regions/northamerica-northeast1/interconnectAttachments/vlan-attach-cologix-1]
Step #4 - "tf apply": module.partner-interconnect-primary.google_compute_interconnect_attachment.on_prem3: Still creating... [30s elapsed]
Step #4 - "tf apply": module.partner-interconnect-primary.google_compute_interconnect_attachment.on_prem3: Creation complete after 32s [id=projects/tzpe-tlz-tlzprod-host4/regions/northamerica-northeast1/interconnectAttachments/vlan-attach-equinix-3]
Step #4 - "tf apply": ╷

```
<img width="1757" alt="Screenshot 2023-07-25 at 10 35 49" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/0818f864-4bae-45e2-9ba7-876cb696faf8">

<img width="1784" alt="Screenshot 2023-07-25 at 10 36 26" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/ad7b084b-b951-438c-8699-9cac25db8029">

**Comment by fmichaelobrien** [comment]
# Customer side requirements

Also, for DNS forwarding return - I thought I read that the 34.199.192.0/19 range was implicitly advertised but hidden on all BGP routing - it turns out it is up to the customer to advertise this - by adding a custom route directly on the interconnect/vpn router beside the dynamic BGP routes - found this a bit odd but I can see optional case for those not wanting cloud to ground and only ground to cloud for SCED/SC2G
- Key for cloud to ground private DNS forwarded queries - add the network-patterns https://docs.google.com/presentation/d/13sjT2tJ4yLIYGRREE3wBrylB1OvcEMpKdquVuJB_nX4/edit?resourcekey=0-N3DruQaiutFvZ98HTT7-vQ#slide=id.g1154b3b950f_2_3152 slide 27 referenced ingress proxy 34.199.192.0/19 as a custom route on the interconnect router (in addition to dynamic subnet routes) - without this DNS queries from gcp to on-prem will not resolve.
- specifically - https://cloud.google.com/dns/docs/policies#return-route
"For Cloud VPN tunnels that use dynamic routing or for Cloud Interconnect, [configure a custom route advertisement](https://cloud.google.com/network-connectivity/docs/router/how-to/advertising-custom-ip) for 35.199.192.0/19 on the BGP session of the Cloud Router that manages the tunnel or VLAN attachment."
- https://cloud.google.com/network-connectivity/docs/router/how-to/advertising-custom-ip
- see also https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit/issues/468
- on top of the partner/direct interconnect add the following
- firewall rule to open incoming DNS query traffic from the private cloud DNS forwarding zone ns 35.199.192.0/19 - https://cloud.google.com/dns/docs/zones/forwarding-zones#firewall-rules
- add 34.199.192.0/19 to the ingress policy on prem
- raise an issue with GCP on whether we can add a customer provided IP for return DNS traffic

**Comment by fmichaelobrien** [comment]
20240406: Closing issue during retrofit/rebase of this TEF V1 based/modified repo to TEF V4 standards
This issue may participate in the LZ refactor after rebase
Query on all issues related to the older V1 version via the tag
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/labels/2024-pre-tef-v4
