### ISSUE TITLE
Tag main branch before merging major PR change 

### ISSUE THREAD

**Issue by fmichaelobrien** [GoogleCloudPlatform/pbmm-on-gcp-onboarding#25]
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/tags

for below or split PR of below
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/pull/21

**Comment by obriensystems** [comment]
20240406: Closing issue during retrofit/rebase of this TEF V1 based/modified repo to TEF V4 standards
This issue may participate in the LZ refactor after rebase
Query on all issues related to the older V1 version via the tag
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/labels/2024-pre-tef-v4
