### ISSUE TITLE
ATO Prep: Add/Verify IAM organization policy - advisory notifications via 2h delay email/iam/logging entries visibility done through terraform

### ISSUE THREAD

**Issue by obriensystems** [GoogleCloudPlatform/pbmm-on-gcp-onboarding#252]
Add/Verify the advisory notification feature for organization policy changes - on deployment actions down to tier 4 done through kcc.
Note there is a 2h delay in the email advisory but the log triggers are immediate

email

<img width="1324" alt="Screenshot 2023-07-15 at 10 11 32" src="https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit/assets/24765473/b32f1849-9ad3-42b2-867d-63cf4ed7f936">

```
What happened
The activity occurred from July 15, 2023 at 4:00:00 AM UTC to July 15, 2023 at 6:00:00 AM UTC in your ob...v organization. Review the following details:

Sensitive actions at the organization level
Organization policies changed at the organization level
This action was taken 2 times

July 15, 2023 at 4:21:27 AM UTC:
Policy: compute.requireShieldedVm
Policy action: Updated
By: michael@obri...v

July 15, 2023 at 4:22:48 AM UTC:
Policy: compute.vmExternalIpAccess
Policy action: Updated
By: michael@obr...v
```
console

<img width="1073" alt="Screenshot 2023-07-15 at 10 12 02" src="https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit/assets/24765473/1ff96592-9bff-42c0-bce2-6dd4861bae1b">

logs
<img width="1692" alt="Screenshot 2023-07-15 at 10 14 17" src="https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit/assets/24765473/f9910461-648c-497f-81f4-eaf0c4a8e026">

```
{
insertId: "-2hk3lecaof"
jsonPayload: {
access: {6}
actionTime: "2023-07-15T04:22:46.359548Z"
actionType: "change_organization_policy"
affectedResources: [1]
learnMoreUri: "https://cloud.google.com/security-command-center/docs/concepts-sensitive-actions-overview"
sourceLogIds: [1]}
logName: "organizations/583....8/logs/sensitiveaction.googleapis.com%2Faction"
receiveTimestamp: "2023-07-15T04:22:48.916254323Z"
resource: {2}
severity: "NOTICE"
timestamp: "2023-07-15T04:22:46.359548Z"
}
```

example - turn off two of the org policies to allow for the following HPC Nvidia GPU CUDA GKE image

https://console.cloud.google.com/marketplace/product/nvidia/nvidia-rtx-virtual-workstation-windows-server-2022

<img width="1683" alt="Screenshot 2023-07-15 at 10 17 46" src="https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit/assets/24765473/ef141d24-ed25-4230-ac45-4a0370e21e65">

with the 2 policies off - left L4 GPU on GCP - right 4090 on prem as reference
<img width="1689" alt="Screenshot 2023-07-15 at 10 10 23" src="https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit/assets/24765473/0546dfdd-9447-45d0-8725-7273d031de5a">

Shadow
https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit/issues/426

**Comment by fmichaelobrien** [comment]
20240406: Closing issue during retrofit/rebase of this TEF V1 based/modified repo to TEF V4 standards
This issue may participate in the LZ refactor after rebase
Query on all issues related to the older V1 version via the tag
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/labels/2024-pre-tef-v4
