### ISSUE TITLE
Remove all TEF V1 modules not in use like VPN, GCE VM - in prep of replacement by TEF V4/TOC/CFF-FAST - see 243

### ISSUE THREAD

**Issue by obriensystems** [GoogleCloudPlatform/pbmm-on-gcp-onboarding#256]
In prep of the TEF V3 (now V4) retrofit remove all modules not in current use to avoid the overhead of maintaining legacy V1 TEF code 
#243 

like
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/blob/main/modules/virtual-machine/terraform.tf

see https://github.com/terraform-google-modules/terraform-example-foundation/issues/940

**Comment by fmichaelobrien** [comment]
20240406: Closing issue during retrofit/rebase of this TEF V1 based/modified repo to TEF V4 standards
This issue may participate in the LZ refactor after rebase
Query on all issues related to the older V1 version via the tag
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/labels/2024-pre-tef-v4
