### ISSUE TITLE
Bug: Align derived UC/lc names/ids for projects and resources as all lower case not camelcase - start both names and ids with lower case - customer/dev confusion

### ISSUE THREAD

**Issue by obriensystems** [GoogleCloudPlatform/pbmm-on-gcp-onboarding#257]
Running a couple installs with a client and they also run into the issue where they copy the distinct project name and run into the Capitalization/non-capitalization mismatch

<img width="1268" alt="Screenshot 2023-07-24 at 11 30 33" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/19a578de-5ff3-41b1-886a-99e1092bd03f">

first 4 letters are camelcase
name: TzPe-tlz-tlz-np2 
first 4 letters are lower case
id:  tzpe-tlz-tlz-np2

why capitalize the first letter of a project - make all projects lower case
assigning to self

example
```
root_@cloudshell:~/lz-tls/_interconnect/pbmm-on-gcp-onboarding/2023_technical_onboarding_center/20-partner-interconnect (lz-tls)$ gcloud config set project  TzPe-tlz-tlz-np2
WARNING: You do not appear to have access to project [TzPe-tlz-tlz-np2] or it does not exist.
Are you sure you wish to set property [core/project] to TzPe-tlz-tlz-np2?

Do you want to continue (Y/n)?  ^C

Command killed by keyboard interrupt


root_@cloudshell:~/lz-tls/_interconnect/pbmm-on-gcp-onboarding/2023_technical_onboarding_center/20-partner-interconnect (lz-tls)$ gcloud config set project tzPe-tlz-tlz-np2
WARNING: You do not appear to have access to project [tzPe-tlz-tlz-np2] or it does not exist.
Are you sure you wish to set property [core/project] to tzPe-tlz-tlz-np2?

Do you want to continue (Y/n)?  n

root_@cloudshell:~/lz-tls/_interconnect/pbmm-on-gcp-onboarding/2023_technical_onboarding_center/20-partner-interconnect (lz-tls)$ gcloud config set project tzpe-tlz-tlz-np2
Updated property [core/project].
root_@cloudshell:~/lz-tls/_interconnect/pbmm-on-gcp-onboarding/2023_technical_onboarding_center/20-partner-interconnect (tzpe-tlz-tlz-np2)$ 
```

**Comment by fmichaelobrien** [comment]
20240406: Closing issue during retrofit/rebase of this TEF V1 based/modified repo to TEF V4 standards
This issue may participate in the LZ refactor after rebase
Query on all issues related to the older V1 version via the tag
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/labels/2024-pre-tef-v4
