### ISSUE TITLE
Reenable IAM organization policy - Resource Location Restriction 

### ISSUE THREAD

**Issue by fmichaelobrien** [GoogleCloudPlatform/pbmm-on-gcp-onboarding#26]
Currently our guardrails part of the landingzone has regional location unrestricted - after an adjustment in our cloud build TF regional config we can turn back on the iam organization policy for security control compliance.

Fix (thanks Mike Craigen) in https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/blob/main/environments/common/common.auto.tfvars#L9

Google Cloud Platform - Resource Location Restriction
example https://github.com/canada-ca/accelerators_accelerateurs-gcp/blob/main/deployment-templates/Terraform/guardrails/1-guardrails/org-policy.tf#L10

<img width="784" alt="Screen Shot 2022-03-23 at 10 21 32 AM" src="https://user-images.githubusercontent.com/94715080/159721295-aa70994a-7b29-4a78-875c-4102e987362b.png">
<img width="1564" alt="Screen Shot 2022-03-23 at 10 22 08 AM" src="https://user-images.githubusercontent.com/94715080/159721420-657a5c1e-ee6d-40e2-8c82-cd5bc015edb2.png">

Location
us (multiple regions in United States)
Storage class
Standard
Public access
Subject to object ACLs
Protection
None

<img width="744" alt="Screen Shot 2022-03-24 at 11 18 22 AM" src="https://user-images.githubusercontent.com/94715080/159949614-7195bae8-1fe6-4b75-be84-58db57c6874f.png">

**Comment by fmichaelobrien** [comment]
I need to retest on the no-more default network creation fix - if this allows regional-only CB
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/blob/main/environments/common/common.auto.tfvars#L9

**Comment by fmichaelobrien** [comment]
See also Chris's research - TF base issue https://github.com/hashicorp/terraform-provider-google/issues/11624

**Comment by obriensystems** [comment]
Fix is to specify the bucket used during the build - and not defer to the default (us)
https://github.com/GoogleCloudPlatform/esp-v2/issues/148

**Comment by fmichaelobrien** [comment]
I am prototyping this in my cloudnuage.org right now

**Comment by obriensystems** [comment]
<img width="941" alt="Screen Shot 2022-08-21 at 21 38 37" src="https://user-images.githubusercontent.com/24765473/185822443-0402de3e-9e59-4997-8107-60bf0c644124.png">

**Comment by fmichaelobrien** [comment]
upgrade to org policy V2 - thanks Mike
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/issues/174

**Comment by obriensystems** [comment]
20240406: Closing issue during retrofit/rebase of this TEF V1 based/modified repo to TEF V4 standards
This issue may participate in the LZ refactor after rebase
Query on all issues related to the older V1 version via the tag
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/labels/2024-pre-tef-v4
