### ISSUE TITLE
Validate post LZ-deploy VPC subnet CIDR change effect on deployed resources - verified OK - subnet destroy/recreate in place

### ISSUE THREAD

**Issue by obriensystems** [GoogleCloudPlatform/pbmm-on-gcp-onboarding#262]
# Scenario: LZ CIDR ranges must be modified post LZ install from the default of 10.20.0.0/16 for prod for example
- no default subnets exist - only custom subnets

Result: option 1: subnet delete/recreate in place does not affect VPC associated resources like a partner interconnect

## Option 1: recreate the entire VPC + subnet - kicking out resource like a running interconnect
see #249
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/blob/main/environments/prod/prod-network.auto.tfvars#L40
          subnet_ip             = "10.10.20.0/24"

## Option 2: add a 2nd subnet and deprecate existing default subnet
- beneficial for services tied only the VPC not a particular subnet

**Comment by obriensystems** [comment]
Testing option 1 with new VPC + subnet

```
{
  "autoCreateSubnetworks": false,
  "creationTimestamp": "2023-07-26T08:53:50.173-07:00",
  "description": "",
  "id": "2000509140114145121",
  "kind": "compute#network",
  "mtu": 1460,
  "name": "eventstream-dev-vpc",
  "networkFirewallPolicyEnforcementOrder": "AFTER_CLASSIC_FIREWALL",
  "routingConfig": {
    "routingMode": "REGIONAL"
  },
  "selfLink": "projects/eventstream-dev/global/networks/eventstream-dev-vpc",
  "selfLinkWithId": "https://www.googleapis.com/compute/beta/projects/eventstream-dev/global/networks/2000509140114145121",
  "subnetworks": [
    "projects/eventstream-dev/regions/northamerica-northeast1/subnetworks/subnet1"
  ]
}

```

**Comment by fmichaelobrien** [comment]
TF change - swap IP directly in the subnet (later add 2nd subnet and/or delete the first)
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/blob/main/environments/prod/prod-network.auto.tfvars#L40
```
diff --git a/environments/prod/prod-network.auto.tfvars b/environments/prod/prod-network.auto.tfvars
index 44be77a..a897e4f 100644
--- a/environments/prod/prod-network.auto.tfvars
+++ b/environments/prod/prod-network.auto.tfvars
@@ -37,7 +37,8 @@ prod_host_net = {
       subnets = [
         {
           subnet_name           = "prsubnet02"
-          subnet_ip             = "10.10.20.0/24"
+          #subnet_ip             = "10.10.20.0/24"
+          subnet_ip             = "10.30.30.0/24"
           subnet_region         = "northamerica-northeast1"
```

**Comment by fmichaelobrien** [comment]
20240406: Closing issue during retrofit/rebase of this TEF V1 based/modified repo to TEF V4 standards
This issue may participate in the LZ refactor after rebase
Query on all issues related to the older V1 version via the tag
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/labels/2024-pre-tef-v4
