### ISSUE TITLE
Provide module/resource for workload service project

### ISSUE THREAD

**Issue by obriensystems** [GoogleCloudPlatform/pbmm-on-gcp-onboarding#263]
Initially we will prototype a service project off the prod/non-prod host project.
Later we provide for a tiered client project creation template including service enablement and IAM permissions
- add 2 tier IAM admin permissions
- verify firewall egress rules (icmp for ping)
- verify egress 0.0.0.0/0 route
- verify ssh access via IAM browser proxy with key transfer but also ssh client access from on-prem to the cloud

see
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/tree/main/modules/project

see IAM permissions for project
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/google_project_iam.html

**Comment by obriensystems** [comment]
Mods
        modified:   environments/common/outputs.tf
        modified:   environments/prod/main.tf
        new file:   environments/prod/prod-workload-network.auto.tfvars

main.tf
```
module "prod-client-prj" {
  source                         = "../../modules/project"
  department_code                = local.organization_config.department_code
  user_defined_string            = var.prod_workload_net.user_defined_string
  additional_user_defined_string = var.prod_workload_net.additional_user_defined_string
  labels                         = var.prod_workload_net.labels
  owner                          = local.organization_config.owner
  environment                    = local.organization_config.environment
  location                       = local.organization_config.location
  billing_account                = local.organization_config.billing_account
  parent                         = data.terraform_remote_state.common.outputs.folders_map_1_level.Prod.id
  services                       = var.prod_workload_net.services
  tf_service_account_email       = data.terraform_remote_state.bootstrap.outputs.service_account_email
  # mutually exclusive
  shared_vpc_host_config         = false
  shared_vpc_service_config      = true
}
```
common/outputs.tf

```
output "folders_map_1_level" {
  value = module.core-folders.folders_map_1_level
}
```

new
prod-workload-network.auto.tfvars
```
prod_workload_net = {

```

**Comment by obriensystems** [comment]
IAM project permissions work on the service project

see https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit/blob/canary/solutions/document-processing/gcloud/deployment.sh#L89

```
gcloud projects add-iam-policy-binding $PROJECT_ID  --member=user:$SA_EMAIL --role=roles/owner --quiet > /dev/null 1>&1

testing gcloud before terraform
root_@cloudshell:~/lz-tls/_lz2/pbmm-on-gcp-onboarding (lz-tls)$ gcloud projects add-iam-policy-binding interconnect-tls  --member=user:developer@terraform.landing.systems --role=roles/owner
```
<img width="1765" alt="Screenshot 2023-07-31 at 14 00 36" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/dded346e-9c93-4f9b-84d4-021e62dea747">

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/google_project_iam.html#google_project_iam_binding

**Comment by fmichaelobrien** [comment]
20240406: Closing issue during retrofit/rebase of this TEF V1 based/modified repo to TEF V4 standards
This issue may participate in the LZ refactor after rebase
Query on all issues related to the older V1 version via the tag
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/labels/2024-pre-tef-v4
