### ISSUE TITLE
Upgrade terraform build image from 1.0.10 to 1.5.x

### ISSUE THREAD

**Issue by obriensystems** [GoogleCloudPlatform/pbmm-on-gcp-onboarding#264]
```
Step #1 - "tf version": *************** TERRAFORM VERSION ******************
Step #1 - "tf version": ******* At environment: environments/prod *************
Step #1 - "tf version": *************************************************
Step #1 - "tf version": Terraform v1.0.10
Step #1 - "tf version": on linux_amd64
Step #1 - "tf version": + provider registry.terraform.io/hashicorp/google v3.90.1
Step #1 - "tf version": + provider registry.terraform.io/hashicorp/google-beta v4.75.0
Step #1 - "tf version": + provider registry.terraform.io/hashicorp/null v3.2.1
Step #1 - "tf version": + provider registry.terraform.io/hashicorp/random v3.5.1
Step #1 - "tf version": 
Step #1 - "tf version": Your version of Terraform is out of date! The latest version
Step #1 - "tf version": is 1.5.4. You can update by downloading from https://www.terraform.io/downloads.html
```

**Comment by fmichaelobrien** [comment]
20231015
for https://github.com/hashicorp/terraform-provider-google/issues/16217
We will need to look at upgrading from 1.0 to 1.5.7 or the new 1.6.0 https://releases.hashicorp.com/terraform/1.6.0/ as a first step in the https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding codebase

**Comment by fmichaelobrien** [comment]
go past 1.5.8 if not using 1.6.x

**Comment by fmichaelobrien** [comment]
20240406: Closing issue during retrofit/rebase of this TEF V1 based/modified repo to TEF V4 standards
This issue may participate in the LZ refactor after rebase
Query on all issues related to the older V1 version via the tag
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/labels/2024-pre-tef-v4
