### ISSUE TITLE
Example landing zone deployment doc - nonprod and nonprod/prod for Cloud Identity based new GCP account

### ISSUE THREAD

**Issue by fmichaelobrien** [GoogleCloudPlatform/pbmm-on-gcp-onboarding#27]
# 20220323 update docs based on procedure below

# Deployments
gcp.obrien.services = peering reconfig
containerized.org = fortigate config - #45 

# branches
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/tree/fmichaelobrien-example-nonprod

# onboarding
- create a cloud account via onboarding procedure
- https://cloud.google.com/billing/docs/onboarding-checklist
- https://cloud.google.com/docs/enterprise/setup-checklist
- in this case non-workspace Cloud Identity is used 
- https://accounts.google.com/SignUpWithoutGmail
Fill in the form with an existing email address outside of Google
 
Launch from step 2 of the IAM | Cloud Identity & Organization | checklist https://console.cloud.google.com/cloud-setup/organization

to https://workspace.google.com/signup/gcpidentity/welcome

Finish and Login to new Google account

https://myaccount.google.com/?utm_source=sign_in_no_continue&pli=1&nlr=1

Navigate to GCP

https://console.cloud.google.com/

If not on a federated account - activate the trial to setup billing or setup billing later

Navigate to IAM| Identity and Organization

https://console.cloud.google.com/iam-admin/cloudidentity/consumer?orgonly=true&supportedpurview=project,organizationId,folder

select the checklist

https://console.cloud.google.com/cloud-setup/overview?orgonly=true&supportedpurview=project,organizationId,folder

If you see a warning - you do not have a cloud identity account yet

Begin Setup button - I am a new customer

(you will end up with 2 users - one already hosted on your domain, the other on the google identity subdomain)

Phone numbers can be used a max 3-5 times for verification
The process is

use an email that is on your target domain (the root domain not the subdomain) - use AWS Workmail for example

Use that user to create the google account above

Login to cloud.google.com with this user and navigate to organization onboarding

hit the checklist - but goto create identity account

create a new user with the subdomain - this will be your super admin account

goto billing and activate your account - to keep credits

wait 24h for the additional 100 org credit

https://console.cloud.google.com/cloud-setup/organization?orgonly=true&supportedpurview=project,organizationId,folder

Make sure to configure a subdomain - example gcp.obrien.systems

example AWS TXT record

https://console.aws.amazon.com/route53/v2/hostedzones#ListRecordSets/Z05779022O0W927A7QCEB

# launch shell

https://shell.cloud.google.com/

Authenticate and view components

admin_super@cloudshell:~$ gcloud auth list
Credentialed Accounts
ACTIVE: *
ACCOUNT: admin-...brien.services

To set the active account, run:
    $ gcloud config set account `ACCOUNT`
    

gcloud components list | grep Name

# for now set owner on the super admin account

<img width="1281" alt="Screen Shot 2022-03-23 at 9 22 22 PM" src="https://user-images.githubusercontent.com/94715080/159823235-49bee088-2ae1-4023-b883-88c68c1fb3cc.png">

# create a folder under the org - don't name it "landingzone" for now

<img width="307" alt="Screen Shot 2022-03-23 at 2 43 13 PM" src="https://user-images.githubusercontent.com/94715080/159772978-76d23bef-11eb-4372-891b-15870aafd61b.png">

# create a staging project under that folder to clone the repo into
<img width="319" alt="Screen Shot 2022-03-23 at 2 48 14 PM" src="https://user-images.githubusercontent.com/94715080/159773856-bcb6a7fa-f7ae-4437-81ef-8a9bf3637e6f.png">

# clone project via "Open in Google Cloud Shell" 
in https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/blob/main/README.md

[![Open this project in Google Cloud Shell](http://gstatic.com/cloudssh/images/open-btn.png)](https://console.cloud.google.com/cloudshell/open?git_repo=https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding&page=editor&tutorial=README.md)

<img width="448" alt="Screen Shot 2022-03-23 at 2 45 02 PM" src="https://user-images.githubusercontent.com/94715080/159773308-59734464-f26e-4e12-86f8-31d643da617d.png">

Open up the folder under cloudshell_open
<img width="1522" alt="Screen Shot 2022-03-23 at 2 46 30 PM" src="https://user-images.githubusercontent.com/94715080/159773553-6dcab6b2-f2a2-49d9-8842-a1ea2c3bff03.png">

# switch projects
```
admin_super@cloudshell:~/cloudshell_open/pbmm-on-gcp-onboarding$ gcloud projects list
PROJECT_ID: landingzone-stg-os
NAME: landingzone-stg-os
admin_super@cloudshell:~/cloudshell_open/pbmm-on-gcp-onboarding$ gcloud config set project landingzone-stg-os
Updated property [core/project].
admin_super@cloudshell:~/cloudshell_open/pbmm-on-gcp-onboarding (landingzone-stg-os)$
```
# switch branches to one of the example branches
```
admin_super@cloudshell:~/cloudshell_open/pbmm-on-gcp-onboarding (landingzone-stg-os)$ git checkout fmichaelobrien-example-nonprod
Branch 'fmichaelobrien-example-nonprod' set up to track remote branch 'fmichaelobrien-example-nonprod' from 'origin'.
Switched to a new branch 'fmichaelobrien-example-nonprod'
```

# modify variables (org, billing, names)
- example here is a recent change to the configs - replace all <DOMAIN, ORGID, BILLINGID, FOLDERID>
```
admin_super@cloudshell:~/cloudshell_open/pbmm-on-gcp-onboarding (landingzone-stg-os)$ git pull
From https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding
   88ad5fa..1f2f2eb  fmichaelobrien-example-nonprod -> origin/fmichaelobrien-example-nonprod
 environments/bootstrap/bootstrap.auto.tfvars           | 30 +++++++++++++++++-------------
 environments/bootstrap/bootstrap.sh                    |  0
 environments/bootstrap/organization-config.auto.tfvars | 20 ++++++++++----------
 environments/common/common.auto.tfvars                 | 36 ++++++++++++++++++------------------
 environments/nonprod/nonp-firewall.auto.tfvars         | 24 ++++++++++++------------
 environments/nonprod/nonp-network.auto.tfvars          | 53 +++++++++++++++++++++++++++++++++--------------------
 environments/nonprod/nonp-vpc-svc-ctl.auto.tfvars      | 36 ++++++++++++++++++------------------
 modules/cloudbuild/cloudbuild_builder/Dockerfile       |  2 ++
 8 files changed, 110 insertions(+), 91 deletions(-)
```

# run environments/bootstrap/bootstrap.sh run
<img width="1259" alt="Screen Shot 2022-03-23 at 8 55 14 PM" src="https://user-images.githubusercontent.com/94715080/159820757-9a2f961f-6aef-45dd-a5ea-622203352e95.png">

# CSR email and name
<img width="920" alt="Screen Shot 2022-03-23 at 9 04 17 PM" src="https://user-images.githubusercontent.com/94715080/159821542-96f34244-1d21-4b1a-b5e3-0c297115d48a.png">

```
To https://source.developers.google.com/p/ospe-obs-osdev-sbx/r/observiceslzd
 * [new branch]      main -> main
INFO - Code pushed to CSR
```
5 min duration

# check bootstrap project
<img width="1119" alt="Screen Shot 2022-03-23 at 9 07 06 PM" src="https://user-images.githubusercontent.com/94715080/159821773-fa6d02c0-9067-4db3-98ef-feeef46fda22.png">

# check CSR - cloud source repo
<img width="1899" alt="Screen Shot 2022-03-23 at 9 09 29 PM" src="https://user-images.githubusercontent.com/94715080/159822012-c6f32f3b-5e53-4f67-bd35-6fdcc60b5b4b.png">

# check cloud build jobs - it is normal that all fail except the docker build job - dependencies were not met - all jobs ran at the same time

<img width="1391" alt="Screen Shot 2022-03-23 at 9 10 31 PM" src="https://user-images.githubusercontent.com/94715080/159822103-03f907e6-50b0-4265-bdf7-39ee0b82e6b6.png">

# rerun the bootstrap/common jobs by committing code

```
admin_super@cloudshell:~/cloudshell_open/pbmm-on-gcp-onboarding/environments/bootstrap (landingzone-stg-os)$ git status
On branch main
nothing to commit, working tree clean
admin_super@cloudshell:~/cloudshell_open/pbmm-on-gcp-onboarding/environments/bootstrap (landingzone-stg-os)$ vi bootstrap.auto.tfvars
admin_super@cloudshell:~/cloudshell_open/pbmm-on-gcp-onboarding/environments/bootstrap (landingzone-stg-os)$ git status
On branch main
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   bootstrap.auto.tfvars
no changes added to commit (use "git add" and/or "git commit -a")
admin_super@cloudshell:~/cloudshell_open/pbmm-on-gcp-onboarding/environments/bootstrap (landingzone-stg-os)$ git add .
admin_super@cloudshell:~/cloudshell_open/pbmm-on-gcp-onboarding/environments/bootstrap (landingzone-stg-os)$ git commit -m "#1 - edit solely to kick in bootstrap cb trigger"
[main 3f5b0cb] #1 - edit solely to kick in bootstrap cb trigger
 1 file changed, 1 insertion(+), 1 deletion(-)
admin_super@cloudshell:~/cloudshell_open/pbmm-on-gcp-onboarding/environments/bootstrap (landingzone-stg-os)$ git push csr main
```

<img width="1092" alt="Screen Shot 2022-03-23 at 9 13 23 PM" src="https://user-images.githubusercontent.com/94715080/159822334-9aca61a3-4132-4f15-a2fe-8ba58ff0909c.png">

# do the same edit to kick in the common cloud build trigger

```
admin_super@cloudshell:~/cloudshell_open/pbmm-on-gcp-onboarding/environments/common (landingzone-stg-os)$ vi common.auto.tfvars
admin_super@cloudshell:~/cloudshell_open/pbmm-on-gcp-onboarding/environments/common (landingzone-stg-os)$ git add .
admin_super@cloudshell:~/cloudshell_open/pbmm-on-gcp-onboarding/environments/common (landingzone-stg-os)$ git commit -m "#1 - edit solely to kick in common cb trigger"
[main f3096ff] #1 - edit solely to kick in common cb trigger
 1 file changed, 2 insertions(+), 2 deletions(-)
admin_super@cloudshell:~/cloudshell_open/pbmm-on-gcp-onboarding/environments/common (landingzone-stg-os)$ git push csr main
```
<img width="1067" alt="Screen Shot 2022-03-23 at 9 20 04 PM" src="https://user-images.githubusercontent.com/94715080/159822972-e29d2de4-b125-4c58-8148-872102f60e21.png">

# see code changes

<img width="1268" alt="Screen Shot 2022-03-23 at 9 20 36 PM" src="https://user-images.githubusercontent.com/94715080/159823036-892bebc2-ce65-4255-8b12-5757c3534a25.png">

# The pull jobs perform terraform plan - but the push jobs do the actual terraform apply
<img width="1917" alt="Screen Shot 2022-03-23 at 9 22 45 PM" src="https://user-images.githubusercontent.com/94715080/159823277-9f482ca9-3deb-4276-8edd-fc280491175e.png">

# ask for more project billing association quota - currently 5 - it is lower for non-workspaces projects 

https://console.cloud.google.com/cloud-build/builds;region=global/57dde321-0817-4cdc-8e17-9aee65008f3e?project=ospe-obs-osdev-sbx
```
Step #3 - "tf apply": │ Error: Error setting billing account "019AA9-7A033F-CE7DF4" for project "projects/ospe-obs-audit": googleapi: Error 400: Precondition check failed.
Step #3 - "tf apply": │ Details:
Step #3 - "tf apply": │ [
Step #3 - "tf apply": │   {
Step #3 - "tf apply": │     "@type": "type.googleapis.com/google.rpc.QuotaFailure",
Step #3 - "tf apply": │     "violations": [
Step #3 - "tf apply": │       {
Step #3 - "tf apply": │         "description": "Cloud billing quota exceeded: https://support.google.com/code/contact/billing_quota_increase",
Step #3 - "tf apply": │         "subject": "billingAccounts/01....DF4"
Step #3 - "tf apply": │       }
```

# delete billing from 2 of 5 projects - try for 2 more - do prod later while we wait for quota to come in 2-3 days

Check I don't already have a project with this name in another account.
Step #3 - "tf apply": │ Error: error creating project ospe-obs-audit (OsPe-obs-audit): googleapi: Error 409: Requested entity already exists, alreadyExists. If you received a 403 error, make sure you have the `roles/resourcemanager.projectCreator` permission

   user_defined_string            = "audit" REQUIRED EDIT. Must be globally unique, used for the audit project
-  additional_user_defined_string = ""      OPTIONAL EDIT. Optionally append a value to the end of the user defined string.
+  additional_user_defined_string = "obs"      OPTIONAL EDIT. Optionally append a value to the end of the user defined string.

<img width="1093" alt="Screen Shot 2022-03-23 at 10 14 55 PM" src="https://user-images.githubusercontent.com/94715080/159828515-75f05d14-49cd-4078-b72d-4be12431154a.png">

# workaround working - 4 projects with billing from 3

<img width="463" alt="Screen Shot 2022-03-23 at 10 22 41 PM" src="https://user-images.githubusercontent.com/94715080/159829291-20225e29-6ca8-4b38-8905-dfaa5f9ae74d.png">

 
<img width="1912" alt="Screen Shot 2022-03-23 at 10 23 07 PM" src="https://user-images.githubusercontent.com/94715080/159829341-4435497f-4f1e-43bd-ae9b-b5b28ca27709.png">

<img width="463" alt="Screen Shot 2022-03-23 at 10 24 14 PM" src="https://user-images.githubusercontent.com/94715080/159829464-16e084dd-d836-4108-9991-8095a79c9ef0.png">

<img width="1349" alt="Screen Shot 2022-03-23 at 10 25 03 PM" src="https://user-images.githubusercontent.com/94715080/159829535-b18448cf-582b-417e-91a3-85ce57b18c20.png">
 
# run nonprod - push to csr
<img width="1110" alt="Screen Shot 2022-03-23 at 10 28 52 PM" src="https://user-images.githubusercontent.com/94715080/159829980-cc580d93-be6b-49a3-acac-75aaa0b1af82.png">

working - 1 extra project
<img width="431" alt="Screen Shot 2022-03-23 at 10 42 13 PM" src="https://user-images.githubusercontent.com/94715080/159831418-222acec6-1a7a-49ba-8bb5-c37102a7b58e.png">

<img width="406" alt="Screen Shot 2022-03-23 at 10 43 08 PM" src="https://user-images.githubusercontent.com/94715080/159831509-d4ab18b7-9efb-4286-9d83-9c2575e081f3.png">

# prod next - and peered VPCs

**Comment by fmichaelobrien** [comment]
# prod deployment
- target branch for 1400 meet 
- use Saadia's example branch https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/tree/example
- merge in changes from non-prod https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/tree/fmichaelobrien-example-nonprod
- verify PR state
- later add roles/permissions changes from https://github.com/canada-ca/accelerators_accelerateurs-gcp/pull/26

**Comment by fmichaelobrien** [comment]
diff
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/commit/c506f2d782cf683e272e39b03be56c703fba1bd9

```
	modified:   environments/bootstrap/bootstrap.auto.tfvars
	modified:   environments/bootstrap/organization-config.auto.tfvars
	modified:   environments/common/common.auto.tfvars
	modified:   environments/nonprod/locals.tf
	modified:   environments/nonprod/nonp-firewall.auto.tfvars
	modified:   environments/nonprod/nonp-network.auto.tfvars
	modified:   environments/nonprod/nonp-vpc-svc-ctl.auto.tfvars
	modified:   environments/prod/locals.tf
	modified:   environments/prod/perimeter-network.auto.tfvars
	modified:   environments/prod/prod-firewall.auto.tfvars
	modified:   environments/prod/prod-network.auto.tfvars
	modified:   environments/prod/prod-private-perimeter-firewall.auto.tfvars
	modified:   environments/prod/prod-public-perimeter-firewall.auto.tfvars
	modified:   environments/prod/prod-vpc-svc-ctl.auto.tfvars
	modified:   environments/prod/variables.tf
	modified:   modules/cloudbuild/cloudbuild_builder/Dockerfile
```

**Comment by fmichaelobrien** [comment]
# nonprod/prod redeploy with git merge of structural config changes in the remote main branch
20220405
testing PR
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/pull/43
in branch
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/tree/fmichaelobrien
before merging

```
in containerized.org (only nonprod deployed so far) as dev - note: obrien.services contains stable prod 

michael@cloudshell:~/cloudshell_open/pbmm-on-gcp-onboarding (landingzone-stg)$ cd ..
michael@cloudshell:~/cloudshell_open (landingzone-stg)$ mkdir merge
michael@cloudshell:~/cloudshell_open (landingzone-stg)$ cd merge/
michael@cloudshell:~/cloudshell_open/merge (landingzone-stg)$ git clone https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding.git
Cloning into 'pbmm-on-gcp-onboarding'...
remote: Enumerating objects: 973, done.
remote: Counting objects: 100% (973/973), done.
remote: Compressing objects: 100% (558/558), done.
remote: Total 973 (delta 476), reused 852 (delta 381), pack-reused 0
Receiving objects: 100% (973/973), 638.43 KiB | 9.39 MiB/s, done.
Resolving deltas: 100% (476/476), done.

michael@cloudshell:~/cloudshell_open/merge (landingzone-stg)$ cd pbmm-on-gcp-onboarding/
michael@cloudshell:~/cloudshell_open/merge/pbmm-on-gcp-onboarding (landingzone-stg)$ git checkout fmichaelobrien
Branch 'fmichaelobrien' set up to track remote branch 'fmichaelobrien' from 'origin'.
Switched to a new branch 'fmichaelobrien'
michael@cloudshell:~/cloudshell_open/merge/pbmm-on-gcp-onboarding (landingzone-stg)$ git status
On branch fmichaelobrien



michael@cloudshell:~/cloudshell_open/merge/pbmm-on-gcp-onboarding (landingzone-stg)$ cp -r environments/ ../../pbmm-on-gcp-onboarding/
michael@cloudshell:~/cloudshell_open/merge/pbmm-on-gcp-onboarding (landingzone-stg)$ cp -r modules/ ../../pbmm-on-gcp-onboarding/
michael@cloudshell:~/cloudshell_open/merge/pbmm-on-gcp-onboarding (landingzone-stg)$ cp -r README.md ../../pbmm-on-gcp-onboarding/
michael@cloudshell:~/cloudshell_open/merge/pbmm-on-gcp-onboarding (landingzone-stg)$ cp -r  ../../pbmm-on-gcp-onboarding/
michael@cloudshell:~/cloudshell_open/merge/pbmm-on-gcp-onboarding (landingzone-stg)$ cp -r writeids.sh ../../pbmm-on-gcp-onboarding/


michael@cloudshell:~/cloudshell_open/pbmm-on-gcp-onboarding (landingzone-stg)$ git status
On branch main
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   README.md
        modified:   environments/bootstrap/bootstrap.auto.tfvars
        modified:   environments/bootstrap/organization-config.auto.tfvars
        modified:   environments/common/common.auto.tfvars
        modified:   environments/nonprod/locals.tf
        modified:   environments/nonprod/nonp-firewall.auto.tfvars
        modified:   environments/nonprod/nonp-network.auto.tfvars
        modified:   environments/nonprod/nonp-vpc-svc-ctl.auto.tfvars
        modified:   environments/nonprod/provider.tf
        modified:   environments/prod/locals.tf
        modified:   environments/prod/perimeter-network.auto.tfvars
        modified:   environments/prod/prod-network.auto.tfvars
        modified:   environments/prod/prod-vpc-svc-ctl.auto.tfvars
        modified:   modules/cloudbuild/cloudbuild_builder/Dockerfile
        modified:   modules/virtual-machine/README.md

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        writeids.sh



michael@cloudshell:~/cloudshell_open/pbmm-on-gcp-onboarding (landingzone-stg)$ git checkout environments/nonprod/provider.tf
Updated 1 path from the index
michael@cloudshell:~/cloudshell_open/pbmm-on-gcp-onboarding (landingzone-stg)$ git add README.md
michael@cloudshell:~/cloudshell_open/pbmm-on-gcp-onboarding (landingzone-stg)$ git add modules/virtual-machine/README.md
michael@cloudshell:~/cloudshell_open/pbmm-on-gcp-onboarding (landingzone-stg)$ git add modules/cloudbuild/cloudbuild_builder/Dockerfile

```

**Comment by fmichaelobrien** [comment]
# 20220517: run main - add automation for attributes
# run 2 deployments to the same org

```















Welcome to Cloud Shell! Type "help" to get started.
To set your Cloud Platform project in this session use “gcloud config set project [PROJECT_ID]”
michael@cloudshell:~$ gcloud config set project landingzone-co2
Updated property [core/project].
michael@cloudshell:~ (landingzone-co2)$ ls
accelerators_accelerateurs-gcp  cloudshell_open  hal                pbmm-on-gcp-onboarding-main.zip  sample-app      spin
cloud-guardrails-gcp            github           InstallHalyard.sh  README-cloudshell.txt            sample-app.tar
michael@cloudshell:~ (landingzone-co2)$ mkdir landingzone-co2
michael@cloudshell:~ (landingzone-co2)$ cd landingzone-co2/
michael@cloudshell:~/landingzone-co2 (landingzone-co2)$ git clone https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding.git
Cloning into 'pbmm-on-gcp-onboarding'...
remote: Enumerating objects: 1141, done.
remote: Counting objects: 100% (191/191), done.
remote: Compressing objects: 100% (106/106), done.
remote: Total 1141 (delta 119), reused 111 (delta 84), pack-reused 950
Receiving objects: 100% (1141/1141), 688.54 KiB | 11.67 MiB/s, done.
Resolving deltas: 100% (583/583), done.
michael@cloudshell:~/landingzone-co2 (landingzone-co2)$ ls
pbmm-on-gcp-onboarding
michael@cloudshell:~/landingzone-co2 (landingzone-co2)$ cd pbmm-on-gcp-onboarding/
michael@cloudshell:~/landingzone-co2/pbmm-on-gcp-onboarding (landingzone-co2)$ DOMAIN=containerized.org
michael@cloudshell:~/landingzone-co2/pbmm-on-gcp-onboarding (landingzone-co2)$ EMAIL=michael@containerized.org
michael@cloudshell:~/landingzone-co2/pbmm-on-gcp-onboarding (landingzone-co2)$ ORG_ID=$(gcloud organizations list --filter="DISPLAY_NAME:$DOMAIN" --format="value(ID)")
michael@cloudshell:~/landingzone-co2/pbmm-on-gcp-onboarding (landingzone-co2)$ git status
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean


michael@cloudshell:~/landingzone-co2/pbmm-on-gcp-onboarding (landingzone-co2)$ ./writeids.sh -c fill -f 156023225078
Derived organization_id: 843157297140
Derived billing_id: 01AD73-CD99D2-D2393B
replacing IDs: billing: 01AD73-CD99D2-D2393B organization: 843157297140 folder: 156023225078 from placeholders
environments/bootstrap/bootstrap.auto.tfvars pass - fill:true
environments/bootstrap/organization-config.auto.tfvars pass - fill:true
environments/common/common.auto.tfvars pass - fill:true
environments/nonprod/nonp-network.auto.tfvars pass - fill:true
environments/common/perimeter-network.auto.tfvars pass - fill:true
environments/prod/prod-network.auto.tfvars pass - fill:true
```




set emails, attributes (add to setids sh automation...)

common
set 
 org_id_scan_list = [     # REQUIRED EDIT. Organization Id list for service account to have cloud asset viewer permission
  ]

run bootstrap and common

```
cloud_source_repo_name
        modified:   environments/bootstrap/bootstrap.auto.tfvars
        modified:   environments/bootstrap/organization-config.auto.tfvars
        modified:   environments/common/common.auto.tfvars
        modified:   environments/common/perimeter-network.auto.tfvars
        modified:   environments/nonprod/nonp-network.auto.tfvars
        modified:   environments/prod/prod-network.auto.tfvars


fix grammar
0932
michael@cloudshell:~/landingzone-co2/pbmm-on-gcp-onboarding/environments/bootstrap (landingzone-co2)$ ./bootstrap.sh run
User: michael@containerized.org
Domain: containerized.org
Is this is user and domain of the organization you want to deploy to? (y/n)

module.landing_zone_bootstrap.module.project.google_project.project: Still creating... [1m0s elapsed]
..
module.landing_zone_bootstrap.module.project.google_project.project: Still creating... [2m40s elapsed]

module.landing_zone_bootstrap.module.project.google_project.project: Creation complete after 3m33s [id=projects/orpe-or-co2-sbx]


may be because of 1 line edit while running
To https://source.developers.google.com/p/orpe-or-co2-sbx/r/co2serviceslzd
 * [new branch]      main -> main
INFO - Code pushed to CSR
./bootstrap.sh: line 452: syntax error near unexpected token `fi'
0940

```
<img width="837" alt="Screen Shot 2022-05-19 at 9 41 41 AM" src="https://user-images.githubusercontent.com/94715080/169307505-9ccbab8e-41d3-43f3-880b-6dd5807928df.png">

**Comment by fmichaelobrien** [comment]
# fixes
```
diff --git a/environments/prod/prod-vpc-svc-ctl.auto.tfvars b/environments/prod/prod-vpc-svc-ctl.auto.tfvars
index 8ba1d15..71ba4bf 100644
--- a/environments/prod/prod-vpc-svc-ctl.auto.tfvars
+++ b/environments/prod/prod-vpc-svc-ctl.auto.tfvars
@@ -10,7 +10,7 @@ prod_vpc_svc_ctl = {
       perimeter_name               = "regular_service_perimeter_prod_1"
       description                  = "Regular Service Perimeter Prod 1"
       restricted_services          = []
-      resources                    = ["project-name"] #"project-name"
+      resources                    = []#"project-name"] #"project-name"
       resources_by_numbers         = []
       access_level                 = [] #"access_level_prod_1"
       restricted_services_dry_run  = []
```

**Comment by obriensystems** [comment]
20240406: Closing issue during retrofit/rebase of this TEF V1 based/modified repo to TEF V4 standards
This issue may participate in the LZ refactor after rebase
Query on all issues related to the older V1 version via the tag
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/labels/2024-pre-tef-v4
