### ISSUE TITLE
Add example profile 3 canary workload services projects around bigquery development

### ISSUE THREAD

**Issue by obriensystems** [GoogleCloudPlatform/pbmm-on-gcp-onboarding#279]
Update: investigate owner role on project or superfolder and folderIAMAdmin
Update: lay out prod/non-prod folder structure
```

```

follow document ai canary at https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit/blob/canary/solutions/document-processing/gcloud/deployment.sh#L88

https://cloud.google.com/bigquery/docs/access-control#bq-permissions
https://cloud.google.com/bigquery/docs/access-control#bigquery

training
https://www.cloudskillsboost.google/focuses/1145?parent=catalog
<img width="1777" alt="Screenshot 2023-08-03 at 13 02 04" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/350e24df-1866-4307-ac72-216adcf9c285">

## Roles
```
gcloud projects add-iam-policy-binding $CC_PROJECT_ID  --member=sgroup:$EMAIL --role=roles/bigquery.admin --quiet > /dev/null 1>&1
```
## Services
Big Query is usually enabled by default on a project - but the lz workflow has it unset - fixing

```
root_@cloudshell:~/lz-tls/_lz2/pbmm-on-gcp-onboarding (lz-tls)$ gcloud config set project tzpe-tlz-tlz-de
Updated property [core/project].
root_@cloudshell:~/lz-tls/_lz2/pbmm-on-gcp-onboarding (tzpe-tlz-tlz-de)$ gcloud services list | grep NAME
NAME: accesscontextmanager.googleapis.com
NAME: appengine.googleapis.com
NAME: artifactregistry.googleapis.com
NAME: cloudbilling.googleapis.com
NAME: cloudbuild.googleapis.com
NAME: cloudidentity.googleapis.com
NAME: cloudkms.googleapis.com
NAME: cloudresourcemanager.googleapis.com
NAME: compute.googleapis.com
NAME: containerregistry.googleapis.com
NAME: iam.googleapis.com
NAME: iamcredentials.googleapis.com
NAME: logging.googleapis.com
NAME: oslogin.googleapis.com
NAME: pubsub.googleapis.com
NAME: secretmanager.googleapis.com
NAME: serviceusage.googleapis.com
NAME: sourcerepo.googleapis.com
NAME: storage-api.googleapis.com
```

add

```
bigquery.googleapis.com
bigquerymigration.googleapis.com
bigquerystorage.googleapis.com

gcloud services enable bigquerymigration.googleapis.com
gcloud services enable bigquery.googleapis.com
gcloud services enable bigquerystorage.googleapis.com
```

**Comment by obriensystems** [comment]
before - no access as expected 
<img width="866" alt="Screenshot 2023-08-03 at 12 11 27" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/ef460c82-38f6-473d-b1a7-28bdc3b37459">

after

**Comment by obriensystems** [comment]
check limited access
<img width="1784" alt="Screenshot 2023-08-03 at 12 38 45" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/b77c9482-7023-4084-8ad2-10bce212a10c">
<img width="1784" alt="Screenshot 2023-08-03 at 12 39 33" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/98782280-c954-4d7a-80fa-92ab43f0ba08">

getting iam admin via group role
<img width="1061" alt="Screenshot 2023-08-03 at 12 40 36" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/80889544-ac6c-4598-9c97-7d19f23c5d10">

although only the terraform service account can modify group membership
<img width="1370" alt="Screenshot 2023-08-03 at 12 41 12" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/2280fd0d-2f96-4c79-9f35-d5a40a3a853a">

removing opsadmin group role

```
diff --git a/environments/common/iam-groups.auto.tfvars b/environments/common/iam-groups.auto.tfvars
index 019403f..dd6fdab 100644
--- a/environments/common/iam-groups.auto.tfvars
+++ b/environments/common/iam-groups.auto.tfvars
@@ -32,7 +32,7 @@ iam-group_opsadmin = {
   domain       = "terraform.landing.systems"
   #owners       = ["ro..ding.systems"]#, "tfsa..tlz-tlz-de.iam.gserviceaccount.com"] # var.service_accounts
   #managers     = ["roo..m.landing.systems"]
-  members      = ["root..stems", "devel...landing.systems"]
+  members      = ["roo..landing.systems"]
```

**Comment by obriensystems** [comment]
verified lower iam permissions on dev user
<img width="1143" alt="Screenshot 2023-08-03 at 12 51 44" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/2909aaa3-b0b3-4fe3-aaeb-6ebe09d11b7f">

**Comment by fmichaelobrien** [comment]
20240406: Closing issue during retrofit/rebase of this TEF V1 based/modified repo to TEF V4 standards
This issue may participate in the LZ refactor after rebase
Query on all issues related to the older V1 version via the tag
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/labels/2024-pre-tef-v4
