### ISSUE TITLE
Expand out "open in google cloud shell" tutorial steps via https://cloud.google.com/shell/docs/open-in-cloud-shell

### ISSUE THREAD

**Issue by fmichaelobrien** [GoogleCloudPlatform/pbmm-on-gcp-onboarding#28]
# finish the tutorial via the example guides in other issues like #27 and #7
<img width="1522" alt="Screen Shot 2022-03-23 at 2 56 22 PM" src="https://user-images.githubusercontent.com/94715080/159775146-6e087713-d0e0-424e-a9fb-f0af8768ce57.png">

**Comment by obriensystems** [comment]
20240406: Closing issue during retrofit/rebase of this TEF V1 based/modified repo to TEF V4 standards
This issue may participate in the LZ refactor after rebase
Query on all issues related to the older V1 version via the tag
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/labels/2024-pre-tef-v4
