### ISSUE TITLE
Add alerting/monitoring - start with email/essential-contacts alerting on the 2 pairs of partner interconnects - 1 or more in failover to all 4 down

### ISSUE THREAD

**Issue by fmichaelobrien** [GoogleCloudPlatform/pbmm-on-gcp-onboarding#285]
Add terraform modules and resources to prod targeting the interconnects to start in #249 

https://registry.terraform.io/modules/terraform-google-modules/project-factory/google/latest/submodules/essential_contacts

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/monitoring_alert_policy#nested_alert_strategy

monitoring/alerting
https://cloud.google.com/network-connectivity/docs/interconnect/how-to/monitoring
https://cloud.google.com/architecture/security-foundations/logging-monitoring

port to or from https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit/issues/448

**Comment by obriensystems** [comment]
Manual first an an existing vlan attachment set that is up - in order that current 24 metrics flag is set

<img width="1825" alt="Screenshot 2023-08-09 at 12 34 33" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/eb5e3878-5945-41e4-8f7b-e7989fed1364">
<img width="1799" alt="Screenshot 2023-08-09 at 12 34 46" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/448bcba6-ebd8-487f-8876-d2708382ec5d">
<img width="1801" alt="Screenshot 2023-08-09 at 12 34 53" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/5fe185d0-f5c6-4122-95b8-5e286ea8e5b0">
<img width="1830" alt="Screenshot 2023-08-09 at 12 35 51" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/a086eae6-d8e3-4faa-a7f7-77466ad9b46f">
<img width="1822" alt="Screenshot 2023-08-09 at 12 36 04" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/8148f169-1407-47b5-bbc4-412e6d385918">
<img width="1814" alt="Screenshot 2023-08-09 at 12 37 12" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/e3dc05be-b52c-4b3e-805c-c1f28850ebc7">
<img width="1820" alt="Screenshot 2023-08-09 at 12 37 45" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/ca5080d4-f91a-4ecb-9289-ac601dc16d1a">
<img width="1820" alt="Screenshot 2023-08-09 at 12 37 59" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/dc044cad-ed31-47a9-9145-c6938cf4a812">
<img width="1822" alt="Screenshot 2023-08-09 at 12 38 14" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/962cea23-af6a-4d9a-9687-801f4bf84163">
<img width="1819" alt="Screenshot 2023-08-09 at 12 38 53" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/26c3d217-b1e5-4c09-ba5b-6e2a2211caba">
<img width="1824" alt="Screenshot 2023-08-09 at 12 39 32" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/a20db29f-c2e4-400f-9d9c-0b81a1bf2e3b">
<img width="1785" alt="Screenshot 2023-08-09 at 12 40 20" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/a3dc7d2b-1d31-4065-9c52-e98f12127462">
<img width="1823" alt="Screenshot 2023-08-09 at 12 40 37" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/e9abcb1a-4b87-423e-982b-138f809d9dca">
<img width="1809" alt="Screenshot 2023-08-09 at 12 41 10" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/dec6f830-b527-4fd8-b51a-9eb2ecf75c8b">
<img width="1830" alt="Screenshot 2023-08-09 at 12 44 42" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/424785b2-de62-4521-b7de-a4a3ea256073">
<img width="1826" alt="Screenshot 2023-08-09 at 12 49 50" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/a40d11c9-b6b6-407f-a313-43f72d4ea310">

**Comment by obriensystems** [comment]
debugging on partner-interconnect
https://source.cloud.google.com/tzpe-tlz-tlz-de/tlscsr2/+/d605b0997174a7c439832f6e9e5399e85867986a:modules/20-partner-interconnect/main.tf;dlc=53fb91787cff2366fed8b485c320f96659830404

https://console.cloud.google.com/cloud-build/builds;region=global/bfd55143-b614-45dc-b573-cba0168d3643;step=4?project=tzpe-tlz-tlz-de&supportedpurview=project


```

resource "google_monitoring_alert_policy" "alert_policy2" {
    project = var.interconnect_router_project_id
    display_name = "My Alert Policy2"
    combiner     = "OR"
    conditions {
        display_name = "test condition"
        condition_threshold {
            filter     = "metric.type=\"compute.googleapis.com/instance/disk/write_bytes_count\" AND resource.type=\"gce_instance\""
            duration   = "60s"
            comparison = "COMPARISON_GT"
            aggregations {
            alignment_period   = "60s"
            per_series_aligner = "ALIGN_RATE"
            }
        }

    }

    alert_strategy {
        auto_close = true
    }

    user_labels = {
        foo = "bar"
    }
}

#Step #4 - "tf apply": │ Error: project: required field is not set
#Step #4 - "tf apply": │   with module.partner-interconnect-primary.google_monitoring_alert_policy.alert_policy,
#Step #4 - "tf apply": │   on ../../modules/20-partner-interconnect/main.tf line 36, in resource "google_monitoring_alert_policy" "alert_policy":

```

**Comment by obriensystems** [comment]
disabled in prod for now until DNS is up in

https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/issues/286

```

resource "google_monitoring_alert_policy" "alert_policy" {
  project = var.interconnect_router_project_id
  display_name = "router-bgp-session-level-1"
  combiner     = "OR"
  conditions {
    display_name = "test condition"
    condition_threshold {
      filter     = "metric.type=\"compute.googleapis.com/instance/disk/write_bytes_count\" AND resource.type=\"gce_instance\""
      duration   = "60s"
      comparison = "COMPARISON_GT"
      aggregations {
        alignment_period   = "60s"
        per_series_aligner = "ALIGN_RATE"
      }
    }
  }

  user_labels = {
    foo = "bar"
  }
}
```

**Comment by fmichaelobrien** [comment]
20240406: Closing issue during retrofit/rebase of this TEF V1 based/modified repo to TEF V4 standards
This issue may participate in the LZ refactor after rebase
Query on all issues related to the older V1 version via the tag
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/labels/2024-pre-tef-v4
