### ISSUE TITLE
Interconnect Private DNS Zone additions for on prem Private Google Access or Private Service Connect

### ISSUE THREAD

**Issue by fmichaelobrien** [GoogleCloudPlatform/pbmm-on-gcp-onboarding#286]
add #295 
shadow LZ V2 work in
https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit/issues/468
and
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/issues/299
https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit/issues/318
https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit/issues/298

<img width="1556" alt="Screenshot 2023-09-15 at 10 51 52" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/f257c7c2-c155-4eba-bcf0-675310dfb5cf">

continuation of #249
## 20230818: design review
- Vpn instead of peering because of peering brought in via dataflow - same issue we would see using IDS for example  -  the double hop invokes the transitivity issue
- Add 2nd interconnect specifically for non-prod (don’t need the redundant set of vlans)
- DNS peering between vpcs stays
- DNS forwarding stays only on prod - to avoid /19 return issue from on-prem
- turn off ipv4 custom routes across prod/nprod (to avoid route crosstalk)
- NCC  - dont use for now - in preview
- Use non-GCP DNS server on simulated prem - 1st google hit is https://hub.docker.com/r/technitium/dns-server
- Follow https://docs.google.com/presentation/d/13sjT2tJ4yLIYGRREE3wBrylB1OvcEMpKdquVuJB_nX4/edit?resourcekey=0-N3DruQaiutFvZ98HTT7-vQ#slide=id.g1154b3b950f_2_3611
- currently not HA-VPN encrypted on the interconnect - using only VPN over interconnect
- Check macsec (only in dedicated)

# 20230821: 
- review moving prod to hub-env - https://user-images.githubusercontent.com/94715080/197665550-ad97d36d-d122-46b4-aaaa-e0ab9326332a.png
- non-ha interconnect for non prod < 50Mbps)
- output of gcp private zone = ns-zonname.googledomains.com.  - on NS record on zone
- the interconnect router must have the 

## Modifications
- add 2nd set of interconnects off non-prod - in #289
- discuss only vpn and no peering between prod/non-prod if required - as bringing a GCP managed service with underlying IaaS peering will turn the 3 hop nprod-prod-prem into a 4 hop transitive peering network - and break the routing
- add non-prod private zone
- add prod private zone
- add non-prod to prod peering zone - (temporary peering to test routing)
- add prod to prem forwarding - (prod is the only dns route to prem even though interconnects are on both prod and non-prod)

# Customer side requirements

Also, for DNS forwarding return - I thought I read that the 34.199.192.0/19 range was implicitly advertised but hidden on all BGP routing - it turns out it is up to the customer to advertise this - by adding a custom route directly on the interconnect/vpn router beside the dynamic BGP routes - found this a bit odd but I can see optional case for those not wanting cloud to ground and only ground to cloud for SCED/SC2G
- Key for cloud to ground private DNS forwarded queries - add the network-patterns https://docs.google.com/presentation/d/13sjT2tJ4yLIYGRREE3wBrylB1OvcEMpKdquVuJB_nX4/edit?resourcekey=0-N3DruQaiutFvZ98HTT7-vQ#slide=id.g1154b3b950f_2_3152 slide 27 referenced ingress proxy 34.199.192.0/19 as a custom route on the interconnect router (in addition to dynamic subnet routes) - without this DNS queries from gcp to on-prem will not resolve.
- specifically - https://cloud.google.com/dns/docs/policies#return-route
"For Cloud VPN tunnels that use dynamic routing or for Cloud Interconnect, [configure a custom route advertisement](https://cloud.google.com/network-connectivity/docs/router/how-to/advertising-custom-ip) for 35.199.192.0/19 on the BGP session of the Cloud Router that manages the tunnel or VLAN attachment."
- https://cloud.google.com/network-connectivity/docs/router/how-to/advertising-custom-ip
- see also https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit/issues/468
- on top of the partner/direct interconnect add the following
- firewall rule to open incoming DNS query traffic from the private cloud DNS forwarding zone ns 35.199.192.0/19 - https://cloud.google.com/dns/docs/zones/forwarding-zones#firewall-rules
- add 34.199.192.0/19 to the ingress policy on prem
- raise an issue with GCP on whether we can add a customer provided IP for return DNS traffic

# Requirements
private zone only from Xavier and our client
https://cloud.google.com/dns/docs/zones/forwarding-zones#terraform
https://cloud.google.com/blog/products/networking/how-to-use-cloud-dns-peering-in-a-shared-vpc-environment/
folderIAMAdmin needed on parent folder of each project (for bq)
forwarding from on prem to GCP:
forwarding from gCP to on prem:

# My notes:
gcloud example
```
enable dns, compute
 gcloud dns --project=all-services-obs managed-zones create private-obrien-software --description="" --dns-name="private.obrien.software." --visibility="private" --networks="https://www.googleapis.com/compute/v1/projects/all-services-obs/global/networks/default"
```

add A and CNAME records

zone
<img width="1450" alt="Screenshot 2023-08-12 at 22 08 39" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/80c9b9f1-9509-4f4f-9183-2ff37df6fabd">

name server - use PSC to *.googledomains.com.
<img width="1315" alt="Screenshot 2023-08-12 at 22 07 36" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/aab3c022-6a83-438a-8200-5628bc1d8883">

# links
- https://github.com/terraform-google-modules/terraform-docs-samples/blob/HEAD/dns/managed_zone_private/main.tf
- https://cloud.google.com/vpc/docs/configure-private-google-access-hybrid
- https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/blueprints/cloud-operations/dns-shared-vpc/README.md instead of https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/tree/master/examples/cloud-operations/dns-shared-vpc in https://cloud.google.com/blog/products/networking/how-to-use-cloud-dns-peering-in-a-shared-vpc-environment/ see #1586 in https://github.com/CloudLandingZone/cloud-foundation-fabric/tree/master
- https://cloud.google.com/dns/docs/zones/forwarding-zones#terraform

# Architecture

202300821: new
<img width="1162" alt="Screenshot 2023-08-21 at 13 59 07" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/a6453b9c-3de9-4f48-a931-9e98f273bec8">

20230818: old
<img width="1097" alt="Screenshot 2023-08-16 at 09 11 03" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/57c44441-bbf0-4c06-a87b-59b91582c2f4">

# Design Issues

## DI 0: Decide on network architecture
- we are option B Hybrid Connectivity to Multiple VPC (or Shared VPC) networks
- slide 27 - B3:  Hybrid DNS Option 1
- slide 30 - B6:  Private Service Connect (PSC) for Google APIs
https://docs.google.com/presentation/d/13sjT2tJ4yLIYGRREE3wBrylB1OvcEMpKdquVuJB_nX4/edit?resourcekey=0-N3DruQaiutFvZ98HTT7-vQ#slide=id.g1154b3b950f_2_3611
- 
<img width="1253" alt="Screenshot 2023-08-16 at 08 17 07" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/33179dfb-c4c0-48c6-b914-b5f75010f7fc">
-
<img width="1254" alt="Screenshot 2023-08-16 at 08 17 25" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/f1a8438b-95ab-4ea1-8e16-1a8b83eb119c">

found older notes I made in March in https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit/issues/318
## DI 1: DNS Forwarding (type 2 to on prem dns server) and DNS Peering
- https://cloud.google.com/dns/docs/zones/forwarding-zones#console
- https://cloud.google.com/dns/docs/zones/peering-zones
- https://cloud.google.com/dns/docs/zones/zones-overview#forwarding-peering-example
- https://cloud.google.com/blog/products/networking/how-to-use-cloud-dns-peering-in-a-shared-vpc-environment

# simulation
- 3 VPCs host, perimeter, on-prem (all need private google access set on their subnets only - can be edited later)
- vpc peering between host and perimeter
- private zones in on-prem site.local and perimeter cloud.local
- dns peering in host to
- dns forwarding from on-prem to host
- dns forwarding from host to on-prem 

# Testing
Using existing VPN in ol for PSC simulation (however global routing across 2 regions is set - may need a regional VPN)
<img width="1439" alt="Screenshot 2023-08-16 at 07 45 44" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/20d09186-236c-473e-9809-f23dd20fba39">

<img width="1400" alt="Screenshot 2023-08-16 at 07 48 27" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/1d1fa023-69bd-4f02-a6aa-c95d918c6f98">

on the VMs get dig
```
sudo apt-get install dnsutils -y
dig www.google.com
```

## Procedures
- https://cloud.google.com/dns/docs/policies#create-in

## Implementation
- on prem DNS servers are authoritative for on prem zones
- cloud DNS is authoritative for GCP zones
- DNS queries from GCP to on-prem use 35.199.192.0/19
### Manual
- simulate on-prem...(other CSP or eBGP enabled home router)
- create folder dns-20230815-286
- create 4 projects 
- sim-dns-prod-host -  host project enabled on shared vpc creation
- sim-dns-nonprod-host - host project enabled on shared vpc creation
- sim-dns-dns
- sim-dns-prem
- enable apis
```
gcloud config set project sim-dns-nonprod-host
gcloud services enable compute.googleapis.com dns.googleapis.com
do all 4
```
- set permissions 
Required 'compute.organizations.enableXpnHost' permission for 'projects/dns-host-ol' - https://gcp.permissions.cloud/predefinedroles/compute.xpnAdmin
- create custom vpc (for reuse as shared vpc)
```
gcloud compute networks create host --project=dns-host-ol --description=hody --subnet-mode=custom --mtu=1460 --bgp-routing-mode=regional
gcloud compute networks subnets create host-sn --project=dns-host-ol --description=host-sn --range=10.0.2.0/24 --stack-type=IPV4_ONLY --network=host --region=northamerica-northeast1 --enable-private-ip-google-access
```
- create host shared-vpc (custom networks, dns api enabled) - delete default vpc
- 
- create dns private zones in host project
```
gcloud dns --project=dns-host-ol managed-zones create private --description="" --dns-name="private.obrienlabs.dev." --visibility="private" --networks="host"
```
- enable compute api
- create shared vpc
- create service project dns-sp-ol
- create dns egress proxy in shared vpc
- create inbound server policy in Cloud DNS for on prem
- create forwarding zone in Cloud DNS for on prem
- 
- On Prem DNS
- 
-

**Comment by obriensystems** [comment]
on m * ob.soft
project all-services-obs

https://cloud.google.com/dns/docs/zones/forwarding-zones#console

```
gcloud compute networks create gcp-prod-host --project=all-services-obs --subnet-mode=custom --mtu=1460 --bgp-routing-mode=regional && gcloud compute networks subnets create gcp-prod-host-pri --project=all-services-obs --range=10.1.0.0/24 --stack-type=IPV4_ONLY --network=gcp-prod-host --region=northamerica-northeast1 --enable-private-ip-google-access && gcloud compute firewall-rules create gcp-prod-host-allow-custom --project=all-services-obs --network=projects/all-services-obs/global/networks/gcp-prod-host --description=Allows\ connection\ from\ any\ source\ to\ any\ instance\ on\ the\ network\ using\ custom\ protocols. --direction=INGRESS --priority=65534 --source-ranges=10.1.0.0/24 --action=ALLOW --rules=all && gcloud compute firewall-rules create gcp-prod-host-allow-icmp --project=all-services-obs --network=projects/all-services-obs/global/networks/gcp-prod-host --description=Allows\ ICMP\ connections\ from\ any\ source\ to\ any\ instance\ on\ the\ network. --direction=INGRESS --priority=65534 --source-ranges=0.0.0.0/0 --action=ALLOW --rules=icmp && gcloud compute firewall-rules create gcp-prod-host-allow-rdp --project=all-services-obs --network=projects/all-services-obs/global/networks/gcp-prod-host --description=Allows\ RDP\ connections\ from\ any\ source\ to\ any\ instance\ on\ the\ network\ using\ port\ 3389. --direction=INGRESS --priority=65534 --source-ranges=0.0.0.0/0 --action=ALLOW --rules=tcp:3389 && gcloud compute firewall-rules create gcp-prod-host-allow-ssh --project=all-services-obs --network=projects/all-services-obs/global/networks/gcp-prod-host --description=Allows\ TCP\ connections\ from\ any\ source\ to\ any\ instance\ on\ the\ network\ using\ port\ 22. --direction=INGRESS --priority=65534 --source-ranges=0.0.0.0/0 --action=ALLOW --rules=tcp:22

2nd vpc
gcloud compute networks create on-prem --project=all-services-obs --subnet-mode=custom --mtu=1460 --bgp-routing-mode=regional && gcloud compute networks subnets create on-prem-sn --project=all-services-obs --range=10.21.0.0/24 --stack-type=IPV4_ONLY --network=on-prem --region=northamerica-northeast1 --enable-private-ip-google-access && gcloud compute firewall-rules create on-prem-allow-custom --project=all-services-obs --network=projects/all-services-obs/global/networks/on-prem --description=Allows\ connection\ from\ any\ source\ to\ any\ instance\ on\ the\ network\ using\ custom\ protocols. --direction=INGRESS --priority=65534 --source-ranges=10.21.0.0/24 --action=ALLOW --rules=all && gcloud compute firewall-rules create on-prem-allow-icmp --project=all-services-obs --network=projects/all-services-obs/global/networks/on-prem --description=Allows\ ICMP\ connections\ from\ any\ source\ to\ any\ instance\ on\ the\ network. --direction=INGRESS --priority=65534 --source-ranges=0.0.0.0/0 --action=ALLOW --rules=icmp && gcloud compute firewall-rules create on-prem-allow-rdp --project=all-services-obs --network=projects/all-services-obs/global/networks/on-prem --description=Allows\ RDP\ connections\ from\ any\ source\ to\ any\ instance\ on\ the\ network\ using\ port\ 3389. --direction=INGRESS --priority=65534 --source-ranges=0.0.0.0/0 --action=ALLOW --rules=tcp:3389 && gcloud compute firewall-rules create on-prem-allow-ssh --project=all-services-obs --network=projects/all-services-obs/global/networks/on-prem --description=Allows\ TCP\ connections\ from\ any\ source\ to\ any\ instance\ on\ the\ network\ using\ port\ 22. --direction=INGRESS --priority=65534 --source-ranges=0.0.0.0/0 --action=ALLOW --rules=tcp:22
```

**Comment by obriensystems** [comment]
Simpler pass on host+services projects and prem using
https://cloud.google.com/blog/products/networking/how-to-use-cloud-dns-peering-in-a-shared-vpc-environment/

**Comment by obriensystems** [comment]
Validation 1: Peering between non-prod and prod (owner of the interconnects) - will pass bgp routes.  This will avoid duplication of the interconnects in non-prod - less secure but lower cost
<img width="1097" alt="Screenshot 2023-08-16 at 09 11 03" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/57c44441-bbf0-4c06-a87b-59b91582c2f4">


- in progress on ol VPN test site

**Comment by obriensystems** [comment]
Validation 2: DNS forwarding between prod host (gcp) and on-prem (do the reverse next - then work on dns peering with the 3 VPCs)

add private zones
```
#gcloud dns --project=interconnect-perim-ol managed-zones create private --description="prod-pri-zone" --dns-name="prod.local." --visibility="private" --networks="gcp-vpc"
gcloud dns --project=interconnect-perim-ol managed-zones create prod-pri-zone --description="prod-pri-zone" --dns-name="prod.local." --visibility="private" --networks="https://www.googleapis.com/compute/v1/projects/interconnect-perim-ol/global/networks/gcp-vpc"

output
routing data NS
ns-gcp-private.googledomains.com.

GET https://dns.googleapis.com/dns/v1beta2/projects/interconnect-perim-ol/managedZones/prod-pri-zone/rrsets/prod.local./NS
{
  "name": "prod.local.",
  "rrdata": [
    "ns-gcp-private.googledomains.com."
  ],
  "ttl": 21600,
  "type": "NS"
}

prem
gcloud dns --project=interconnect-perim-ol managed-zones create prem-pri-zone --description="prem-pri-zone" --dns-name="prem.local." --visibility="private" --networks="https://www.googleapis.com/compute/v1/projects/interconnect-perim-ol/global/networks/on-prem"

output:
routing ns
ns-gcp-private.googledomains.com.

```

add forwarding zones

add peer zones (later)

**Comment by obriensystems** [comment]
Try embedded module before trying cff off
https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/blueprints/cloud-operations/dns-shared-vpc/main.tf

https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/tree/main/modules/dns-zone/examples
without the public zone


```
│ Error: Error creating ManagedZone: googleapi: Error 403: Cloud DNS API has not been used in project tzpe-tlz-tlzprod-host4 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/dns.googleapis.com/overview?project=tzpe-tlz-tlzprod-host4 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.


add api to prod
dns.googleapis.com
```

example working - modifying to production

<img width="1160" alt="Screenshot 2023-08-21 at 09 02 36" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/1008023c-9cb3-42f7-88ce-e7377208fe93">

<img width="1532" alt="Screenshot 2023-08-21 at 09 02 15" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/337c4116-9c99-435f-8ece-fe823ac35eb2">

```
Step #4 - "tf apply": module.net-host-prj.module.project.google_project_service.project_services["dns.googleapis.com"]: Creating...
Step #4 - "tf apply": module.net-host-prj.module.project.google_project_service.project_services["dns.googleapis.com"]: Still creating... [10s elapsed]
Step #4 - "tf apply": module.net-host-prj.module.project.google_project_service.project_services["dns.googleapis.com"]: Still creating... [20s elapsed]
Step #4 - "tf apply": module.net-host-prj.module.project.google_project_service.project_services["dns.googleapis.com"]: Creation complete after 21s [id=tzpe-tlz-tlzprod-host4/dns.googleapis.com]
Step #4 - "tf apply": module.private_zone.google_dns_managed_zone.private[0]: Creating...
Step #4 - "tf apply": module.forwarding_zone.google_dns_managed_zone.forwarding[0]: Creating...
Step #4 - "tf apply": module.net-host-prj.module.network["tlzprod-svpc"].module.subnets["prsubnet02"].google_compute_subnetwork.subnetwork: Modifying... [id=projects/tzpe-tlz-tlzprod-host4/regions/northamerica-northeast1/subnetworks/tzpecnr-prsubnet02-host4-snet]
Step #4 - "tf apply": module.net-host-prj.module.network["tlzprod-svpc"].module.subnets["prsubnet02"].google_compute_subnetwork.subnetwork: Modifications complete after 0s [id=projects/tzpe-tlz-tlzprod-host4/regions/northamerica-northeast1/subnetworks/tzpecnr-prsubnet02-host4-snet]
Step #4 - "tf apply": module.forwarding_zone.google_dns_managed_zone.forwarding[0]: Creation complete after 1s [id=projects/tzpe-tlz-tlzprod-host4/managedZones/dns-local]
Step #4 - "tf apply": module.private_zone.google_dns_managed_zone.private[0]: Creation complete after 1s [id=projects/tzpe-tlz-tlzprod-host4/managedZones/private-local]
Step #4 - "tf apply": module.private_zone.google_dns_record_set.cloud-static-records["/TXT"]: Creating...
Step #4 - "tf apply": module.private_zone.google_dns_record_set.cloud-static-records["ns/A"]: Creating...
Step #4 - "tf apply": module.private_zone.google_dns_record_set.cloud-static-records["/MX"]: Creating...
Step #4 - "tf apply": module.private_zone.google_dns_record_set.cloud-static-records["localhost/A"]: Creating...
Step #4 - "tf apply": module.private_zone.google_dns_record_set.cloud-static-records["/MX"]: Creation complete after 1s [id=projects/tzpe-tlz-tlzprod-host4/managedZones/private-local/rrsets/private.local./MX]
Step #4 - "tf apply": module.private_zone.google_dns_record_set.cloud-static-records["localhost/A"]: Creation complete after 2s [id=projects/tzpe-tlz-tlzprod-host4/managedZones/private-local/rrsets/localhost.private.local./A]
Step #4 - "tf apply": module.private_zone.google_dns_record_set.cloud-static-records["/TXT"]: Creation complete after 2s [id=projects/tzpe-tlz-tlzprod-host4/managedZones/private-local/rrsets/private.local./TXT]
Step #4 - "tf apply": module.private_zone.google_dns_record_set.cloud-static-records["ns/A"]: Creation complete after 2s [id=projects/tzpe-tlz-tlzprod-host4/managedZones/private-local/rrsets/ns.private.local./A]
Step #4 - "tf apply": ╷
```

<img width="1765" alt="Screenshot 2023-08-21 at 09 03 23" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/63a16d6e-f400-44f6-a5d1-8f4e4ffd6aa4">

**Comment by fmichaelobrien** [comment]
# Customer side requirements

Also, for DNS forwarding return - I thought I read that the 34.199.192.0/19 range was implicitly advertised but hidden on all BGP routing - it turns out it is up to the customer to advertise this - by adding a custom route directly on the interconnect/vpn router beside the dynamic BGP routes - found this a bit odd but I can see optional case for those not wanting cloud to ground and only ground to cloud for SCED/SC2G
- Key for cloud to ground private DNS forwarded queries - add the network-patterns https://docs.google.com/presentation/d/13sjT2tJ4yLIYGRREE3wBrylB1OvcEMpKdquVuJB_nX4/edit?resourcekey=0-N3DruQaiutFvZ98HTT7-vQ#slide=id.g1154b3b950f_2_3152 slide 27 referenced ingress proxy 34.199.192.0/19 as a custom route on the interconnect router (in addition to dynamic subnet routes) - without this DNS queries from gcp to on-prem will not resolve.
- specifically - https://cloud.google.com/dns/docs/policies#return-route
"For Cloud VPN tunnels that use dynamic routing or for Cloud Interconnect, [configure a custom route advertisement](https://cloud.google.com/network-connectivity/docs/router/how-to/advertising-custom-ip) for 35.199.192.0/19 on the BGP session of the Cloud Router that manages the tunnel or VLAN attachment."
- https://cloud.google.com/network-connectivity/docs/router/how-to/advertising-custom-ip
- see also https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit/issues/468
- on top of the partner/direct interconnect add the following
- firewall rule to open incoming DNS query traffic from the private cloud DNS forwarding zone ns 35.199.192.0/19 - https://cloud.google.com/dns/docs/zones/forwarding-zones#firewall-rules
- add 34.199.192.0/19 to the ingress policy on prem
- raise an issue with GCP on whether we can add a customer provided IP for return DNS traffic

**Comment by obriensystems** [comment]
AWS (prem/ground) to GCP HA VPN up for private google access and DNS forwarding simulation in 
https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit/issues/494
and shadow

**Comment by fmichaelobrien** [comment]
20240406: Closing issue during retrofit/rebase of this TEF V1 based/modified repo to TEF V4 standards
This issue may participate in the LZ refactor after rebase
Query on all issues related to the older V1 version via the tag
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/labels/2024-pre-tef-v4
