### ISSUE TITLE
remove/consolidate bootstrap.sh run() function - it has no effect as run functionality is duplicated in the case statement

### ISSUE THREAD

**Issue by fmichaelobrien** [GoogleCloudPlatform/pbmm-on-gcp-onboarding#29]
The function run()
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/blob/main/environments/bootstrap/bootstrap.sh#L27

```
function run () {
 auth
 apply_roles
 tf_apply
 upload_statefile
 create_backends
 create_csr
} 
```
is not run because we already run the sub function calls directly in 

https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/blob/main/environments/bootstrap/bootstrap.sh#L412

```
case $1 in
  run)
  auth
  apply_roles
  tf_apply
  upload_statefile
  create_backends
  create_csr
  ;;
```

**Comment by obriensystems** [comment]
20240406: Closing issue during retrofit/rebase of this TEF V1 based/modified repo to TEF V4 standards
This issue may participate in the LZ refactor after rebase
Query on all issues related to the older V1 version via the tag
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/labels/2024-pre-tef-v4
