### ISSUE TITLE
Fix typo on 2nd DNS IP address on forwarding zone to on-prem - thanks George

### ISSUE THREAD

**Issue by obriensystems** [GoogleCloudPlatform/pbmm-on-gcp-onboarding#293]
on top of #249  and #286 

https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/blob/main/environments/prod/dns.tf#L96

https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/commit/64b92b4e0d81aa9457eb1be608a51c148b2a542e#diff-e786f41fff47bec09c1aa8908300e6672b88f088d711488c54e93e9b2a22ffdeR96

**Comment by fmichaelobrien** [comment]
20240406: Closing issue during retrofit/rebase of this TEF V1 based/modified repo to TEF V4 standards
This issue may participate in the LZ refactor after rebase
Query on all issues related to the older V1 version via the tag
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/labels/2024-pre-tef-v4
