### ISSUE TITLE
Feature: add partner interconnect also to non-prod and add DNS peering zone in np to the forwarding zone in prod - no VPC peering required - missing dns inbound policy

### ISSUE THREAD

**Issue by obriensystems** [GoogleCloudPlatform/pbmm-on-gcp-onboarding#294]
In addition to work in #249 and #286
after #295 and #293 

update: missing inbound dns policy

```
michael@gcp-server:~$ ping vm.prem.local
ping: vm.prem.local: Name or service not known
```

**Comment by obriensystems** [comment]
nonprod forwarding zone
```
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   environments/nonprod/variables.tf
        modified:   environments/prod/dns.tf
        modified:   environments/prod/variables.tf
        modified:   writeids.sh

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        environments/nonprod/dns.tf
        environments/nonprod/nprod-dns.auto.tfvars
        modules/21-workloads/
```

**Comment by obriensystems** [comment]
Test out prod to prem first to get 3 route DNS routing
![Uploading Screenshot 2023-08-23 at 12.17.41.png…]()

```
gcloud dns --project=interconnect-perim-ol managed-zones create peer-prod-to-prem-vpc --description="" --dns-name="prod.local." --visibility="private" --networks="" --target-project="interconnect-perim-ol" --target-network="on-prem"
```
had network association set - resetting
<img width="878" alt="Screenshot 2023-08-23 at 12 18 51" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/733d53ad-e492-498e-a29f-a8b0174ba31f">

failed to on-prem - reversing to (prod to on-prem)

<img width="610" alt="Screenshot 2023-08-23 at 12 21 42" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/c3a4c8e6-4776-43c9-9118-9b2ca1e7612f">

```
gcloud dns --project=interconnect-perim-ol managed-zones create peer-prod-to-prem-vpc --description="" --dns-name="prod.local." --visibility="private" --networks="" --target-project="interconnect-perim-ol" --target-network="on-prem"
```
<img width="637" alt="Screenshot 2023-08-23 at 12 22 46" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/fca1ac96-b1a7-43f6-ab82-21eb001a9e28">

attempt associate with prod - already in use again

**Comment by fmichaelobrien** [comment]
20240406: Closing issue during retrofit/rebase of this TEF V1 based/modified repo to TEF V4 standards
This issue may participate in the LZ refactor after rebase
Query on all issues related to the older V1 version via the tag
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/labels/2024-pre-tef-v4
