### ISSUE TITLE
Add Google DNS Egress Proxy CIDR 34.199.192.0/19 as an additional static route to the interconnect router - keep bgp dynamic routes

### ISSUE THREAD

**Issue by obriensystems** [GoogleCloudPlatform/pbmm-on-gcp-onboarding#295]
on top of 
#249 
#286

Also, for DNS forwarding return - I thought I read that the 34.199.192.0/19 range was implicitly advertised but hidden on all BGP routing - it turns out it is up to the customer to advertise this - by adding a custom route directly on the interconnect/vpn router beside the dynamic BGP routes - found this a bit odd but I can see optional case for those not wanting cloud to ground and only ground to cloud for SCED/SC2G
- Key for cloud to ground private DNS forwarded queries - add the network-patterns https://docs.google.com/presentation/d/13sjT2tJ4yLIYGRREE3wBrylB1OvcEMpKdquVuJB_nX4/edit?resourcekey=0-N3DruQaiutFvZ98HTT7-vQ#slide=id.g1154b3b950f_2_3152 slide 27 referenced ingress proxy 34.199.192.0/19 as a custom route on the interconnect router (in addition to dynamic subnet routes) - without this DNS queries from gcp to on-prem will not resolve.
- specifically - https://cloud.google.com/dns/docs/policies#return-route
"For Cloud VPN tunnels that use dynamic routing or for Cloud Interconnect, [configure a custom route advertisement](https://cloud.google.com/network-connectivity/docs/router/how-to/advertising-custom-ip) for 35.199.192.0/19 on the BGP session of the Cloud Router that manages the tunnel or VLAN attachment."
- https://cloud.google.com/network-connectivity/docs/router/how-to/advertising-custom-ip
- see also https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit/issues/468
- on top of the partner/direct interconnect add the following
- firewall rule to open incoming DNS query traffic from the private cloud DNS forwarding zone ns 35.199.192.0/19 - https://cloud.google.com/dns/docs/zones/forwarding-zones#firewall-rules
- add 34.199.192.0/19 to the ingress policy on prem
- raise an issue with GCP on whether we can add a customer provided IP for return DNS traffic

**Comment by obriensystems** [comment]
follow
https://registry.terraform.io/providers/hashicorp/google/3.0.0-beta.1/docs/resources/compute_router#example-usage---router-basic

```
gp {
    asn               = 16550
    advertise_mode    = "CUSTOM"
    advertised_groups = ["ALL_SUBNETS"]
    advertised_ip_ranges {
      range = "34.199.192.0/19"
      description = "DNS Egress Proxy"
    }
```

**Comment by obriensystems** [comment]
Note: make kcc shadow

**Comment by obriensystems** [comment]
testing
```
Step #3 - "tf plan":   # module.partner-interconnect-primary.google_compute_router.router1 will be updated in-place
Step #3 - "tf plan":   ~ resource "google_compute_router" "router1" {
Step #3 - "tf plan":         id                 = "projects/tzpe-tlz-tlzprod-host4/regions/northamerica-northeast1/routers/interconnect-prod-router"
Step #3 - "tf plan":         name               = "interconnect-prod-router"
Step #3 - "tf plan":         # (5 unchanged attributes hidden)
Step #3 - "tf plan": 
Step #3 - "tf plan":       ~ bgp {
Step #3 - "tf plan":           ~ advertise_mode    = "DEFAULT" -> "CUSTOM"
Step #3 - "tf plan":           ~ advertised_groups = [
Step #3 - "tf plan":               + "ALL_SUBNETS",
Step #3 - "tf plan":             ]
Step #3 - "tf plan":             # (1 unchanged attribute hidden)
Step #3 - "tf plan": 
Step #3 - "tf plan":           + advertised_ip_ranges {
Step #3 - "tf plan":               + description = "DNS Egress Proxy"
Step #3 - "tf plan":               + range       = "34.199.192.0/19"
Step #3 - "tf plan":             }
Step #3 - "tf plan":         }
Step #3 - "tf plan":     }
```
<img width="893" alt="Screenshot 2023-08-23 at 10 42 34" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/e491aaff-0846-477b-b072-f182784ad0f5">

**Comment by fmichaelobrien** [comment]
20240406: Closing issue during retrofit/rebase of this TEF V1 based/modified repo to TEF V4 standards
This issue may participate in the LZ refactor after rebase
Query on all issues related to the older V1 version via the tag
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/labels/2024-pre-tef-v4
