### ISSUE TITLE
move #295 DNS Egress Proxy 34.199.192.0/19 out of modules into a tfvar in environments - even though it is static

### ISSUE THREAD

**Issue by obriensystems** [GoogleCloudPlatform/pbmm-on-gcp-onboarding#296]
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/blob/main/modules/20-partner-interconnect/main.tf#L78

see #295
and
#286 
#249

**Comment by fmichaelobrien** [comment]
20240406: Closing issue during retrofit/rebase of this TEF V1 based/modified repo to TEF V4 standards
This issue may participate in the LZ refactor after rebase
Query on all issues related to the older V1 version via the tag
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/labels/2024-pre-tef-v4
