### ISSUE TITLE
PR contribution 291 - refactor modules/logging-center/main.tf hardcoded services list out into env/common tfvars

### ISSUE THREAD

**Issue by obriensystems** [GoogleCloudPlatform/pbmm-on-gcp-onboarding#314]
See example implementation fix in the two for audit and guardrails
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/pull/291/files#diff-cb9302fb17255576bca335da2817cda2a821b776209c180f929f6527396f89fd

```
services                                = ["storage.googleapis.com", "logging.googleapis.com", "monitoring.googleapis.com"]
```

Hardcoded service list needs to move out of modules into a tfvar in environments/common
For an example fix - see #284  - 2 PRs as reference

https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/pull/310/files#diff-acb71cc23936666b11db107a6fe60a986ed76ee48c2150b4e035b7519b4e973dR83

https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/pull/313

**Comment by fmichaelobrien** [comment]
20240406: Closing issue during retrofit/rebase of this TEF V1 based/modified repo to TEF V4 standards
This issue may participate in the LZ refactor after rebase
Query on all issues related to the older V1 version via the tag
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/labels/2024-pre-tef-v4
