### ISSUE TITLE
Routing logs from log sinks to 3rd party software such as Splunk using PubSub

### ISSUE THREAD

**Issue by obriensystems** [GoogleCloudPlatform/pbmm-on-gcp-onboarding#318]
Use Case is around routing logs to 3rd party software on prem

add centralized logging project bucket as logging sink targets from workloads https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit/blob/main/solutions/core-landing-zone/lz-folder/audits/logging-project/cloud-logging-buckets.yaml#L41

follow guidance below
https://cloud.google.com/logging/docs/routing/overview#sinks
https://cloud.google.com/logging/docs/export/aggregated_sinks
https://cloud.google.com/logging/docs/export/pubsub
https://cloud.google.com/storage/docs/pubsub-notifications
https://cloud.google.com/architecture/monitoring

Splunk Log Sink and Filtering
https://cloud.google.com/architecture/stream-logs-from-google-cloud-to-splunk
https://registry.terraform.io/modules/terraform-google-modules/log-export/google/latest/examples/splunk-sink

https://cloud.google.com/architecture/security-foundations/logging-monitoring

20231015 work starting on older branch v20230917 adding an alternate org sink until the main branch is stabilized
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/releases/tag/v20230917
see #332 

Branching off 332 branch for PRs related to log sinks
<img width="472" alt="Screenshot 2023-10-15 at 19 18 35" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/5424c741-cfa1-468e-a865-ade0afe3066b">

use
```
git checkout 318-log-sink-alerting
```
diff between 332 branch
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/pull/334/files

diff between main branch
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/pull/333/files

### Current state
- organization log sink is there at the org root under the defined variable https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/blob/main/environments/common/common.auto.tfvars#L73  sink_name
- the logs are warning level only

- see https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/blob/main/docs/google-cloud-security-controls.md#cloud-logging---logs-router
<img width="1780" alt="Screenshot 2023-10-15 at 20 15 33" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/ad202eef-4e8c-4c33-85a9-c00a487b4108">
- the logs route to the bucket storage.googleapis.com/tzpeaudittlz with a retention of 1 sec
<img width="1795" alt="Screenshot 2023-10-15 at 20 16 39" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/dc0c9c1d-ec73-4294-bb8b-99421d6f776e">
under coldline storage
<img width="1422" alt="Screenshot 2023-10-15 at 20 18 11" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/d1488dfe-e63d-4042-b86a-7f68fc41a0a0">
for example authenticated URL
https://storage.cloud.google.com/tzpeaudittlz/cloudaudit.googleapis.com/activity/2023/01/31/17%3A00%3A00_17%3A59%3A59_S0.json

```
{"insertId":"1nnt445c5pn","logName":"organizations/131880894992/logs/cloudaudit.googleapis.com%2Factivity","protoPayload":{"@type":"type.googleapis.com/google.cloud.audit.AuditLog","authenticationInfo":{"principalEmail":"tfsa0131@tzpe-tlz-tlz-de.iam.gserviceaccount.com","serviceAccountDelegationInfo":[{"firstPartyPrincipal":{"principalEmail":"407485305437@cloudbuild.gserviceaccount.com"}},{"firstPartyPrincipal":{"principalEmail":"cloud-build-argo-foreman@prod.google.com"}}]},"authorizationInfo":[{"granted":true,"permission":"accesscontextmanager.policies.create","resource":"organizations/131880894992","resourceAttributes":{}}],"metadata":{"idaasCustomerId":"C02e6x9c7","userId":"101414391001446101002"},"methodName":"google.identity.accesscontextmanager.v1.AccessContextManager.CreateAccessPolicy","request":{"@type":"type.googleapis.com/google.identity.accesscontextmanager.v1.AccessPolicy","parent":"organizations/131880894992"},"requestMetadata":{"callerIp":"34.67.85.47","callerSuppliedUserAgent":"Terraform/1.0.10 (+https://www.terraform.io) Terraform-Plugin-SDK/2.5.0 terraform-provider-google/3.90.1,gzip(gfe),gzip(gfe)","destinationAttributes":{},"requestAttributes":{"auth":{},"time":"2023-01-31T17:03:06.538767Z"}},"resourceName":"organizations/131880894992","serviceName":"accesscontextmanager.googleapis.com","status":{"code":6,"message":"Policy already exists with parent organizations/131880894992"}},"receiveTimestamp":"2023-01-31T17:03:06.933885627Z","resource":{"labels":{"method":"google.identity.accesscontextmanager.v1.AccessContextManager.CreateAccessPolicy","service":"accesscontextmanager.googleapis.com"},"type":"audited_resource"},"severity":"ERROR","timestamp":"2023-01-31T17:03:06.458004Z"}
```

or a later PSC endpoint
https://storage.cloud.google.com/tzpeaudittlz/cloudaudit.googleapis.com/activity/2023/09/06/14%3A00%3A00_14%3A59%3A59_S1.json?_ga=2.86505105.-885096055.1674837219

```
{"insertId":"j59qz8e92zgy","logName":"projects/tzpe-tlz-tlzprod-host4/logs/cloudaudit.googleapis.com%2Factivity","protoPayload":{"@type":"type.googleapis.com/google.cloud.audit.AuditLog","authenticationInfo":{"principalEmail":"tfsa0131@tzpe-tlz-tlz-de.iam.gserviceaccount.com","principalSubject":"serviceAccount:tfsa0131@tzpe-tlz-tlz-de.iam.gserviceaccount.com","serviceAccountDelegationInfo":[{"firstPartyPrincipal":{"principalEmail":"407485305437@cloudbuild.gserviceaccount.com"}},{"firstPartyPrincipal":{"principalEmail":"cloud-build-argo-foreman@prod.google.com"}}]},"authorizationInfo":[{"granted":true,"permission":"compute.globalForwardingRules.create","resourceAttributes":{"name":"projects/tzpe-tlz-tlzprod-host4/global/forwardingRules/psc-incoming","service":"compute","type":"compute.globalForwardingRules"}},{"granted":true,"permission":"compute.globalForwardingRules.pscCreate","resourceAttributes":{"name":"projects/tzpe-tlz-tlzprod-host4/global/forwardingRules/psc-incoming","service":"compute","type":"compute.globalForwardingRules"}},{"granted":true,"permission":"compute.networks.use","resourceAttributes":{"name":"projects/tzpe-tlz-tlzprod-host4/global/networks/tzpecnr-tlzprod-svpc-vpc","service":"compute","type":"compute.networks"}},{"granted":true,"permission":"compute.globalAddresses.use","resourceAttributes":{"name":"projects/tzpe-tlz-tlzprod-host4/global/addresses/global-psconnect-ip","service":"compute","type":"compute.globalAddresses"}}],"methodName":"beta.compute.globalForwardingRules.insert","request":{"@type":"type.googleapis.com/compute.globalForwardingRules.insert","IPAddress":"projects/tzpe-tlz-tlzprod-host4/global/addresses/global-psconnect-ip","name":"psc-incoming","network":"projects/tzpe-tlz-tlzprod-host4/global/networks/tzpecnr-tlzprod-svpc-vpc","target":"all-apis"},"requestMetadata":{"callerIp":"34.27.112.162","callerSuppliedUserAgent":"Terraform/1.0.10 (+https://www.terraform.io) Terraform-Plugin-SDK/2.10.1 terraform-provider-google-beta/4.81.0 blueprints/terraform/terraform-google-network:private-service-connect/v7.3.0,gzip(gfe)","destinationAttributes":{},"requestAttributes":{"auth":{},"time":"2023-09-06T14:08:18.136012Z"}},"resourceLocation":{"currentLocations":["global"]},"resourceName":"projects/tzpe-tlz-tlzprod-host4/global/forwardingRules/psc-incoming","response":{"@type":"type.googleapis.com/error","error":{"code":400,"errors":[{"domain":"global","message":"Invalid value for field 'resource.name': 'psc-incoming'. The forwarding rule name for PSC Google APIs must be an 1-20 characters string with lowercase letters and numbers and must start with a letter.","reason":"invalid"}],"message":"Invalid value for field 'resource.name': 'psc-incoming'. The forwarding rule name for PSC Google APIs must be an 1-20 characters string with lowercase letters and numbers and must start with a letter."}},"serviceName":"compute.googleapis.com","status":{"code":3,"message":"Invalid value for field 'resource.name': 'psc-incoming'. The forwarding rule name for PSC Google APIs must be an 1-20 characters string with lowercase letters and numbers and must start with a letter."}},"receiveTimestamp":"2023-09-06T14:08:18.670124354Z","resource":{"labels":{"forwarding_rule_id":"","project_id":"tzpe-tlz-tlzprod-host4","region":"global"},"type":"gce_forwarding_rule"},"severity":"ERROR","timestamp":"2023-09-06T14:08:18.041559Z"}
```

### Future state
Org sink
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/logging_organization_sink

Project sink
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/logging_project_sink

**Comment by obriensystems** [comment]
A good example of bug chasing for 30 min (nothing related to actual coding dev or devops) - just a typo 
Hint: was not an issue with any of the actual terraform yaml code

<img width="1781" alt="Screenshot 2023-10-15 at 21 12 28" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/c420a627-561c-4c1f-afc8-6caf8a419119">

<img width="1795" alt="Screenshot 2023-10-15 at 21 12 55" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/b91f348c-0287-434d-bca8-6cd13c93f0e8">

fixed with a single file change

**Comment by obriensystems** [comment]
Applying log sink on prod project to start - with a target of existing bucket - will switch to pubsub
<img width="1794" alt="Screenshot 2023-10-15 at 21 52 02" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/0237d340-2ef3-4fff-a4e0-12c015cd4451">
<img width="1316" alt="Screenshot 2023-10-15 at 21 52 34" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/d39b538a-427b-47c1-80d6-7ea9bb9730a7">
preview logs from the router pane

<img width="1792" alt="Screenshot 2023-10-15 at 21 57 50" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/9cc224b5-032c-4c5c-8073-ef2ce7c1fec8">


```

Step #3 - "tf plan": Terraform will perform the following actions:
Step #3 - "tf plan": 
Step #3 - "tf plan":   # module.project-level-log-sink.google_logging_project_sink.my-sink will be created
Step #3 - "tf plan":   + resource "google_logging_project_sink" "my-sink" {
Step #3 - "tf plan":       + destination            = "logging.googleapis.com/projects/tzpe-tlz-audittlz-tlz/locations/northamerica-northeast1/buckets/20231015tlz"
Step #3 - "tf plan":       + filter                 = "resource.type = gce_instance AND severity >= INFO"
Step #3 - "tf plan":       + id                     = (known after apply)
Step #3 - "tf plan":       + name                   = "20231015-sink"
Step #3 - "tf plan":       + project                = "tzpe-tlz-tlzprod-host4"
Step #3 - "tf plan":       + unique_writer_identity = true
Step #3 - "tf plan":       + writer_identity        = (known after apply)
Step #3 - "tf plan": 
Step #3 - "tf plan":       + bigquery_options {
Step #3 - "tf plan":           + use_partitioned_tables = (known after apply)
Step #3 - "tf plan":         }
Step #3 - "tf plan":     }
Step #3 - "tf plan": 
Step #3 - "tf plan":   # module.service_accounts.data.template_file.keys["sa"] will be read during apply
Step #3 - "tf plan":   # (config refers to values not yet known)
Step #3 - "tf plan":  <= data "template_file" "keys"  {
Step #3 - "tf plan":       ~ id       = "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855" -> (known after apply)
Step #3 - "tf plan":       + rendered = (known after apply)
Step #3 - "tf plan":         # (2 unchanged attributes hidden)
Step #3 - "tf plan":     }
Step #3 - "tf plan": 
Step #3 - "tf plan":   # module.net-host-prj.module.project.google_project.project will be updated in-place
Step #3 - "tf plan":   ~ resource "google_project" "project" {
Step #3 - "tf plan":         id                  = "projects/tzpe-tlz-tlzprod-host4"
Step #3 - "tf plan":       ~ labels              = {
Step #3 - "tf plan":           - "date_modified" = "2023-10-16"
Step #3 - "tf plan":         } -> (known after apply)
Step #3 - "tf plan":         name                = "TzPe-tlz-tlzprod-host4"
Step #3 - "tf plan":         # (5 unchanged attributes hidden)
Step #3 - "tf plan":     }
Step #3 - "tf plan": 
Step #3 - "tf plan":   # module.net-host-prj.module.network["tlzprod-svpc"].module.subnets["prsubnet02"].google_compute_subnetwork.subnetwork will be updated in-place
Step #3 - "tf plan":   ~ resource "google_compute_subnetwork" "subnetwork" {
Step #3 - "tf plan":         id                         = "projects/tzpe-tlz-tlzprod-host4/regions/northamerica-northeast1/subnetworks/tzpecnr-prsubnet02-host4-snet"
Step #3 - "tf plan":         name                       = "tzpecnr-prsubnet02-host4-snet"
Step #3 - "tf plan":         # (13 unchanged attributes hidden)
Step #3 - "tf plan": 
Step #3 - "tf plan":       ~ log_config {
Step #3 - "tf plan":           - metadata             = "EXCLUDE_ALL_METADATA" -> null
Step #3 - "tf plan":             # (4 unchanged attributes hidden)
Step #3 - "tf plan":         }
Step #3 - "tf plan":     }
Step #3 - "tf plan": 
Step #3 - "tf plan": Plan: 1 to add, 2 to change, 0 to destroy.


module.service_accounts.data.template_file.keys["sa"]: Read complete after 0s [id=e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855]
module.net-host-prj.module.network["tlzprod-svpc"].module.subnets["prsubnet02"].google_compute_subnetwork.subnetwork: Modifying... [id=projects/tzpe-tlz-tlzprod-host4/regions/northamerica-northeast1/subnetworks/tzpecnr-prsubnet02-host4-snet]
module.net-host-prj.module.network["tlzprod-svpc"].module.subnets["prsubnet02"].google_compute_subnetwork.subnetwork: Modifications complete after 1s [id=projects/tzpe-tlz-tlzprod-host4/regions/northamerica-northeast1/subnetworks/tzpecnr-prsubnet02-host4-snet]
module.project-level-log-sink.google_logging_project_sink.my-sink: Creating...
module.project-level-log-sink.google_logging_project_sink.my-sink: Creation complete after 2s [id=projects/tzpe-tlz-tlzprod-host4/sinks/20231015-sink]
```

fixed hardcoded audit project - to pick up prod shared VPC project, removed gce specific log filter, moved bucket to prod from audit. Pending is code to create the bucket

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/storage_bucket

<img width="1036" alt="Screenshot 2023-10-15 at 22 20 43" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/e113cd29-045f-4e6a-84e1-23eba5002c38">



we can target splunk
<img width="576" alt="Screenshot 2023-10-15 at 21 58 58" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/48ac3876-ab36-4fdf-b006-63f1597ce632">

**Comment by obriensystems** [comment]
Logging bucket vs cloud storage bucket
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/logging_project_bucket_config
<img width="1792" alt="Screenshot 2023-10-15 at 22 43 37" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/04bdc00e-00c0-4c0a-8ca6-776eeaf135ca">

```
resource "google_logging_project_bucket_config" "prod-log-sink-bucket" {
    project          = var.project_id
    location         = var.region1
    retention_days   = 30
    #enable_analytics = true # N/A yet
    bucket_id        = var.bucket_name
}

Step #4 - "tf apply": module.project-level-log-sink.google_logging_project_bucket_config.analytics-enabled-bucket: Creating...
Step #4 - "tf apply": module.project-level-log-sink.google_logging_project_bucket_config.analytics-enabled-bucket: Creation complete after 1s [id=projects/tzpe-tlz-tlzprod-host4/locations/northamerica-northeast1/buckets/20231015-prod-sink]
```


redeploying with renamed sinks, buckets
Note: log storage bucket does not get removed - if the variable name is also changed
https://console.cloud.google.com/logs/storage?project=tzpe-tlz-tlzprod-host4&supportedpurview=project

**Comment by obriensystems** [comment]
Create GCS bucket for 2nd GCS log sink destination - remove filter
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/storage_bucket

<img width="1775" alt="Screenshot 2023-10-15 at 23 35 38" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/7ce09975-ccdd-4295-8477-5877e84ca16b">
<img width="1792" alt="Screenshot 2023-10-15 at 23 36 06" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/0960638e-4e41-49f6-bea5-57fb0197637f">
<img width="1787" alt="Screenshot 2023-10-15 at 23 36 29" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/369b7682-dc20-40fa-a638-a20933092433">

logs take up to an hour to show - do some VM start/stop to generate logs first
<img width="1797" alt="Screenshot 2023-10-15 at 23 38 12" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/f6bacac7-2724-402c-8eac-3d43e6fd3f13">

<img width="756" alt="Screenshot 2023-10-15 at 23 37 32" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/7b415592-85a5-47e2-841c-6eb98756dcb2">

preview logs
<img width="1790" alt="Screenshot 2023-10-15 at 23 39 04" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/09c02058-2332-411f-939a-8acfd84f509d">

**Comment by obriensystems** [comment]
PR 1 of 2-3
```
root_@cloudshell:~/lz-tls/_lz2/_upsource/pbmm-on-gcp-onboarding (lz-tls)$ git status
On branch 318-log-sink-alerting
Your branch is up to date with 'origin/318-log-sink-alerting'.

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        modified:   environments/prod/main.tf
        new file:   environments/prod/prod-logging.auto.tfvars
        modified:   environments/prod/variables.tf
        new file:   modules/23-logging/main.tf
        new file:   modules/23-logging/outputs.tf
        new file:   modules/23-logging/variables.tf
        new file:   modules/24-gcs-bucket/main.tf
        new file:   modules/24-gcs-bucket/outputs.tf
        new file:   modules/24-gcs-bucket/variables.tf
        ```

**Comment by obriensystems** [comment]
Review KCC version of our logging project and it's sinks
https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit/blob/main/solutions/client-landing-zone/logging-project/cloud-logging-bucket.yaml

<img width="1922" alt="Screenshot 2023-10-16 at 10 21 40" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/c859b318-4a72-4eb1-96ac-973b73c63f86">

**Comment by obriensystems** [comment]
## Revisit requirements and dev environment
- https://cloud.google.com/logging/docs/export/configure_export_v2
- https://cloud.google.com/assured-workloads/docs/eu-sovereign-controls-restrictions-limitations

## folder level logs experimentation using gcloud instead of terraform for throughput

**Comment by obriensystems** [comment]
storage bucket and logging bucket created for 2 routers in bigquery-ol at the org scope 
20231106:1630 
<img width="1469" alt="Screenshot 2023-11-06 at 16 43 57" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/3836c6f5-204e-4209-a494-0f8101c4fbc0">

**Comment by obriensystems** [comment]
Reviewing the results of https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/pull/333/files#diff-2f2b3d2889b990647e43f24f860b0d08898940ea273d175ae257fed4339431f7

Noticed that the GCS sink is routing to a log router instead of a GCS storage bucket - hence why log storage is filled but the GCS bucket is not

log router
<img width="1760" alt="Screenshot 2023-11-07 at 08 26 52" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/e1edbe4a-36a8-4856-a440-a22b58f48f85">
prod-log-sink
<img width="1775" alt="Screenshot 2023-11-07 at 08 27 22" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/5b7dec5c-5c54-4f8a-b35c-225bdff19b84">



prod-log-gcs-sink
<img width="1782" alt="Screenshot 2023-11-07 at 08 27 40" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/4c612031-a056-47c8-baf8-7b3af20ba50f">

log storage
<img width="1769" alt="Screenshot 2023-11-07 at 08 28 05" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/e5cd74c5-8233-4536-8ddb-cdcd7f63b9c1">

prod-sink-gcs
<img width="1782" alt="Screenshot 2023-11-07 at 08 29 13" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/4a408827-a374-4ba1-a64a-d913ae23b212">


triage switch 
```
gcs_bucket_name = "20231015-prod-sink-gcs"

resource "google_logging_project_sink" "prod-log-sink-to-gcs-bucket" {
  name = var.gcs_sink_name
  project = var.project_id

  # Can export to pubsub, cloud storage, bigquery, log bucket, or another project
  #destination = "pubsub.googleapis.com/projects/my-project/topics/instance-activity"
  #destination = "logging.googleapis.com/projects/${var.project_id}/locations/${var.region1}/buckets/${var.gcs_bucket_name}"
  destination = "storage.googleapis.com/${var.gcs_bucket_name}" 



resource "google_logging_project_sink" "prod-log-sink-to-log-bucket" {
  name = var.log_sink_name
  project = var.project_id

  # Can export to pubsub, cloud storage, bigquery, log bucket, or another project
  #destination = "pubsub.googleapis.com/projects/my-project/topics/instance-activity"
  destination = "logging.googleapis.com/projects/${var.project_id}/locations/${var.region1}/buckets/${var.log_bucket_name}"

  #destination = "storage.googleapis.com/[GCS_BUCKET]"
  #destination = "bigquery.googleapis.com/projects/[PROJECT_ID]/datasets/[DATASET]"
  #destination = "pubsub.googleapis.com/projects/[PROJECT_ID]/topics/[TOPIC_ID]"
  #destination = "logging.googleapis.com/projects/[PROJECT_ID]/locations/global/buckets/[BUCKET_ID]"
  #destination = "logging.googleapis.com/projects/[PROJECT_ID]"

  # Example: Log all WARN or higher severity messages relating to instances
  #filter = "resource.type = gce_instance AND severity >= INFO"
  # filter only by log severity - remember filter is optional
  filter = "severity >= INFO"

  # Use a unique writer (creates a unique service account used for writing)
  unique_writer_identity = true
}

and turn off filter
```

**Comment by obriensystems** [comment]
Check existing config flag set to true
before we swap in the service account - see if it kicks in the default sa
around
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/logging_project_sink
```
  # Use a unique writer (creates a unique service account used for writing)
  unique_writer_identity = true
```

change
```
root_@cloudshell:~/lz-tls/_lz2/pbmm-on-gcp-onboarding (lz-tls)$ git diff
diff --git a/modules/23-logging/main.tf b/modules/23-logging/main.tf
index 943f4b0..8472e25 100644
--- a/modules/23-logging/main.tf
+++ b/modules/23-logging/main.tf
@@ -69,7 +69,7 @@ resource "google_logging_project_sink" "prod-log-sink-to-gcs-bucket" {
   #filter = "severity >= INFO"
 
   # Use a unique writer (creates a unique service account used for writing)
-  unique_writer_identity = true
+  #unique_writer_identity = true
```

**Comment by fmichaelobrien** [comment]
drive/shadow to https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit/issues/651

**Comment by fmichaelobrien** [comment]
20240406: Closing issue during retrofit/rebase of this TEF V1 based/modified repo to TEF V4 standards
This issue may participate in the LZ refactor after rebase
Query on all issues related to the older V1 version via the tag
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/labels/2024-pre-tef-v4
