### ISSUE TITLE
Add automated security controls validation via cloud asset inventory API call or CSV extract

### ISSUE THREAD

**Issue by fmichaelobrien** [GoogleCloudPlatform/pbmm-on-gcp-onboarding#32]
see
https://console.cloud.google.com/iam-admin/asset-inventory/resources?project=ospe-obs-obsdev-np&pageState=(%22projectFacets%22:(%22f%22:%22projects%2F491293490833,projects%2F1094360923192%22))

verify existing handles drift, on the fly validation, reporting

<img width="909" alt="Screen Shot 2022-03-24 at 12 31 20 PM" src="https://user-images.githubusercontent.com/94715080/159964831-17bea533-dba0-4543-9376-a79dbd491d66.png">
<img width="1144" alt="Screen Shot 2022-03-24 at 12 31 44 PM" src="https://user-images.githubusercontent.com/94715080/159964911-7301f6f2-939c-41a4-9e1b-29feb1737707.png">

<img width="1569" alt="Screen Shot 2022-03-24 at 2 14 36 PM" src="https://user-images.githubusercontent.com/94715080/159983680-75940566-df4e-4b56-8702-c30c71c71f9d.png">
<img width="1576" alt="Screen Shot 2022-03-24 at 2 15 04 PM" src="https://user-images.githubusercontent.com/94715080/159983695-17eabfdb-0d4e-43a0-8848-b2c4051b5dff.png">

**Comment by obriensystems** [comment]
20240406: Closing issue during retrofit/rebase of this TEF V1 based/modified repo to TEF V4 standards
This issue may participate in the LZ refactor after rebase
Query on all issues related to the older V1 version via the tag
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/labels/2024-pre-tef-v4
