### ISSUE TITLE
Day 0: Pre-Release Terraform Landing Zone install with Yoppworks additions  - procedure verify and re-documentation

### ISSUE THREAD

**Issue by obriensystems** [GoogleCloudPlatform/pbmm-on-gcp-onboarding#320]
re-procedure from https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/issues/300
Combination of 3B1 and 1

Follow and edit https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/blob/main/docs/google-cloud-onboarding.md#onboarding-category-1-workspace-account---domain-hosted-on-google-domains

Follow and edit https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/blob/main/docs/google-cloud-onboarding.md#onboarding-category-3b1-3rd-party-email-account---3rd-party-aws-route53-domain-validation---reuse-existing-billing-account

Create 1b: Workspace, domain on 3rd party
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/blob/main/docs/google-cloud-onboarding.md#onboarding-category-1b-workspace-account---domain-hosted-by-3rd-party

## Requirements
- workspace business standard account (for emails without forwarding) - combination of 3
- Billing Account Administrator, Organization Administrator - single account for now

## Use existing domain for new GCP account
Google Domains has moved to Squarespace - therefore use Route53 for now obr*.indust*

<img width="1363" alt="Screenshot 2023-09-26 at 11 30 05" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/3b498712-3909-4001-9dda-d1727da6cb78">

## Start GCP
not https://workspace.google.com/signup/gcpidentity/welcome#0
use https://workspace.google.com/business/signup/welcome

Use incognito window
<img width="1261" alt="Screenshot 2023-09-26 at 11 38 54" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/96a7d051-41f8-4aac-b067-2adaf93dbf3b">

business account name
<img width="1258" alt="Screenshot 2023-09-26 at 11 39 29" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/126f224e-6a3a-4222-8d94-a616cdcc2c37">

Add name + current email
Yes I have a domain
<img width="1260" alt="Screenshot 2023-09-26 at 11 42 55" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/1d6bbf29-562a-4241-bb18-dc8f6016d5e7">

<img width="1267" alt="Screenshot 2023-09-26 at 11 43 26" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/91dc32a3-8fdc-45f6-918c-4b38be343b45">

<img width="1256" alt="Screenshot 2023-09-26 at 11 43 48" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/fbdb1c1f-e194-4e26-bb1d-b503e6c77112">

How you will sign in
<img width="1263" alt="Screenshot 2023-09-26 at 11 44 28" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/45092765-1144-4c23-8ab6-d6ae3a899462">

default to business standard (will allow for Duet-AI)
<img width="1258" alt="Screenshot 2023-09-26 at 11 45 04" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/cfedc69f-ee9f-4d27-b817-4b42a8013e3f">

billing for workspace first before gcp
<img width="1267" alt="Screenshot 2023-09-26 at 11 45 43" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/9b44dbb5-715f-41a9-804a-7b85e6f30d58">

new account (setup mx records later)
<img width="1250" alt="Screenshot 2023-09-26 at 11 46 56" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/d0b16052-7d7e-412d-8988-50775bce2c2a">

admin account
<img width="1265" alt="Screenshot 2023-09-26 at 11 47 32" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/af559990-047c-4d88-b4a1-bfe7d2238a17">

Activate gmail 
<img width="1261" alt="Screenshot 2023-09-26 at 11 48 04" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/cb22a60c-6eb9-4fce-ba11-4e014520bf2e">

set route53 dns
<img width="1246" alt="Screenshot 2023-09-26 at 11 48 52" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/e9867378-b85e-4179-a376-0368f5d88
cd6">

<img width="1238" alt="Screenshot 2023-09-26 at 11 49 51" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/057a5dc9-fe69-4a16-b4ff-0f4e6b5827f5">

on route53

<img width="1367" alt="Screenshot 2023-09-26 at 11 52 19" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/2797d48d-ebbc-4b67-b918-a309aff253f1">

<img width="1368" alt="Screenshot 2023-09-26 at 11 53 38" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/cb13a10b-a59e-4b8b-9090-c30d416e09ed">

<img width="1363" alt="Screenshot 2023-09-26 at 11 54 01" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/9211e92a-4c09-4e13-84b1-ffc419e8e100">

<img width="1250" alt="Screenshot 2023-09-26 at 11 54 26" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/17242447-4eaa-4a4b-9cb3-4da0794c8849">

remove @
<img width="1360" alt="Screenshot 2023-09-26 at 11 55 32" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/9bb7c9b1-6acf-44ac-a1e6-ef98349c027d">

retry
<img width="1231" alt="Screenshot 2023-09-26 at 11 56 26" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/bba5e4c5-f79c-4a86-a7f1-6b7197db553f">

2 min OK
<img width="1249" alt="Screenshot 2023-09-26 at 11 57 15" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/7b072a44-287d-4e80-8672-79ee86d4c9b0">

skip new users for now
<img width="1251" alt="Screenshot 2023-09-26 at 11 57 41" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/26f55a87-1a0b-4400-98b5-8d8de5bfc5b8">

<img width="1259" alt="Screenshot 2023-09-26 at 11 58 10" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/ab6c078c-8760-477d-b700-dc87f081c124">

## Start a new Chrome profile
<img width="1029" alt="Screenshot 2023-09-26 at 12 50 58" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/b9293283-e143-46f6-bcdc-1429d745a3ce">
<img width="1017" alt="Screenshot 2023-09-26 at 12 51 22" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/0d81dba5-c901-47d4-97e1-43d517357e71">

<img width="1300" alt="Screenshot 2023-09-26 at 12 52 12" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/e142152a-00b6-46b3-9842-3dfe5d7d0bc0">

## launch cloud.google.com
![image](https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/dac82a3f-992d-4c06-ad7f-8dbd92147ffd)

![image](https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/c8b7955d-3251-463a-9c02-f8040f30bb00)

accept credits
![image](https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/561c61c7-6213-4d58-ab8d-c5855fe003f3)

setup billing

![image](https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/7cfbc39d-7bb5-4c86-b2b5-8cc810434680)

setup org
![image](https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/abcacbd3-e661-4789-b9ee-3ae1beadbff4)

prepay 50 on payment overview to enable billing quota increases

![image](https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/19c356fd-3588-4c15-b1cc-1395c17ef678)

## accept free trial - enable full account
<img width="1302" alt="Screenshot 2023-09-27 at 08 48 23" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/38a1f24d-1e28-4258-9fa3-e74a7c8d1c0d">

<img width="1308" alt="Screenshot 2023-09-27 at 08 48 44" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/59225019-58cf-49f1-a7f6-08de08133a27">

<img width="1307" alt="Screenshot 2023-09-27 at 08 49 08" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/1d68330a-9693-4721-a041-5cd0a76834c3">

**Comment by fmichaelobrien** [comment]
20240406: Closing issue during retrofit/rebase of this TEF V1 based/modified repo to TEF V4 standards
This issue may participate in the LZ refactor after rebase
Query on all issues related to the older V1 version via the tag
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/labels/2024-pre-tef-v4
