### ISSUE TITLE
Request project:billing account quota increase for cloud identity based organizations from 5 to 10+

### ISSUE THREAD

**Issue by fmichaelobrien** [GoogleCloudPlatform/pbmm-on-gcp-onboarding#33]
# This deployment will add 5 projects to your organization - you will need at least a quota of 6 for project:billing association
Since an additional project is needed to bootstrap the landingzone - 6 projects will be required.
It would be better to ask for this quota increase before running the deployment as you will run into a quota restriction on the last prod project.

# procedure
https://support.google.com/cloud/answer/6330231
The key is to ask for "paid" services and a minimal increase - usually double 5-10 in increments - these will come in under 3 min

## directly
https://support.google.com/code/contact/billing_quota_increase

## via billing console before running deployment - recommended

navigate to https://console.cloud.google.com/billing

select your organization

if there are more than 5 projects - select one that does not have billing associated (actions on right) - change billing

...writing...

## during deployment

You may run into either the console level or the api level error

## console level error
<img width="1348" alt="Screen Shot 2022-03-25 at 10 17 19 AM" src="https://user-images.githubusercontent.com/94715080/160138087-f48cbe7d-1e19-4af2-819b-f8451a437fc5.png">

<img width="844" alt="Screen Shot 2022-03-25 at 10 17 34 AM" src="https://user-images.githubusercontent.com/94715080/160138138-3f938b83-ca14-4870-a6f8-439f0759dfb5.png">

<img width="196" alt="Screen Shot 2022-03-25 at 10 17 43 AM" src="https://user-images.githubusercontent.com/94715080/160138172-9d2ae8e5-0ce8-4809-9c4e-969a1872b622.png">

<img width="541" alt="Screen Shot 2022-03-25 at 10 27 50 AM" src="https://user-images.githubusercontent.com/94715080/160140127-b2b824b8-c23a-475c-b9e1-0553e9f0c5a6.png">

<img width="542" alt="Screen Shot 2022-03-25 at 10 08 37 AM" src="https://user-images.githubusercontent.com/94715080/160136570-0a67f785-b529-4322-b6bc-648bce9dd861.png">

<img width="1527" alt="Screen Shot 2022-03-25 at 10 11 37 AM" src="https://user-images.githubusercontent.com/94715080/160137104-ef5b24ef-ea5f-432f-b980-7e273d6482f7.png">

<img width="1528" alt="Screen Shot 2022-03-25 at 10 39 54 AM" src="https://user-images.githubusercontent.com/94715080/160142388-1eb54dad-47cb-4016-99eb-e83851400323.png">

# result for console manual process

request - duration will be within 1-3 min if via AI (it could take 2-3 days if a review is required - but usually is approved on the order of minutes)
<img width="960" alt="Screen Shot 2022-03-25 at 9 43 25 AM" src="https://user-images.githubusercontent.com/94715080/160132169-aafc91c9-d29c-4fad-88a4-ebb8d4fe2a37.png">
<img width="546" alt="Screen Shot 2022-03-25 at 10 54 56 AM" src="https://user-images.githubusercontent.com/94715080/160145297-fb785527-6b0e-47ab-b2c8-a33cf0764b89.png">
<img width="1005" alt="Screen Shot 2022-03-25 at 10 55 07 AM" src="https://user-images.githubusercontent.com/94715080/160145315-cd783b2a-632c-4a76-9d48-9e182e0aacf0.png">

# result from CLI request

**Comment by obriensystems** [comment]
20240406: Closing issue during retrofit/rebase of this TEF V1 based/modified repo to TEF V4 standards
This issue may participate in the LZ refactor after rebase
Query on all issues related to the older V1 version via the tag
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/labels/2024-pre-tef-v4
