### ISSUE TITLE
Audit labels variable override has no effect because of labels/lables spelling mismatch

### ISSUE THREAD

**Issue by obriensystems** [GoogleCloudPlatform/pbmm-on-gcp-onboarding#343]
Check prod as well for no effect - currently triaging around dns.tf override

occurs in branches
- main
- subbranches off 341

s part of #341 
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/blob/main/environments/common/main.tf#L43
labels                         = var.audit.audit_labels
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/blob/main/environments/common/common.auto.tfvars#L80
audit_lables = {}
```
main.tf reference
  labels                         = var.audit.audit_labels
common.auto.tfvars
  audit_lables = {
```

**Comment by fmichaelobrien** [comment]
The same for audit

<img width="989" alt="Screenshot 2023-12-04 at 13 09 20" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/a650d0b4-aa88-4b8b-bd96-aab918a6cd6a">

```
  #labels                         = var.audit.audit_labels
  labels = {
        date_modified = "202310" # overriden
     business_contact = "michaelo"
  }
```

**Comment by fmichaelobrien** [comment]
20240406: Closing issue during retrofit/rebase of this TEF V1 based/modified repo to TEF V4 standards
This issue may participate in the LZ refactor after rebase
Query on all issues related to the older V1 version via the tag
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/labels/2024-pre-tef-v4
