### ISSUE TITLE
Enable Network Analysis : Connectivity Tests - for VMs - off network interfaced details in GCE

### ISSUE THREAD

**Issue by obriensystems** [GoogleCloudPlatform/pbmm-on-gcp-onboarding#349]
shadow https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit/issues/873
off network interface details in GCE

<img width="1401" alt="Screenshot 2024-03-03 at 10 40 31" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/e4cd91e0-f226-4fb1-b9d5-22ace9f4b691">

<img width="1409" alt="Screenshot 2024-03-03 at 10 40 10" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/9ab1162c-b406-4594-bec9-aff5ddbcb059">

gcloud tests ok
<img width="1153" alt="Screenshot 2024-03-03 at 10 38 45" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/45bf30bb-e07c-4647-a65f-aa4a12660721">
<img width="496" alt="Screenshot 2024-03-03 at 10 41 05" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/aad6ae40-695f-4123-9d29-7026a3946dd2">

<img width="1411" alt="Screenshot 2024-03-03 at 10 43 37" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/32ce56aa-8f47-4acb-92fe-f1970776d646">

terraform does not
<img width="1175" alt="Screenshot 2024-03-03 at 10 41 34" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/18acac54-3cb2-42a4-99e4-206d4e395433">

<img width="1432" alt="Screenshot 2024-03-03 at 10 44 27" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/13b14d4a-1f67-47a9-becc-a38d6b43a019">

issue for TF is the ingress FW rule
<img width="1439" alt="Screenshot 2024-03-03 at 10 49 57" src="https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit/assets/24765473/87fe31ba-9953-4eaa-ab26-adc554fdfc78">

**Comment by obriensystems** [comment]
Issue is no external load balancer in terraform like there is in gcloud

<img width="1443" alt="Screenshot 2024-03-03 at 17 44 55" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/8bab62f4-3830-4cc2-80b8-f2f6188dc233">

**Comment by obriensystems** [comment]
issue was fortigate incoming allow on /32 address did not handle IPV6 - not the firewall rule allow which was already 0.0.0.0/0

In some clients - "what is my ip" will return an IPV6 address instead of a IPV4 address
The fix for this is to ignore the lookup of your /32 ip and just open it to 0.0.0.0/0
without the fix  - we hang on admin access

# change
in 
https://github.com/fortinet/fortigate-tutorial-gcp/blob/main/terraform/day0/main.tf#L9
```
 data "http" "my_ip" {
   url             = "http://api.ipify.org"
 }
 
 # Create base deployment of FortiGate HA cluster
@@ -16,8 +17,10 @@ module "fortigates" {
   region          = var.GCE_REGION
   service_account = data.google_service_account.fgt.email != null ? data.google_service_account.fgt.email : ""
-  admin_acl       = ["${data.http.my_ip.body}/32"]
-  api_acl         = ["${data.http.my_ip.body}/32"]
+ # admin_acl       = ["${data.http.my_ip.body}/32"]
+  admin_acl       = ["0.0.0.0/0"]
+ # api_acl         = ["${data.http.my_ip.body}/32"]
+  api_acl         = ["0.0.0.0/0"]
```

<img width="1364" alt="Screenshot 2024-03-03 at 19 07 18" src="https://github.com/fortinet/fortigate-tutorial-gcp/assets/24765473/e1f7453d-eb98-4c7c-ac4f-12030fcde043">

**Comment by fmichaelobrien** [comment]
20240406: Closing issue during retrofit/rebase of this TEF V1 based/modified repo to TEF V4 standards
This issue may participate in the LZ refactor after rebase
Query on all issues related to the older V1 version via the tag
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/labels/2024-pre-tef-v4
