### ISSUE TITLE
Introduce 2024 light - a secondary Landing Zone based on the GCP Enterprise Setup with Fortigate IaaS NGFW overlay - both in terraform

### ISSUE THREAD

**Issue by fmichaelobrien** [GoogleCloudPlatform/pbmm-on-gcp-onboarding#351]
20240402 TEF work not in https://github.com/terraform-google-modules/terraform-example-foundation/issues/1133
20240206 #345 superceeds this one
**Historical**
Follow previous cloud-setup investigation runs at
- TOC alignment July 2023 - all the way to the end including policies
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/issues/251
and from May 2023
https://github.com/CloudLandingZone/google-cloud-enterprise-setup-checklist/issues/1

**Artifacts**
- org (olapp)
- branch (https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/tree/351-landing-zone-fortigate-cloud-setup)
- wiki https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/wiki/Architecture
- repo folder: 2024_fortigate-on-cloud-setup

**Requirements:**
We have a a required for a light landing zone

The enterprise setup is a Google supported LZ
The fortigate TF overlay is a Fortinet supported example

1 - use the foundations setup
https://github.com/CloudLandingZone/google-cloud-enterprise-setup-checklist
Describing
https://cloud.google.com/docs/enterprise/setup-checklist 
2 - overlay the working unmodified fortigate cluster (reattach peering to the setup above…)
https://github.com/fortinet/fortigate-tutorial-gcp/tree/main/terraform 

### Base Landing Zone
<img width="927" alt="Screenshot 2024-03-04 at 12 48 02 PM" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/94715080/99347ced-47fa-4332-9067-174e696458dd">

### Merged with Fortigate LB sandwich cluster - re-peer with above

<img width="1140" alt="Screenshot 2024-03-04 at 12 47 18 PM" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/94715080/cc3ebaba-42c6-4bdb-9fba-204ec8f84e03">

This superseeds #345 
20240206 #345 superceeds this one

**Comment by obriensystems** [comment]
Start foundation setup on a relatively new org - one where no terraform or kcc config controller lz has been deployed yet

## Output Artifacts
- manual console procedures + terraform scripts from cloud-setup + terraform from Fortinet (adjusted)
- Try to get a gcloud script done for the manual procedures

# 1 - Create an Organization
- get project quota increased - done
<img width="1448" alt="Screenshot 2024-03-04 at 14 27 32" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/858ae826-87ee-459c-a374-e9f36298d9a3">

# 2 - Configure Users and Groups
- partial
# 3 - Assign Administrative access
- done

# 4 - setup billing
- done

**Comment by obriensystems** [comment]
Buglist
2 - users and groups
- BAA or BAU must be applied to SA in IAM (not just the billing page) or the following 2 groups will fail to create
missing 
gcp-logging-viewers@obrienlabs.app
gcp-billing-admins@obrienlabs.app
before
<img width="1395" alt="Screenshot 2024-03-05 at 11 33 29" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/38f53639-de5f-425a-8c40-200b50ceac2c">
add Billing Admin and Project Billing Manager
<img width="763" alt="Screenshot 2024-03-05 at 11 34 56" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/b980af40-1d13-4a73-b9b4-d22eb1ee0381">
to
<img width="1400" alt="Screenshot 2024-03-05 at 11 35 28" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/eee71efb-c338-429b-a760-b81453a52a39">
fixing
<img width="1423" alt="Screenshot 2024-03-05 at 11 37 50" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/524c0cac-207c-4567-bea8-d53275dca475">
<img width="1423" alt="Screenshot 2024-03-05 at 11 38 09" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/ff6e812b-e912-4901-b05b-4cf853acc409">
