### ISSUE TITLE
Remove company reference in readme

### ISSUE THREAD

**Issue by stephen-sourced** [GoogleCloudPlatform/pbmm-on-gcp-onboarding#37]
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/blob/main/modules/virtual-machine/README.md

**Comment by fmichaelobrien** [comment]
Nice catch - Thanks for that.  If you would like your PR merged, the following site is where you will be able to sign the CLA.  We welcome your patch.
https://cla.developers.google.com/

**Comment by fmichaelobrien** [comment]
#36 
in https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/pull/36
