### ISSUE TITLE
Multi-tenant shared org for developers - verify multiple deployments per org off folders - see create_unique_tag_key

### ISSUE THREAD

**Issue by obriensystems** [GoogleCloudPlatform/pbmm-on-gcp-onboarding#371]
There are customer use cases where multiple developers are deploying the TEF in a single org - hence avoid org level collisions.
see
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/blob/main/1-org/envs/shared/terraform.example.tfvars#L40

**Comment by fmichaelobrien** [comment]
two use cases (clean GCP org is shared)
- UC1: 2 devs running full LZs on the same org (no delete of one)
- UC2: 1 dev rerunning a 2nd LZ on a re-used org (where the last LZ was ideally fully removed via terraform destroy - but has some left over gcloud artifacts or undeleted tf artifacts like groups.
