### ISSUE TITLE
ER: upgrade terraform 1.3.0 to later 1.6 to allow for PBR policy based routing - workaround is to gcloud the api

### ISSUE THREAD

**Issue by obriensystems** [GoogleCloudPlatform/pbmm-on-gcp-onboarding#373]
Check 1.7.x before a later 1.7 (Oct 2023 build)

shadow https://github.com/terraform-google-modules/terraform-example-foundation/issues/1141
https://github.com/terraform-google-modules/terraform-example-foundation/issues/1183

Start with gcloud version in https://cloud.google.com/vpc/docs/use-policy-based-routes#gcloud
and https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/network_connectivity_policy_based_route

### TL;DR

check at least 1.5.4
see 

The version of terraform run internally has issues with lack of support for later APIs 
https://github.com/terraform-google-modules/terraform-example-foundation/blob/master/0-bootstrap/Dockerfile#L18
```
ARG TERRAFORM_VERSION=1.3.0
```

We need support for PBR - Policy Based Routing

check 1.6.x for inclusion of https://github.com/GoogleCloudPlatform/magic-modules/pull/9320 late october 2023
https://releases.hashicorp.com/terraform/

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/network_connectivity_policy_based_route

https://cloud.google.com/network-connectivity/docs/reference/networkconnectivity/rest/v1/projects.locations.global.policyBasedRoutes
https://cloud.google.com/vpc/docs/use-policy-based-routes#api
https://github.com/hashicorp/terraform-provider-google/issues/15414
https://github.com/GoogleCloudPlatform/magic-modules/pull/9320
https://github.com/terraform-google-modules/docs-examples/pull/579
https://cloud.google.com/vpc/docs/use-policy-based-routes#create-within-vpc

without PBR we dont have PBMM microsegmentation
https://github.com/terraform-google-modules/terraform-example-foundation/blob/master/0-bootstrap/Dockerfile#L18
https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit/issues/854
https://cloud.google.com/vpc/docs/policy-based-routes
https://medium.com/google-cloud/why-policy-based-routing-is-a-game-changer-f4c6a7badccb
https://codelabs.developers.google.com/codelabs/cloudnet-pbr#0
https://cloud.google.com/vpc/docs/use-policy-based-routes#create-within-vpc
During the upgrade check for instances of OPTIONAL

References
https://github.com/hashicorp/terraform-provider-google/issues/16217#issuecomment-1984213522

**Comment by fmichaelobrien** [comment]
see
- https://github.com/terraform-google-modules/terraform-google-network/tree/master/modules/network-firewall-policy
- https://github.com/hashicorp/terraform-provider-google/issues/17030

**Comment by fmichaelobrien** [comment]
b/321386368
