### ISSUE TITLE
Overlay fortigate NGFW dual LB example into 3-networks-hub-and-spoke

### ISSUE THREAD

**Issue by fmichaelobrien** [GoogleCloudPlatform/pbmm-on-gcp-onboarding#389]
20240517: assigned to Andrew
- stopped (non-VDOM) deployment in obrienlabs.app
- review VDOM hidden status from Martin - https://community.fortinet.com/t5/FortiGate/Technical-Tip-HA-Reserved-Management-Interface-s-hidden-VDOM/ta-p/214783
## Requirements
Adapt the 40net solution into the TEF
(Bartek) https://github.com/40net-cloud/fortinet-gcp-solutions/tree/master/FortiGate
https://github.com/fortinet/fortigate-terraform-deploy/tree/main/gcp/7.4
https://github.com/fortinet/fortigate-tutorial-gcp/tree/main/terraform
last run from feb
https://github.com/fortinet/fortigate-tutorial-gcp/issues/7

see example TEF deployment in #360 and https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/issues/351

see alternate GCP native NGFW / Firewall+ overlay work in https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/issues/396
- Ideally the NGFW work in 396 and 389 are pluggable and work as an option to the existing transitive VMs in the TEF
- see see https://github.com/hashicorp/terraform-provider-google/issues/17030
b/321386368

# Architecture
- https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/issues/377

<img width="1024" alt="Screenshot 2024-04-17 at 7 07 48 AM" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/94715080/f5b5ee83-722c-4889-a616-77a1e63b2ac5">

See previous analysis in
- https://github.com/fortinet/fortigate-tutorial-gcp/issues/7
- https://github.com/40net-cloud/fortinet-gcp-solutions/issues/11
- https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit/issues/873
- https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit/issues/854

## Design
Take the existing TEF V4 and adapt the Fortinet terraform example LB sandwich HA cluster below
Verified
https://github.com/fortinet/fortigate-tutorial-gcp/tree/main/terraform
Unverified
https://github.com/40net-cloud/fortinet-gcp-solutions/tree/master/FortiGate
look at the best one from Fortinet
https://github.com/fortinet/fortigate-terraform-deploy/tree/main/gcp/7.4

## Notes
- see https://github.com/GoogleCloudPlatform/terraform-example-foundation-app/blob/main/foundation-extension/3-networks-extension/README.md
- see https://docs.fortinet.com/document/fortigate-public-cloud/7.2.0/gcp-administration-guide/856600

# CLI
- https://community.fortinet.com/t5/FortiGate/Troubleshooting-Tip-Using-the-FortiOS-built-in-packet-sniffer/ta-p/194222
- https://help.fortinet.com/fdb/5-1-13/olh/Content/FortiDB/User%20Guide/using-the-command-line-interface/show/show_system_interface.htm

**Comment by eballestas** [comment]
Working on this one.

**Comment by obriensystems** [comment]
currently stopped in obrienlabs.app
![image](https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/ffbb88a4-69e5-4e38-9535-142a77504d4e)
