### ISSUE TITLE
Fix/Triage resources for loop error on regular_service_perimeter module for prod

### ISSUE THREAD

**Issue by fmichaelobrien** [GoogleCloudPlatform/pbmm-on-gcp-onboarding#40]
triaging the vpc resources module and going over git config changes - 
 https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/blob/main/modules/vpc-service-controls/modules/regular_service_perimeter/main.tf#L22

And retrofit
https://github.com/terraform-google-modules/terraform-google-vpc-service-controls/tree/master/modules/regular_service_perimeter 

```
prod_vpc_svc_ctl = {
  regular_service_perimeter = {
    regular_service_perimeter_1 = {
      perimeter_name               = "regular_service_perimeter_prod_1"
      description                  = "Regular Service Perimeter 1"
      # match to nonp-network - see OsPe-obs-obsprd-obshostproj
      resources                    = []#"ospe-obs-obsprd-obshostproj3"] #leave empty if using net host project. no empty strings.
      access_level                 = ["ospevsc_access_level_1_vsc"]
#      restricted_services          = [""]
       resources_by_numbers         = []#["250599001049"]

Step #2 - "tf plan": │ Error: Invalid for_each argument
Step #2 - "tf plan": │ 
Step #2 - "tf plan": │   on ../../modules/vpc-service-controls/modules/regular_service_perimeter/main.tf line 22, in data "google_project" "resources":
Step #2 - "tf plan": │   22:   for_each   = toset(var.resources)
Step #2 - "tf plan": │     ├────────────────
Step #2 - "tf plan": │     │ var.resources is a list of string, known only after apply
```

**Comment by fmichaelobrien** [comment]
verified commenting out for loop specific to resources
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/issues/27#issuecomment-1080727416

validate failed on
Step https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/pull/1 - "tf validate": │ Error: Reference to undeclared local value
Step https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/pull/1 - "tf validate": │
Step https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/pull/1 - "tf validate": │ on main.tf line 34, in module "vpc-svc-ctl":
Step https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/pull/1 - "tf validate": │ 34: bridge_service_perimeter = local.prod_vpc_svc_ctl.bridge_service_perimeter
Step https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/pull/1 - "tf validate": │
Step https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/pull/1 - "tf validate": │ A local value with the name "prod_vpc_svc_ctl" has not been declared.

uncommenting locals block on main.tf for prod_vpc_svc_ctl
```
diff --git a/environments/prod/locals.tf b/environments/prod/locals.tf
index c641c23..c7cf7d3 100644
--- a/environments/prod/locals.tf
+++ b/environments/prod/locals.tf
@@ -7,7 +7,7 @@
 locals {
   organization_config = data.terraform_remote_state.bootstrap.outputs.organization_config

  nonprod_vpc_svc_ctl = {
   for perim_type, svcperim in var.nonprod_vpc_svc_ctl : perim_type => {
      for prj, attrs in svcperim : prj => merge(
        {
          for attr, val in attrs : attr => val if attr != "resources"
        },
        {
#          resources = distinct(concat(attrs.resources, [module.net-host-prj.project_id]))
        }
      )
    }
  }
}
```

**Comment by obriensystems** [comment]
20240406: Closing issue during retrofit/rebase of this TEF V1 based/modified repo to TEF V4 standards
This issue may participate in the LZ refactor after rebase
Query on all issues related to the older V1 version via the tag
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/labels/2024-pre-tef-v4
