### ISSUE TITLE
Step 0-bootstrap: no outputs generated 

### ISSUE THREAD

**Issue by eballestas** [GoogleCloudPlatform/pbmm-on-gcp-onboarding#416]
when implementing the step 8 of the 0-bootstrap confguration, the outputs come back empty, because the outputs.tf file is not being activated. producing this output

```
projects gcs bucket tfstate = ╷
│ Warning: No outputs found
│ 
│ The state file either has no outputs defined, or all the defined outputs are empty. Please define an output in your configuration with the `output` keyword and run `terraform
│ refresh` for it to become available. If you are using interpolation, please verify the interpolated value is not empty. You can use the `terraform console` command to assist.
╵
```

after removing the extensions, it works.

**Comment by fmichaelobrien** [comment]
The current main branch has a partial switch to local deployment in prep of ado.  There was a pr merged without readme adjustments and without the full retrofit towards ado support - as an addition not the current removal - see 399

To bring up CB/CSR for now - use the older clean branch
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/tree/gh357-tef-v4-fork

With the addition of the 3rd PR before the disablement of CB.tf went in

https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/pull/369

This branch is essentially still a clean TEF copy with some readme, service, IAM changes before pulling out cloud build and csr.

Details on https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/tree/gh357-tef-v4-fork

**Comment by obriensystems** [comment]
main branch updated to temporarily return to CB/CSR defaulting - ready for use
See latest 3rd org testing 50 min for #421 in https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/issues/421#issuecomment-2093522430
