### ISSUE TITLE
0-bootstrap: cloudbuild output is not present on outputs.tf file

### ISSUE THREAD

**Issue by eballestas** [GoogleCloudPlatform/pbmm-on-gcp-onboarding#417]
need to add the cloudbuild output to the outputs.tf file
step 9

**Comment by eballestas** [comment]
need to add to outputs.tf

``output "cicd_project_id" {
  description = "Project where cicd pipelines live."
  value       = module.local_cicd.project_id
}
```


```
module.seed_bootstrap.google_storage_bucket_iam_member.orgadmins_state_iam[0]: Refreshing state... [id=b/bkt-prj-b-seed-tfstate-05dd/roles/storage.admin/group:admin-gcp@eballest.dev]

Changes to Outputs:
  + cicd_project_id                                   = "prj-b-cicd-local-c1bc"

You can apply this plan to save these new output values to the Terraform state, without changing any real infrastructure.
```

**Comment by fmichaelobrien** [comment]
The current main branch has a partial switch to local deployment in prep of ado.  There was a pr merged without readme adjustments and without the full retrofit towards ado support - as an addition not the current removal - see 399

To bring up CB/CSR for now - use the older clean branch
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/tree/gh357-tef-v4-fork

With the addition of the 3rd PR before the disablement of CB.tf went in

https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/pull/369

This branch is essentially still a clean TEF copy with some readme, service, IAM changes before pulling out cloud build and csr.

Details on https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/tree/gh357-tef-v4-fork

**Comment by obriensystems** [comment]
main branch updated to temporarily return to CB/CSR defaulting - ready for use
See latest 3rd org testing 50 min for #421 in https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/issues/421#issuecomment-2093522430
