### ISSUE TITLE
ITSG-33 security controls mapping for TEF V4 - for org policies

### ISSUE THREAD

**Issue by fmichaelobrien** [GoogleCloudPlatform/pbmm-on-gcp-onboarding#441]
20240524: I  will update the subtasks later today
# work items
- us as a reference - the 12 guardrails minimum 30-day security for profile 3 (details in a lower comment
- - https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/blob/main/z_2024_v020_pre_tef_v4/docs/google-cloud-security-controls.md#guardrails-evidence-package
- - https://github.com/canada-ca/cloud-guardrails/blob/master/EN/00_Applicable-Scope.md#table2-guardrail-identifiers-service-models-and-cloud-usage-profiles
- - https://github.com/canada-ca/cloud-guardrails/blob/master/EN/13_Plan-for-Continuity.md

- map existing TEF controls to KCC - as a discovery exercise only
- get security team member to drive deliverables
- work through existing 6 policies - https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/blob/main/1-org/envs/shared/org_policy.tf#L118C1-L129C2
- determine org policies missing - optionally add them to org_policy 
- worry about dev runtime folder overrides later - for now turn off policies during dev
- yhe gke policies for the gateway controller are optional https://github.com/terraform-google-modules/terraform-example-foundation/tree/master/policy-library/policies/constraints
- reference 66 contols in https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/wiki/Security-Controls - break out only org policy ones

Start with https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/wiki/Security-Controls

specifically the org policies (doc work)
- lz v2 - https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit/tree/main/solutions/core-landing-zone/org/org-policies
- tef - https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/blob/main/1-org/envs/shared/org_policy.tf#L64

# work items
- correlate the TEF org_policy with control mapping in KCC and the NIST-800-53
- SCC-p has controls - output
- http://go/91-controls see mappings
- check 

# example locationRestriction
- https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/blob/main/z_2024_v020_pre_tef_v4/docs/google-cloud-security-controls.md#6260sc-7boundary-protection
SC-7
- see https://cloud.google.com/resource-manager/docs/organization-policy/creating-managing-custom-constraints
- reference 3 part regionalization in upcoming upstream sync https://github.com/terraform-google-modules/terraform-example-foundation/pull/1181/files
# Example incident response documents
- https://cloud.google.com/blog/products/infrastructure/details-of-google-cloud-gcve-incident/?e=48754805

**Comment by obriensystems** [comment]
Discussion notes to incorporate above

We should be ok with what is already in the TEF, what is inherent in GCP already (encryption, IAM role restrictions...), what will be inherent in the client's AD identity provider (we supply what workspace does for MFA/2FA for example - the client correlates this via their AD identities as an analog IdP).
   For non-federal full ITSG-33 (PBMM/FedRAMP) will not be required but is useful.  A request for the client security team to get involved early on is useful.  but we can prepare a minimum default set of compliance documentation - starting with a wiki/readme on our end.

    I am not that concerned about the org policies, the 4 in https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/blob/main/1-org/envs/shared/org_policy.tf are a start.
    I expect we will not need custom policies - as the out of the box org policies (including the 4-6 set by GCP by default should be ok, IP related, location restriction, service account lockdown, shielded VMs...).  I don't think we will need to get into the rego that is used by KCC.  KCC is just a guide of where we could go.

     Bottom line we need at least the 30 day guardrails level of security - at profile 3.
     About interconnects - this is profile 5/6 and is workload related - it can be in phase 2

     We can start with 3 documents
     1) The guardrails evidence section of the (federal) document at
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/blob/main/z_2024_v020_pre_tef_v4/docs/google-cloud-security-controls.md#guardrails-evidence-package
     If you check the details of the GR's - they are around monitoring, alerts, VPC firewall rules/segmentation, accounts, encryption at rest/transit, the waf/armor, and the problematic marketplace restriction (2 more org policies).
     The NGFW's handle a lot of network, security for us - we just reference some evidence of traffic capture, enable/disable for east-west and north-south canary loads.

     2) The guardrails themselves (the older version has a profile page) - we make sure we have at least 1 piece of evidence for required GR 1-12.
     In the end the TEF is already mentioned as FedRAMP compliant - we know this depends on what is enabled and it is up to us to gather evidence.

https://github.com/canada-ca/cloud-guardrails/blob/master/EN/00_Applicable-Scope.md#table2-guardrail-identifiers-service-models-and-cloud-usage-profiles
     For example GR13 is new - https://github.com/canada-ca/cloud-guardrails/blob/master/EN/13_Plan-for-Continuity.md
     The evidence would be a procedure for a 2nd super admin account (the break glass) - where the MFA and password are kept locked/separate

     If any rule was a base default it would be GR5 - location https://github.com/canada-ca/cloud-guardrails/blob/master/EN/05_Data-Location.md#mandatory-requirements
     In reality we can usually get a waiver per workload - at the non-federal level - for services like NCC, or some the AI services - that do not reside in CA yet (but are in the plan) and currently need US locations overrides.  Here we mention intent, have the policy in place in the yaml - but not necessarily enable it on our test deployment.

**Comment by obriensystems** [comment]
for example, guardrails navigation for screen caps for the location restriction

- deploy/modified tf code in https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/blob/main/1-org/envs/shared/org_policy.tf#L100C41-L101C84
- navigate as reference to

- https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/blob/main/z_2024_v020_pre_tef_v4/docs/google-cloud-security-controls.md
- https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/blob/main/z_2024_v020_pre_tef_v4/docs/google-cloud-security-controls.md#guardrails-subset
- https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/blob/main/z_2024_v020_pre_tef_v4/docs/google-cloud-security-controls.md#05-data-location-1
- check list
- https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/blob/main/z_2024_v020_pre_tef_v4/docs/google-cloud-security-controls.md#05-data-location-1
- navigate to GR05
- https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/blob/main/z_2024_v020_pre_tef_v4/docs/google-cloud-security-controls.md#6260sc-7boundary-protection
- https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/blob/main/z_2024_v020_pre_tef_v4/docs/google-cloud-security-controls.md#iam---organization-policies---resource-location-restriction


- https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/blob/main/2-environments/modules/env_baseline/monitoring.tf
- runtime example of loggin https://console.cloud.google.com/logs/query;cursorTimestamp=2024-05-27T14:16:27.851800721Z;duration=PT1H?referrer=search&hl=en&orgonly=true&project=prj-d-monitoring-hwfg&supportedpurview=project
-

**Comment by obriensystems** [comment]
see #452
