### ISSUE TITLE
Fortigate configuration spec triage for GC-CAP and GC-TIP

### ISSUE THREAD

**Issue by fmichaelobrien** [GoogleCloudPlatform/pbmm-on-gcp-onboarding#45]
Reference: https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/blob/main/docs/architecture.md#di-6-landing-zone-network-topology-design
# figure out various fortigate configs

# notes
https://cloud.google.com/architecture?category=networking&text=appliance to https://cloud.google.com/architecture/deploying-nat-gateways-in-a-hub-and-spoke-architecture-using-vpc-network-peering-and-routing?hl=en
https://github.com/fortinetsolutions/terraform-modules/tree/master/GCP/examples

https://github.com/40net-cloud/fortinet-gcp-solutions/tree/master/FortiGate/architectures

https://cloud.google.com/architecture/architecture-centralized-network-appliances-on-google-cloud 

https://cloud.google.com/architecture/gcve-advanced-network-security?hl=en
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/tree/main/modules/fortigate-appliance 

# design

# questions
- see https://github.com/fortinetsolutions/terraform-modules/issues/2
-  so far around the minimum roles on the terraform service account
-

**Comment by martingiguere** [comment]
First architecture to integrate to test deployment with:
 https://github.com/fortinetsolutions/terraform-modules/tree/master/GCP/examples/ha-active-passive

**Comment by fmichaelobrien** [comment]
Config start:
- register one of your 60 day eval licenses
- in the CSR repo in your cloud shell
- copy the lic file to [modules/fortigate-appliance](https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/tree/main/modules/fortigate-appliance/files)
- copy the example tfvars https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/blob/main/config/TFvars/prod/fortigate-firewall.auto.tfvars to https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/tree/main/environments/prod

**Comment by fmichaelobrien** [comment]
# Meeting minutes:
- discuss fortigate config with original developers
2 options  (rough notes - will fill out later tonight)
- directly in environments/prod - add the fortigate config from TFvars and work out the variables section by adding a new fortigate module in main.tf (uncomment the fortigateConfig in variables.tf
- make a new 5th environment (outside of prod) just for fortigate - will need either a full cloud build/trigger infrastructure or some manual terraform plan/apply

**Comment by fmichaelobrien** [comment]
Checking my license file - I also need the VM image name - I should have it in my eval license email...getting it
```
admin_@cloudshell:~/wse_github/fortinetsolutions/terraform-modules/GCP/examples/ha-active-active (fortigate-arg)$ git diff
diff --git a/GCP/examples/ha-active-active/terraform.tfvars b/GCP/examples/ha-active-active/terraform.tfvars
index 55db49d..e83013b 100644
--- a/GCP/examples/ha-active-active/terraform.tfvars
+++ b/GCP/examples/ha-active-active/terraform.tfvars
@@ -1,11 +1,12 @@
-credentials_file_path           = "<credentials_file_path>"
-service_account                 = "<service_account_email>"
-project                         = "<project>"
+credentials_file_path           = "/home/admin_/FGVM08TM22001748.lic" # modified
+service_account                 = "terraform-fortigate-arg@fortigate-arg.iam.gserviceaccount.com" # modified
+project                         = "fortigate-arg"
 name                            = "terraform-a-a"
 region                          = "us-central1"
 zone                            = "us-central1-c"
 machine                         = "n1-standard-2"
-image                           = "<IMAGE>"
+#image                           = "<IMAGE>" # need image
+image                           = "windows-cloud/windows-2019" # verify tf for now
 bastionhost_image               = "windows-cloud/windows-2019"
 bastionhost_machine             = "n1-standard-2"
 admin_port                      = 8443


Terraform plan

│ Error: JSON credentials in "-----BEGIN FGT VM LICENSE-----\nQAA…

 VM LICENSE-----\n" are not valid: invalid character '-' in numeric literal
│
│   with provider["registry.terraform.io/hashicorp/google"],
│   on main.tf line 3, in provider "google":
│    3:   credentials = file(var.credentials_file_path)

```

**Comment by obriensystems** [comment]
Testing baseline in recent cloudnuage.dev LZ deploy
```
root_@cloudshell:~$ mkdir github
root_@cloudshell:~$ cd github/
root_@cloudshell:~/github$ git clone https://github.com/fortinetsolutions/terraform-modules.git
Cloning into 'terraform-modules'...
root_@cloudshell:~/github/terraform-modules$ gcloud config set project traffic-cnd
Updated property [core/project].
```

**Comment by fmichaelobrien** [comment]
Coordination with https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit/issues/84

**Comment by fmichaelobrien** [comment]
Verify VDOM (Virtual Domain) fortifate prod zone separation 
https://docs.fortinet.com/document/fortigate/6.0.0/cookbook/154890/vdom-configuration
https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit/blob/dev/solutions/landing-zone/architecture.md#di-24-validate-vdom---virtual-domain-fortigate-zone-isolation

**Comment by fmichaelobrien** [comment]
Deploying example cluster in https://github.com/fortinet/fortigate-tutorial-gcp/issues/1 - thanks Dave

**Comment by obriensystems** [comment]
Fortigate HA LB active/standby up (both vms)- but issues with payg instead of byod license being worked out
Example project contains the entire stack including 4 VPCs for the fortigates and 2 for the public and private perimeters - hence a compute-networks quota request is required to move from 5 to 6 VPCs (you can delete the default VPC)

https://github.com/fortinet/fortigate-tutorial-gcp/issues/1

<img width="1569" alt="Screen Shot 2022-10-20 at 00 26 42" src="https://user-images.githubusercontent.com/24765473/196856408-94dedd03-f2fd-490b-83c1-2eb05056c354.png">

<img width="1332" alt="Screen Shot 2022-10-20 at 00 27 27" src="https://user-images.githubusercontent.com/24765473/196856477-da8f0ed0-8e6f-425b-8146-2bc79d0be2e7.png">

<img width="1564" alt="Screen Shot 2022-10-20 at 00 28 29" src="https://user-images.githubusercontent.com/24765473/196856605-2b945be8-34b5-4ea6-b083-53157f7b61db.png">

**Comment by fmichaelobrien** [comment]
compute.networks Quota is per project
5-10
<img width="1647" alt="Screen Shot 2022-10-20 at 7 54 30 AM" src="https://user-images.githubusercontent.com/94715080/196941547-496170b5-d4d2-4293-aac7-7d5e492198c1.png">

5
<img width="1630" alt="Screen Shot 2022-10-20 at 7 53 18 AM" src="https://user-images.githubusercontent.com/94715080/196941325-cafced29-2845-4429-b55c-171636267894.png">

**Comment by fmichaelobrien** [comment]
Some background for collaborators - The Fortinet initiative started a year ago, we had a couple sessions with the Fortinet team and one at a dept in Feb 
The TF work has been on hold since Oct 2022 as the focus moved to the kcc version of perimeter work.  Full NGFW fortigate/ids integration is planned for last 2023

Both are in public on the public facing LZ repos with extensive notes
partially deployed - https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit/issues/258
feasibility only - https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/issues/45
A good reference is the gcloud lb sandwich
https://github.com/fortinetsolutions/terraform-modules/tree/master/GCP/examples/ha-active-passive
and in particular the gcloud deployment - which can be CC bulk exported after deployment - there are instructions i documented "in public" on raising the fortigate-tutorial-gcp for
https://github.com/fortinet/fortigate-tutorial-gcp/tree/main/gcloud
in
https://github.com/fortinet/fortigate-tutorial-gcp/issues/1

**Comment by obriensystems** [comment]
part of #360

**Comment by obriensystems** [comment]
20240406: Closing issue during retrofit/rebase of this TEF V1 based/modified repo to TEF V4 standards
This issue may participate in the LZ refactor after rebase
Query on all issues related to the older V1 version via the tag
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/labels/2024-pre-tef-v4
