### ISSUE TITLE
Please clarify purpose and usage of this repo vs terraform-example-foundation

### ISSUE THREAD

**Issue by alfrecron11** [GoogleCloudPlatform/pbmm-on-gcp-onboarding#471]
Looking at the instructions in the Readme files, the referenced name of base folder for the code is named "terraform-example-foundation" But when cloning this repo the base folder is pbmm-on-gcp-onboarding.  
Example in 0-bootstrap

```
Clone [terraform-example-foundation](https://github.com/terraform-google-modules/terraform-example-foundation) into your local environment and navigate to the 0-bootstrap folder.
git clone https://github.com/terraform-google-modules/terraform-example-foundation.git
cd terraform-example-foundation/0-bootstrap

```
Is this repo maintained ? Looking at the commits the most recent ones are more than 3 month ago.
Can someone clarify what is the purpose and usage of this repo as in fact it seems all the code is supposed to come from another github repo?

**Comment by obriensystems** [comment]
fyi, some history on https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/wiki
