### ISSUE TITLE
Following "cloud source" sunset on june 17 2024, CB deployment broken, update needed for the code and deployment procedure.

### ISSUE THREAD

**Issue by grombath55** [GoogleCloudPlatform/pbmm-on-gcp-onboarding#472]
In 0-bootstrap (cb.tf) and 4-projects (example_infra_pipeline.tf) the API "sourcerepo.googleapis.com" is activated
But since June 17 2024 this is no longer working and the cb.tf module returns an error.
How this distribution is supposed to be deployed w/o cloud source? The new "secure source manager" replacing "cloud source" does not work the same and even the "gcloud source clone repos clone"  command referenced in the documented procedures no longer works.

The Readme docs in "main" seem stale, not having been updated for the last 7-8 months, however the sunset of "cloud source" was announced way back. And still the documentation does not reflect this.

What are the remaining / working options for deploying and assessing the "fit for use" of this distribution?  Before embarking into testing deployment w/ Jenkins / Gitlab / Github / TFCloud were these deployments methods thoroughly tested and validated ? Because it seems the only fully documented deployment procedure is the cloudbuild one.

It seems that there is also a barely documented "Local deployment" procedure and an undocumented Azure Devops pipeline which seems to implement a deployment procedure using "local" Terraform commands.  Are these methods validated and functional? For the Devops pipeline there is no mention whatsoever in the documentation.

Did anyone successfully experiment with the Local or Devops deployment methods? If the case would it be possible to document the steps and outcomes?

**Comment by obriensystems** [comment]
see also https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/issues/439 and https://github.com/terraform-google-modules/terraform-example-foundation/issues/1249

**Comment by obriensystems** [comment]
and https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/issues/469
