### ISSUE TITLE
Enable vpcaccess API for VPC serverless access

### ISSUE THREAD

**Issue by fmichaelobrien** [GoogleCloudPlatform/pbmm-on-gcp-onboarding#50]
Navigating to VPC / serverless access
enable via TF adjust like the cli endpoing
```
admin_super@cloudshell:~$ gcloud config set project ospe-obs-obsprd-obshostproj7
Updated property [core/project].
admin_super@cloudshell:~ (ospe-obs-obsprd-obshostproj7)$ gcloud services enable vpcaccess.googleapis.com
Operation "operations/acf.p2-190560299827-e1782e65-9bd0-411a-a4a4-768d0ebc31de" finished successfully.
```
to fix

<img width="974" alt="Screen Shot 2022-04-10 at 7 19 45 PM" src="https://user-images.githubusercontent.com/94715080/162644200-1d53e78a-e593-4fc3-9054-5a0337d94d48.png">
<img width="935" alt="Screen Shot 2022-04-10 at 7 20 10 PM" src="https://user-images.githubusercontent.com/94715080/162644211-dea21fdd-ac2e-4517-ac04-997db7a7f8b4.png">

**Comment by obriensystems** [comment]
20240406: Closing issue during retrofit/rebase of this TEF V1 based/modified repo to TEF V4 standards
This issue may participate in the LZ refactor after rebase
Query on all issues related to the older V1 version via the tag
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/labels/2024-pre-tef-v4
