### ISSUE TITLE
Enable identity aware proxy API

### ISSUE THREAD

**Issue by fmichaelobrien** [GoogleCloudPlatform/pbmm-on-gcp-onboarding#51]
We are using IAP and need to enable the API
<img width="1200" alt="Screen Shot 2022-04-10 at 7 30 04 PM" src="https://user-images.githubusercontent.com/94715080/162644573-7491aaea-bc3a-46a7-bf24-1e2014c5e7c7.png">

```
admin_super@cloudshell:~ (ospe-obs-obsprd-obshostproj7)$ gcloud services list
NAME: compute.googleapis.com
TITLE: Compute Engine API

NAME: deploymentmanager.googleapis.com
TITLE: Cloud Deployment Manager V2 API

NAME: logging.googleapis.com
TITLE: Cloud Logging API

NAME: monitoring.googleapis.com
TITLE: Cloud Monitoring API

NAME: oslogin.googleapis.com
TITLE: Cloud OS Login API

NAME: vpcaccess.googleapis.com
TITLE: Serverless VPC Access API
```

**Comment by fmichaelobrien** [comment]
<img width="1519" alt="_5302_identity_Aware_proxy_configure_consent_screen" src="https://user-images.githubusercontent.com/94715080/165202466-b163669f-abc1-4db1-be61-94c18f623ca3.png">

**Comment by fmichaelobrien** [comment]
see issues with IAP for GCE ssh
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/issues/48#issuecomment-1129042940

**Comment by fmichaelobrien** [comment]
SSH on non lz project also has the warning (no warning on clean GCP) - connects OK

Please consider adding the IAP-secured Tunnel User IAM role to start using Cloud IAP for TCP forwarding for better performance.
<img width="899" alt="Screen Shot 2022-05-20 at 9 49 05 AM" src="https://user-images.githubusercontent.com/94715080/169542046-8f82b1b7-fac5-47d2-b963-792187542784.png">
<img width="1425" alt="Screen Shot 2022-05-20 at 9 49 30 AM" src="https://user-images.githubusercontent.com/94715080/169542132-2996c01f-3af3-4c17-ac98-c5ee3dd8fd93.png">

**Comment by obriensystems** [comment]
20240406: Closing issue during retrofit/rebase of this TEF V1 based/modified repo to TEF V4 standards
This issue may participate in the LZ refactor after rebase
Query on all issues related to the older V1 version via the tag
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/labels/2024-pre-tef-v4
