### ISSUE TITLE
Verify that the default log sinks (_Default, _Required) are sufficient

### ISSUE THREAD

**Issue by fmichaelobrien** [GoogleCloudPlatform/pbmm-on-gcp-onboarding#54]
The 2 log sinks in the guardrails, audit and prod project are actually only the 2 defaults that are automatically created

<img width="1525" alt="Screen Shot 2022-04-10 at 8 03 38 PM" src="https://user-images.githubusercontent.com/94715080/162645710-4be7155d-bd40-4ee3-b577-f2ad400f4b8c.png">

**Comment by fmichaelobrien** [comment]
Thanks Mike C. - at the org level

osPeCLD-oscommsink1-sink

Display name
[OsPeCLD-oscommsink1-sink](https://console.cloud.google.com/#)
Asset type
logging.googleapis.com/LogSink
Location
[global](https://console.cloud.google.com/#)


Display name
[DoPeCLD-corcommsink1-sink](https://console.cloud.google.com/#)
Asset type
logging.googleapis.com/LogSink
Location
[global](https://console.cloud.google.com/#)
(ok - just check the org level coverage after a in/out traffic generation microservice set is up)

**Comment by obriensystems** [comment]
20240406: Closing issue during retrofit/rebase of this TEF V1 based/modified repo to TEF V4 standards
This issue may participate in the LZ refactor after rebase
Query on all issues related to the older V1 version via the tag
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/labels/2024-pre-tef-v4
