### ISSUE TITLE
Add validation for 63 char resource id limit - we are around 60 for some ids like the firewall rules

### ISSUE THREAD

**Issue by fmichaelobrien** [GoogleCloudPlatform/pbmm-on-gcp-onboarding#56]
The following went over 63

Step #2 - "tf plan": │ Error: Invalid value for variable
Step #2 - "tf plan": │ 
Step #2 - "tf plan": │   on ../../modules/firewall/naming.tf line 79, in module "custom_rules_names":
Step #2 - "tf plan": │   79:   user_defined_string = each.key
Step #2 - "tf plan": │ 
Step #2 - "tf plan": │ The name must be 1-63 characters long, and comply with RFC1035 the first
Step #2 - "tf plan": │ character must be a lowercase letter, and all following characters must be
Step #2 - "tf plan": │ a dash, lowercase letter, or digit, except the last character, which cannot
Step #2 - "tf plan": │ be a dash.

projects/dope-dod-coprod-coperim/global/firewalls/dopefwl-allow-ssh-ingress-fwr
to (74)
projects/dope-dod-coprod-coperim/global/firewalls/dopefwl-allow-ssh-ingress-pub-fwr

**Comment by obriensystems** [comment]
20240406: Closing issue during retrofit/rebase of this TEF V1 based/modified repo to TEF V4 standards
This issue may participate in the LZ refactor after rebase
Query on all issues related to the older V1 version via the tag
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/labels/2024-pre-tef-v4
