### ISSUE TITLE
Setup weekly developer office hours call - 1710-1725 GMT every 2nd Tuesday starting 10 May 2022

### ISSUE THREAD

**Issue by fmichaelobrien** [GoogleCloudPlatform/pbmm-on-gcp-onboarding#58]
Times - offers welcome

Purpose: pbmm-lz office hours - open source collaborators 2 week sync
## Weekly Office Hours / Collaborators Meeting
 - Time: 1310-1325 EDT, 1710-1725 GMT, 1010-1025 PDT
 - Date: 10 May 2022, 25 May - every 2 weeks on Tuesday
 - Location: https://meet.google.com/qmh-uzqk-ssn?authuser=0&hs=122

Purpose:
- sync PRs in queue
- sync issue assignments/priorities - developer allocation/objectives
- discuss ongoing work
- discuss upcoming enhancements
- discuss static validation automation
- discuss runtime dynamic validation (uServices, traffic generation, external/internal/peering connections/traffic, logs, alerts, metric generation)

**Comment by obriensystems** [comment]
Add
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/issues/created_by/patpicos

**Comment by fmichaelobrien** [comment]
# 20220510 developer office hours 1 - agenda
- Issues outstanding review
- Contributing
- PR procedures - getting involved
   keep the main branch stable
   use either short/long lived repo branches or a private fork for PR work
   example https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/pull/43
   testing as per the PR
   for example a readme.md will not require testing - unless there is CLI (all CLI must have verification in the PR)
   otherwise any changes affecting deployment - will need deployment testing evidence
   https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/pull/43#issuecomment-1095485808 
- Questions/answers
- Next call 1710GMT 20220524 - see https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding#weekly-office-hours--collaborators-meeting

**Comment by fmichaelobrien** [comment]
Changed to Wed's 20220921 1430-1530 EDT until Dec 21 2022

Landing Zone weekly Wed office hours 1430-1530 - optional
Video call link: https://meet.google.com/nwp-xcdi-vms

**Comment by fmichaelobrien** [comment]
20240406: Closing issue during retrofit/rebase of this TEF V1 based/modified repo to TEF V4 standards
This issue may participate in the LZ refactor after rebase
Query on all issues related to the older V1 version via the tag
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/labels/2024-pre-tef-v4
