### ISSUE TITLE
Azure References in source code

### ISSUE THREAD

**Issue by patpicos** [GoogleCloudPlatform/pbmm-on-gcp-onboarding#63]
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/blob/e346334fd3fd41b9c26f0c4a68c9c2da7b5233b1/modules/naming-standard/README.md?plain=1#L97

Why are there Azure references in a GCP code base?

**Comment by fmichaelobrien** [comment]
likely original linking in multi-cloud CSP modules - I would keep it as is - to  encourage tracking/tracing and updates

**Comment by fmichaelobrien** [comment]
see
#63
#64
#65
#66

**Comment by fmichaelobrien** [comment]
triaging priorities in prep of a planned release - reopen with a tested PR if needed

**Comment by fmichaelobrien** [comment]
We frequently deploy in customer environments that interface with ad and ado, hence some azure, AWS, gcp identifiers may be mixed together in a local naming standard
