### ISSUE TITLE
Reference to Azure documentation

### ISSUE THREAD

**Issue by patpicos** [GoogleCloudPlatform/pbmm-on-gcp-onboarding#64]
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/blob/c0bffc85af6ba17eab10f74dfd077ddc11fdf714/modules/naming-standard/configs/resource_types.yaml#L3

**Comment by fmichaelobrien** [comment]
Comment based on best practice across the CSP industry and/or original linking in multi-cloud CSP modules is encouraged for tracking/tracing and updates

**Comment by fmichaelobrien** [comment]
triaging priorities in prep of a planned release - reopen with a tested PR if needed

**Comment by fmichaelobrien** [comment]
We frequently deploy in customer environments that interface with ad and ado, hence some azure, AWS, gcp identifiers may be mixed together in a local naming standard
