### ISSUE TITLE
Azure reference in go.sum

### ISSUE THREAD

**Issue by patpicos** [GoogleCloudPlatform/pbmm-on-gcp-onboarding#65]
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/blob/c0bffc85af6ba17eab10f74dfd077ddc11fdf714/modules/folder/go.sum#L14-L47

**Comment by fmichaelobrien** [comment]
These modules are currently unused

**Comment by fmichaelobrien** [comment]
triaging priorities in prep of a planned release - reopen with a tested PR if needed

**Comment by fmichaelobrien** [comment]
We frequently deploy in customer environments that interface with ad and ado, hence some azure, AWS, gcp identifiers may be mixed together in a local naming standard
