### ISSUE TITLE
Reissue TDD based on prod deployment changes since Nov 2021

### ISSUE THREAD

**Issue by fmichaelobrien** [GoogleCloudPlatform/pbmm-on-gcp-onboarding#68]
update and include readme.md changes
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/blob/main/Technical%20Design%20Document_Canada%20PBMM%20Landing%20Zone_20220211.1.pdf

**Comment by fmichaelobrien** [comment]
see https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/issues/162

**Comment by obriensystems** [comment]
20240406: Closing issue during retrofit/rebase of this TEF V1 based/modified repo to TEF V4 standards
This issue may participate in the LZ refactor after rebase
Query on all issues related to the older V1 version via the tag
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/labels/2024-pre-tef-v4
