### ISSUE TITLE
Compliance Evidence: Guardrails 12 - marketplace config - restricted content missing

### ISSUE THREAD

**Issue by fmichaelobrien** [GoogleCloudPlatform/pbmm-on-gcp-onboarding#69]
see CM‑2, CM‑3, CM‑4, CM‑5, CM‑8, SA‑22
https://github.com/canada-ca/cloud-guardrails/blob/master/EN/12_Cloud-Marketplace-Config.md

see Service Catalog https://cloud.google.com/service-catalog
```
permissions at the project level
cloudprivatecatalogproducer.settings.get
cloudprivatecatalogproducer.settings.update
```

or IAM policy for purchasing products
https://cloud.google.com/marketplace/docs/access-control

purchase via
https://cloud.google.com/iam/docs/understanding-roles#billing-roles
roles/billing.admin
which is in the billing admin group

For usage - add the project viewer https://cloud.google.com/iam/docs/understanding-roles#basic

**Comment by obriensystems** [comment]
Issue is though that we seem to need marketplace for certain essential native GCP services like CSR

for example - creating a new repo - contains /marketplace in the url

https://console.cloud.google.com/marketplace/product/google-cloud-platform/cloud-source-repositories?q=search&referrer=search&project=magellan-01

gets us to the source.cloud page

https://source.cloud.google.com/

we need to verifying turning off marketplace will not affect GCP operation

**Comment by obriensystems** [comment]
20240406: Closing issue during retrofit/rebase of this TEF V1 based/modified repo to TEF V4 standards
This issue may participate in the LZ refactor after rebase
Query on all issues related to the older V1 version via the tag
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/labels/2024-pre-tef-v4
