### ISSUE TITLE
Installation run prerequisites around organization/cloud-identity onboarding - capture in prep of readme.md update

### ISSUE THREAD

**Issue by fmichaelobrien** [GoogleCloudPlatform/pbmm-on-gcp-onboarding#7]
# capturing additions to the doc prior to a patch

https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding#readme

## Use case: non-GCP domain for identity federation
- new super admin role account (non-workspace) cloud identity
- external to GCP domain that will be used for cloud identity users to validate against - domain must be a subdomain like sub.domain.com - to avoid TXT zone collision with existing records at the root domain
- in IAM run the checklist - as the super admin users - the first step organization creation will auto create here
- https://console.cloud.google.com/cloud-setup/users-groups
- step 2 : group creation - for example "gcp-organization-admins@gcp.packet.global"
- step 3 :  admin and billing group role assignments

20220317 update
https://cloud.google.com/blog/topics/developers-practitioners/using-google-cloud-service-account-impersonation-your-terraform-code

**Comment by fmichaelobrien** [comment]
20220317 - restart and check permissions above

michael@cloudshell:~$ gcloud config set project landingzone-stg
Updated property [core/project].
michael@cloudshell:~ (landingzone-stg)$

checked artifact registry not enabled on landingzone-stg before - enabled after
michael@cloudshell:~/github/pbmm-on-gcp-onboarding-main/environments/bootstrap (landingzone-stg)$ gcloud services enable \
  cloudbilling.googleapis.com \
  cloudresourcemanager.googleapis.com \
  storage-api.googleapis.com \
  sourcerepo.googleapis.com \
  cloudkms.googleapis.com \
  compute.googleapis.com \
  iam.googleapis.com \
  iamcredentials.googleapis.com \
  monitoring.googleapis.com \
  logging.googleapis.com \
  bigquery.googleapis.com \
  artifactregistry.googleapis.com \
  cloudbuild.googleapis.com \
  container.googleapis.com
Operation "operations/acat.p2-403373923652-f1144ac7-5e2e-4f9f-afc1-d1a7fc354798" finished successfully.

enablement takes time for some regions
Failed to list repositories for the following locations: europe, asia-northeast1, asia-south1. If you recently enabled the Artifact Registry API, the enablement status might not have propagated to these locations. Please try again later.


rerunning to check state on SA

change the cb dockerfile first (even though we have a 777 on it)
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/issues/9#issuecomment-1068465128

COPY entrypoint.bash /builder/entrypoint.bash
+RUN chmod +x /builder/entrypoint.bash
ENTRYPOINT ["/builder/entrypoint.bash"]

michael@cloudshell:~/github/pbmm-on-gcp-onboarding-main/environments/bootstrap (landingzone-stg)$ ./bootstrap.sh run
│ Error: googleapi: Error 403: The caller does not have permission, forbidden
│
│   with data.google_service_account_access_token.default,
│   on provider.tf line 25, in data "google_service_account_access_token" "default":
│   25: data "google_service_account_access_token" "default" {


delete provider.tf in bootstrap and common

**Comment by fmichaelobrien** [comment]
Thanks Chris for the template - will adapt https://github.com/kubernetes/kubernetes/blob/master/.github/PULL_REQUEST_TEMPLATE.md

**Comment by fmichaelobrien** [comment]
│ Error: googleapi: Error 404: Requested entity was not found., notFound
│
│   with data.google_service_account_access_token.default,
│   on provider.tf line 25, in data "google_service_account_access_token" "default":
│   25: data "google_service_account_access_token" "default" {

fixed by deleting the provider.tf's as above
cycle the bucket name
 Error: Error when reading or editing Storage Bucket "copecontainerizedlznp": Get "https://storage.googleapis.com/storage/v1/b/copecontainerizedlznp?alt=json&prettyPrint=false": dial tcp [2607:f8b0:400c:c12::80]:443: connect: cannot assign requested address
│
│   with module.landing_zone_bootstrap.google_storage_bucket.org_terraform_state["nonprod"],
│   on ../../modules/landing-zone-bootstrap/main.tf line 83, in resource "google_storage_bucket" "org_terraform_state":
│   83: resource "google_storage_bucket" "org_terraform_state" {


modified bucket names

rerun
Plan: 50 to add, 9 to change, 20 to destroy.


module.cloudbuild_bootstrap.null_resource.cloudbuild_terraform_builder (local-exec): ID: a94f80e0-fae1-4d0c-a844-b50117dcc0c6
module.cloudbuild_bootstrap.null_resource.cloudbuild_terraform_builder (local-exec): CREATE_TIME: 2022-03-17T19:01:25+00:00
module.cloudbuild_bootstrap.null_resource.cloudbuild_terraform_builder (local-exec): DURATION: -
module.cloudbuild_bootstrap.null_resource.cloudbuild_terraform_builder (local-exec): SOURCE: gs://cope-cod-codev-sbx_cloudbuild/source/1647543685.116032-ff109bf185f448ba847c6edf89183fa6.tgz
module.cloudbuild_bootstrap.null_resource.cloudbuild_terraform_builder (local-exec): IMAGES: -
module.cloudbuild_bootstrap.null_resource.cloudbuild_terraform_builder (local-exec): STATUS: QUEUED
module.cloudbuild_bootstrap.null_resource.cloudbuild_terraform_builder: Creation complete after 4s [id=8629374506232579809]
╷
│ Warning: Experimental feature "module_variable_optional_attrs" is active
│
│   on terraform.tf line 7, in terraform:
│    7:   experiments = [module_variable_optional_attrs]
│
│ Experimental features are subject to breaking changes in future minor or patch releases, based on feedback.
│
│ If you have feedback on the design of this feature, please open a GitHub issue to discuss it.
│
│ (and 2 more similar warnings elsewhere)
╵
╷
│ Error: Failed to save state
│
│ Error saving state: Failed to upload state to gs://copecontainerizedlzco/environments/bootstrap/default.tfstate: googleapi: Error 404: The specified bucket does not exist.,
│ notFound
╵
╷
│ Error: Failed to persist state to backend
│
│ The error shown above has prevented Terraform from writing the updated state to the configured backend. To allow for recovery, the state has been written to the file
│ "errored.tfstate" in the current working directory.
│
│ Running "terraform apply" again at this point will create a forked state, making it harder to recover.
│
│ To retry writing this state, use the following command:
│     terraform state push errored.tfstate
│
╵
╷
│ Error: Error releasing the state lock
│
│ Error message: 2 errors occurred:
│   * storage: object doesn't exist
│   * storage: object doesn't exist
│
│
│
│ Terraform acquires a lock when accessing your state to prevent others
│ running Terraform to potentially modify the state at the same time. An
│ error occurred while releasing this lock. This could mean that the lock
│ did or did not release properly. If the lock didn't release properly,
│ Terraform may not be able to run future commands since it'll appear as if
│ the lock is held.
│
│ In this scenario, please call the "force-unlock" command to unlock the
│ state manually. This is a very dangerous operation since if it is done
│ erroneously it could result in two people modifying state at the same time.
│ Only call this command if you're certain that the unlock above failed and
│ that no one else is holding a lock.
╵

rebuild 1st cb job after token fixe
landing-zone-bootstrap-push-trigger

note all required on bucket names are not actually required - just need a string as we auto append random chars


add to common tfvars
      bucket_name          = "audit"               # REQUIRED EDIT. Must be globally unique, used for the audit bucket - will append

 { # remove line 75
    member = "group:group2@test.domain.net"
    roles = [
      "roles/viewer",
    ]
  }
]


forgot 84/96/106

**Comment by fmichaelobrien** [comment]
rerun 2 - make sure we are in a repo - not a zip

**Comment by fmichaelobrien** [comment]
clone the repo  - use an existing folder/project structure
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/issues/14

Welcome to Cloud Shell! Type "help" to get started.
Your Cloud Platform project in this session is set to cope-cod-codev-sbx.
Use “gcloud config set project [PROJECT_ID]” to change to a different project.
cloudshell_open --repo_url "https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding" --page "editor" --tutorial "README.md" --force_new_clone
michael@cloudshell:~ (cope-cod-codev-sbx)$ cloudshell_open --repo_url "https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding" --page "editor" --tutorial "README.md" --force_new_clone
2022/03/17 20:43:09 Cloning https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding into /home/michael/cloudshell_open/pbmm-on-gcp-onboarding
Cloning into '/home/michael/cloudshell_open/pbmm-on-gcp-onboarding'...
remote: Enumerating objects: 797, done.
remote: Counting objects: 100% (797/797), done.
remote: Compressing objects: 100% (479/479), done.
remote: Total 797 (delta 345), reused 712 (delta 285), pack-reused 0
Receiving objects: 100% (797/797), 609.60 KiB | 8.47 MiB/s, done.
Resolving deltas: 100% (345/345), done.
michael@cloudshell:~/cloudshell_open/pbmm-on-gcp-onboarding (cope-cod-codev-sbx)$ git status
On branch main
Your branch is up to date with 'origin/main'.


michael@cloudshell:~/cloudshell_open/pbmm-on-gcp-onboarding (landingzone-sbx)$ gcloud config set project landingzone-stg
Updated property [core/project].

**Comment by obriensystems** [comment]
# terraform show output attached

# error
in org tfvars - billing account is email 
  billing_account = "mic...erized.org" # REQUIRED EDIT Format of ######-######-######

# nonprod config
edit all three auto.tfvars variables in https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/tree/main/environments/nonprod

Before running check pre-PR changes

755's in both scripts

viewer to owner role 2 in common/common.auto.tfvars
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/pull/21/files#diff-cdfb3286ca9a1536d1a76793bb08135732f6fa216a1032f0d96e5a78c4a181e2R118

**Comment by obriensystems** [comment]
Continuing non-prod/prod based on example branch
Note: non-prod needs prod up - to create vpc peering

Step #3 - "tf apply": │ Error: Error adding network peering: googleapi: Error 400: Invalid value for field 'networkPeering.network': 'projects/dcde-team-prod-perim/global/networks/dcdecnr-privperimvpc-vpc'. The project 'dcde-team-prod-perim' was not found., invalid

https://console.cloud.google.com/cloud-build/builds;region=global/7675a46b-1c2b-40ba-bd41-2b378d3301e1?project=dope-dod-dodev-dbx

**Comment by obriensystems** [comment]
20240406: Closing issue during retrofit/rebase of this TEF V1 based/modified repo to TEF V4 standards
This issue may participate in the LZ refactor after rebase
Query on all issues related to the older V1 version via the tag
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/labels/2024-pre-tef-v4
