### ISSUE TITLE
Formal documentation folder

### ISSUE THREAD

**Issue by fmichaelobrien** [GoogleCloudPlatform/pbmm-on-gcp-onboarding#75]
# main PR story and subtasks here

# topics
## firewall
- native GCP armor
- 3rd party Fortinet/Fortigate, Paloalto, Checkpoint, Juniper networks, Cisco, Barracuda

**Comment by obriensystems** [comment]
# topics
- developer doc (CICD, updating releases, pulling changes from this repo to a local landing zone deployment
- traffic generation app including tx/trace/audit logs
- thread parallel VM cpu/ram saturation app - for auto scaling events
- audit/alert generation app
- compliance verification apps/deployments (attempt cloud run batch container in non-NA region)
- mitigation for LZ breaking changes affecting app redeploys (VPC changes that kick out VMs for example)
-

**Comment by fmichaelobrien** [comment]
git rebase of remote branch
```
michael@cloudshell:~/cloudshell_open/pbmm-on-gcp-onboarding (landingzone-stg)$ git config --global pull.rebase false
michael@cloudshell:~/cloudshell_open/pbmm-on-gcp-onboarding (landingzone-stg)$ git pull https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding.git fmichaelobrien
From https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding
 * branch            fmichaelobrien -> FETCH_HEAD
fatal: refusing to merge unrelated histories


```
