### ISSUE TITLE
Verify prod/proj default local route CIDRs are 24/25/25 - 256 vs 128

### ISSUE THREAD

**Issue by fmichaelobrien** [GoogleCloudPlatform/pbmm-on-gcp-onboarding#76]
Finding it odd that one of our 3 subnets - project is size 24 (256) but shared services, shared infra are 25 (128)

Could just be a typo
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/blob/example/environments/prod/prod-network.auto.tfvars#L52
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/blob/fmichaelobrien-example-prod/environments/prod/prod-network.auto.tfvars#L54

Note: the 3 subnetwork config is not in main yet - only 1 subnet exists there
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/blob/fmichaelobrien-example-prod/environments/prod/prod-network.auto.tfvars#L54

**Comment by obriensystems** [comment]
20240406: Closing issue during retrofit/rebase of this TEF V1 based/modified repo to TEF V4 standards
This issue may participate in the LZ refactor after rebase
Query on all issues related to the older V1 version via the tag
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/labels/2024-pre-tef-v4
