### ISSUE TITLE
Verify PR 77 disable serial port access and skipDefaultNetworkCreation both set to true

### ISSUE THREAD

**Issue by fmichaelobrien** [GoogleCloudPlatform/pbmm-on-gcp-onboarding#78]
verify https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/pull/77

https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/blob/main/environments/common/common.auto.tfvars#L9
```
  policy_boolean        = { "constraints/compute.skipDefaultNetworkCreation" = true, "constraints/compute.disableSerialPortAccess" = true } #constraints/compute.skipDefaultNetworkCreation = false
```

We will need to patch a live system and verify on the non-prod or prod TF deployment CB trigger - I can do this later today if needed

verify both flipped from false, rerun deployment, add to the ATO evidence doc
constraints/compute.skipDefaultNetworkCreation" = true
"constraints/compute.disableSerialPortAccess" = true

**Comment by obriensystems** [comment]
20240406: Closing issue during retrofit/rebase of this TEF V1 based/modified repo to TEF V4 standards
This issue may participate in the LZ refactor after rebase
Query on all issues related to the older V1 version via the tag
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/labels/2024-pre-tef-v4
