### ISSUE TITLE
Exercise landing zone automated workflow such as audit log trigger filters with traffic-generation north/southbound pair

### ISSUE THREAD

**Issue by fmichaelobrien** [GoogleCloudPlatform/pbmm-on-gcp-onboarding#82]
# anything that causes event handling
- audit log trigger filters push events via eventarc to a service/k8s-container (see Seroter: https://cloud.google.com/eventarc/docs/gke/creating-triggers 
- storage bucket event
- pub sub topic publishing

**Comment by obriensystems** [comment]
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/blob/main/docs/google-cloud-landingzone-traffic-generation.md

**Comment by obriensystems** [comment]
20240406: Closing issue during retrofit/rebase of this TEF V1 based/modified repo to TEF V4 standards
This issue may participate in the LZ refactor after rebase
Query on all issues related to the older V1 version via the tag
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/labels/2024-pre-tef-v4
