### ISSUE TITLE
Adjust common/perimeter network name to avoid collision with previous location in prod - via  user_defined_string

### ISSUE THREAD

**Issue by obriensystems** [GoogleCloudPlatform/pbmm-on-gcp-onboarding#84]
Without this a redeployment on git merge with the 0.1.0 release will fail as common and prod will be in exclusive conflict
line 7
```
public_perimeter_net = {
 - user_defined_string            = "obsprod" # must be globally unique
 + user_defined_string            = "obsprd" # must be globally unique
```

<img width="1682" alt="Screen Shot 2022-05-15 at 11 07 21" src="https://user-images.githubusercontent.com/24765473/168479930-336ef12f-58e1-4917-bd04-6814003a3889.png">

<img width="1680" alt="Screen Shot 2022-05-15 at 11 15 37" src="https://user-images.githubusercontent.com/24765473/168480139-d0dd0556-3e79-45af-a6a7-cbf827cc9e85.png">

**Comment by fmichaelobrien** [comment]
Tested above in previous run for #81

**Comment by obriensystems** [comment]
20240406: Closing issue during retrofit/rebase of this TEF V1 based/modified repo to TEF V4 standards
This issue may participate in the LZ refactor after rebase
Query on all issues related to the older V1 version via the tag
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/labels/2024-pre-tef-v4
