### ISSUE TITLE
Enable artifact registry vulnerability scanning

### ISSUE THREAD

**Issue by fmichaelobrien** [GoogleCloudPlatform/pbmm-on-gcp-onboarding#86]
Turn on CVE scanning by default on the TF runner and any other app images

<img width="1426" alt="Screen Shot 2022-05-17 at 10 14 08 AM" src="https://user-images.githubusercontent.com/94715080/168832366-863b3fc2-9ee0-4408-a2fa-ee8bf7d8c4a4.png">

**Comment by fmichaelobrien** [comment]
add to services list 
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/blob/main/environments/nonprod/nonp-network.auto.tfvars#L11
and
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/blob/main/environments/prod/prod-network.auto.tfvars#L11

**Comment by fmichaelobrien** [comment]
<img width="1720" alt="_0904_artifact_registry_vulnerability_scanning_example_run" src="https://user-images.githubusercontent.com/94715080/177174226-1bb0f56c-d4c5-4bb2-9ad2-fd71203dae1b.png">

**Comment by obriensystems** [comment]
20240406: Closing issue during retrofit/rebase of this TEF V1 based/modified repo to TEF V4 standards
This issue may participate in the LZ refactor after rebase
Query on all issues related to the older V1 version via the tag
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/labels/2024-pre-tef-v4
