### ISSUE TITLE
Triage dev-cloudbuild_artifacts bucket deletion error in bootstrap for 1 of 2 project

### ISSUE THREAD

**Issue by fmichaelobrien** [GoogleCloudPlatform/pbmm-on-gcp-onboarding#88]
Error: Error trying to delete bucket ..ev-cloudbuild_artifacts containing objects without `force_destroy` set to true
https://github.com/hashicorp/terraform-provider-google/issues/1509

**Comment by obriensystems** [comment]
20240406: Closing issue during retrofit/rebase of this TEF V1 based/modified repo to TEF V4 standards
This issue may participate in the LZ refactor after rebase
Query on all issues related to the older V1 version via the tag
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/labels/2024-pre-tef-v4
