### ISSUE TITLE
Add entrypoint.sh chmod 777 in addition to bootstrap.sh in readme

### ISSUE THREAD

**Issue by fmichaelobrien** [GoogleCloudPlatform/pbmm-on-gcp-onboarding#9]
2nd chmod 777 in addition to bootstrap.sh

modules/cloudbuild/cloudbuild_builder/entrypoint.sh

or you get the following on the cloud build step
https://console.cloud.google.com/cloud-build/builds;region=global/3614b560-219c-4969-9119-9c34e8faa02c?cloudshell=true&project=olse-oldev-oldev-sbx

Step #0: Processing triggers for mime-support (3.64ubuntu1) ...
Step #0: /bin/sh: 1: RUN: not found
Step #0: The command '/bin/sh -c apt-get update &&    /builder/google-cloud-sdk/bin/gcloud -q components install alpha beta &&     apt-get -y install curl jq unzip git ca-certificates && RUN curl https://releases.hashicorp.com/terraform/${ENV_TERRAFORM_VERSION}/terraform_${ENV_TERRAFORM_VERSION}_linux_amd64.zip       > terraform_linux_amd64.zip &&     echo "${ENV_TERRAFORM_VERSION_SHA256SUM} terraform_linux_amd64.zip" > terraform_SHA256SUMS &&     sha256sum -c terraform_SHA256SUMS --status &&     unzip terraform_linux_amd64.zip -d /builder/terraform &&     rm -f terraform_linux_amd64.zip' returned a non-zero code: 127
Finished Step #0
ERROR
ERROR: build step 0 "gcr.io/cloud-builders/docker" failed: step exited with non-zero status: 127
Step #0:

**Comment by obriensystems** [comment]
20240406: Closing issue during retrofit/rebase of this TEF V1 based/modified repo to TEF V4 standards
This issue may participate in the LZ refactor after rebase
Query on all issues related to the older V1 version via the tag
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/labels/2024-pre-tef-v4
