### ISSUE TITLE
Handle deployed resources in the lz via load backup/restore during non-prod/prod terraform delete/apply - during repo update

### ISSUE THREAD

**Issue by fmichaelobrien** [GoogleCloudPlatform/pbmm-on-gcp-onboarding#91]
- Discussion/architecture around retaining deployed workload (VMs, cloud run.... involved for example in ATO evidence/compliance traffic gen - or customer deployments) resources in the LZ

**Comment by obriensystems** [comment]
20240406: Closing issue during retrofit/rebase of this TEF V1 based/modified repo to TEF V4 standards
This issue may participate in the LZ refactor after rebase
Query on all issues related to the older V1 version via the tag
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/labels/2024-pre-tef-v4
