### ISSUE TITLE
Governance validation: Triage various governance policy automation frameworks

### ISSUE THREAD

**Issue by fmichaelobrien** [GoogleCloudPlatform/pbmm-on-gcp-onboarding#93]
# design issues pros/cons for defer/target options for various governance policy automation frameworks

Investigate Q on forseti use in the terraform LZ
The Terraform LZ would definitely benefit from using the policy enforcement/verification yamls.  There is policy controller work in the next release of the LZ but multiple sources of validation would be useful.  The default set of rules running on the GCE scanner instance look to be a very good start
https://github.com/forseti-security/forseti-security/tree/master/samples/scanner/scanners 

Chris: Verify custom governance 
Chris: see TF validation preview https://cloud.google.com/blog/products/compliance/google-cloud-cli-terraform-validation-preview

**Comment by fmichaelobrien** [comment]
service account roles that work (2)

```
You1:33 PM
Access Context Manager Admin
Cloud Build Editor
Compute Admin
Compute Network Admin
Logs Configuration Writer
Owner
Project Deleter
Security Admin
Service Account Admin
Service Account Token Creator
Service Usage Admin
Storage Admin
Viewer
Access Context Manager Admin
Billing Account User
Compute Admin
Compute Network Admin
Compute Shared VPC Admin
Folder Admin
Logs Configuration Writer
Organization Policy Administrator
Organization Role Administrator
Organization Viewer
Project Creator
Project Deleter
Security Admin
Service Account Admin
Service Account Token Creator
Service Usage Admin
Storage Admin
Viewer
```

**Comment by obriensystems** [comment]
20240406: Closing issue during retrofit/rebase of this TEF V1 based/modified repo to TEF V4 standards
This issue may participate in the LZ refactor after rebase
Query on all issues related to the older V1 version via the tag
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/labels/2024-pre-tef-v4
