### ISSUE TITLE
Fill out perimeter/non-prod/prod access context manager levels

### ISSUE THREAD

**Issue by fmichaelobrien** [GoogleCloudPlatform/pbmm-on-gcp-onboarding#94]
edit common tfvar
```
access_context_manager = { # REQUIRED OBJECT. VPC Service Controls object. 
  policy_name         = "or" # OPTIONAL EDIT. If null, will be generated by module. Only used when creating new policy.
  policy_id           = "or2" # OPTIONAL EDIT. Only used when previously existing. Includes subsequent runs 
  user_defined_string = "oracm" # Optional EDIT.
  access_level        = {} # leave empty for testing
}
```
<img width="1423" alt="Screen Shot 2022-05-19 at 12 40 04 PM" src="https://user-images.githubusercontent.com/94715080/169353119-d214bfc1-3994-4c3d-927c-aed92bab1368.png">

**Comment by fmichaelobrien** [comment]
see https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/issues/123

**Comment by obriensystems** [comment]
20240406: Closing issue during retrofit/rebase of this TEF V1 based/modified repo to TEF V4 standards
This issue may participate in the LZ refactor after rebase
Query on all issues related to the older V1 version via the tag
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/labels/2024-pre-tef-v4
