### ISSUE TITLE
Procedure for github fetch remote repo pull/merge into local CSR repo - and associated merge conflict avoidance and workload redeploy issues

### ISSUE THREAD

**Issue by fmichaelobrien** [GoogleCloudPlatform/pbmm-on-gcp-onboarding#95]
Q
Chris Carty, 11 min
Do we have any strategies to keep tabs on any potential drift between upstream source and downstream deployments?

A
Not in the repo - but I have been thinking about documenting the repo merge procedure on a remote pull from the github branch and associated CSR local branch.  So far we have been doing manual merges.
raised to track this

Until we finish the 2nd part of the id overlay (do/undo) - we will end up with expected merge conflicts on any pull - I should have the deployment specific ID seds done shortly on top of 
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/issues/41

associated with our need to handle redeployment of workloads during possible teardown/redeployments of infrastructure - like when we moved the perimeter.
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/issues/91

**Comment by fmichaelobrien** [comment]
key the doc off recently added doc folder in https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/blob/main/docs/README.md

**Comment by fmichaelobrien** [comment]
example from guardrails
https://github.com/canada-ca/accelerators_accelerateurs-gcp/issues/24#issuecomment-1087722599
```
 1277  [2022-03-31 20:51:42 -0400] git clone https://github.com/fmichaelobrien/accelerators_accelerateurs-gcp.git
 1278  [2022-03-31 20:52:00 -0400] git checkout -b canada-ca-main main
 1279  [2022-03-31 20:52:03 -0400] cd accelerators_accelerateurs-gcp/
 1280  [2022-03-31 20:52:04 -0400] git checkout -b canada-ca-main main
 1281  [2022-03-31 20:52:12 -0400] git pull git://github.com/canada-ca/accelerators_accelerateurs-gcp.git main
 1282  [2022-03-31 20:53:08 -0400] git config --global pull.rebase false
 1283  [2022-03-31 20:53:11 -0400] git pull git://github.com/canada-ca/accelerators_accelerateurs-gcp.git main
 1287  [2022-03-31 20:57:07 -0400] git add deployment-templates/
 1289  [2022-03-31 20:57:57 -0400] git commit -m "merge remote"
 1290  [2022-03-31 20:58:07 -0400] git push origin main
 1292  [2022-03-31 20:59:09 -0400] git checkout main
 1294  [2022-03-31 20:59:28 -0400] git merge --no-ff canada-ca-main
 1296  [2022-03-31 21:00:15 -0400] git push origin main
```

**Comment by obriensystems** [comment]
20240406: Closing issue during retrofit/rebase of this TEF V1 based/modified repo to TEF V4 standards
This issue may participate in the LZ refactor after rebase
Query on all issues related to the older V1 version via the tag
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/labels/2024-pre-tef-v4
